#[doc = "🧘"]
pub const PERSON_IN_LOTUS_POSITION: crate::Emoji = crate::Emoji {
    glyph: "🧘",
    codepoint: "1F9D8",
    status: crate::Status::FullyQualified,
    introduction_version: 5f32,
    name: "person in lotus position",
    group: "People & Body",
    subgroup: "person-resting",
    is_variant: false,
    variants: &[],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("person in lotus position"),
        keywords: &["meditation", "person in lotus position", "yoga"],
    }],
};
#[doc = "🧘🏻"]
pub const PERSON_IN_LOTUS_POSITION_LIGHT_SKIN_TONE: crate::Emoji = crate::Emoji {
    glyph: "🧘🏻",
    codepoint: "1F9D8 1F3FB",
    status: crate::Status::FullyQualified,
    introduction_version: 5f32,
    name: "person in lotus position: light skin tone",
    group: "People & Body",
    subgroup: "person-resting",
    is_variant: false,
    variants: &[],
    annotations: &[],
};
#[doc = "🧘🏼"]
pub const PERSON_IN_LOTUS_POSITION_MEDIUM_LIGHT_SKIN_TONE: crate::Emoji = crate::Emoji {
    glyph: "🧘🏼",
    codepoint: "1F9D8 1F3FC",
    status: crate::Status::FullyQualified,
    introduction_version: 5f32,
    name: "person in lotus position: medium-light skin tone",
    group: "People & Body",
    subgroup: "person-resting",
    is_variant: false,
    variants: &[],
    annotations: &[],
};
#[doc = "🧘🏽"]
pub const PERSON_IN_LOTUS_POSITION_MEDIUM_SKIN_TONE: crate::Emoji = crate::Emoji {
    glyph: "🧘🏽",
    codepoint: "1F9D8 1F3FD",
    status: crate::Status::FullyQualified,
    introduction_version: 5f32,
    name: "person in lotus position: medium skin tone",
    group: "People & Body",
    subgroup: "person-resting",
    is_variant: false,
    variants: &[],
    annotations: &[],
};
#[doc = "🧘🏾"]
pub const PERSON_IN_LOTUS_POSITION_MEDIUM_DARK_SKIN_TONE: crate::Emoji = crate::Emoji {
    glyph: "🧘🏾",
    codepoint: "1F9D8 1F3FE",
    status: crate::Status::FullyQualified,
    introduction_version: 5f32,
    name: "person in lotus position: medium-dark skin tone",
    group: "People & Body",
    subgroup: "person-resting",
    is_variant: false,
    variants: &[],
    annotations: &[],
};
#[doc = "🧘🏿"]
pub const PERSON_IN_LOTUS_POSITION_DARK_SKIN_TONE: crate::Emoji = crate::Emoji {
    glyph: "🧘🏿",
    codepoint: "1F9D8 1F3FF",
    status: crate::Status::FullyQualified,
    introduction_version: 5f32,
    name: "person in lotus position: dark skin tone",
    group: "People & Body",
    subgroup: "person-resting",
    is_variant: false,
    variants: &[],
    annotations: &[],
};
#[doc = "🧘\u{200d}♂\u{fe0f}"]
pub const MAN_IN_LOTUS_POSITION: crate::Emoji = crate::Emoji {
    glyph: "🧘\u{200d}♂\u{fe0f}",
    codepoint: "1F9D8 200D 2642 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 5f32,
    name: "man in lotus position",
    group: "People & Body",
    subgroup: "person-resting",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "🧘\u{200d}♂",
        codepoint: "1F9D8 200D 2642",
        status: crate::Status::MinimallyQualified,
        introduction_version: 5f32,
        name: "man in lotus position",
        group: "People & Body",
        subgroup: "person-resting",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("man in lotus position"),
        keywords: &["man in lotus position", "meditation", "yoga"],
    }],
};
#[doc = "🧘🏻\u{200d}♂\u{fe0f}"]
pub const MAN_IN_LOTUS_POSITION_LIGHT_SKIN_TONE: crate::Emoji = crate::Emoji {
    glyph: "🧘🏻\u{200d}♂\u{fe0f}",
    codepoint: "1F9D8 1F3FB 200D 2642 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 5f32,
    name: "man in lotus position: light skin tone",
    group: "People & Body",
    subgroup: "person-resting",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "🧘🏻\u{200d}♂",
        codepoint: "1F9D8 1F3FB 200D 2642",
        status: crate::Status::MinimallyQualified,
        introduction_version: 5f32,
        name: "man in lotus position: light skin tone",
        group: "People & Body",
        subgroup: "person-resting",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[],
};
#[doc = "🧘🏼\u{200d}♂\u{fe0f}"]
pub const MAN_IN_LOTUS_POSITION_MEDIUM_LIGHT_SKIN_TONE: crate::Emoji = crate::Emoji {
    glyph: "🧘🏼\u{200d}♂\u{fe0f}",
    codepoint: "1F9D8 1F3FC 200D 2642 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 5f32,
    name: "man in lotus position: medium-light skin tone",
    group: "People & Body",
    subgroup: "person-resting",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "🧘🏼\u{200d}♂",
        codepoint: "1F9D8 1F3FC 200D 2642",
        status: crate::Status::MinimallyQualified,
        introduction_version: 5f32,
        name: "man in lotus position: medium-light skin tone",
        group: "People & Body",
        subgroup: "person-resting",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[],
};
#[doc = "🧘🏽\u{200d}♂\u{fe0f}"]
pub const MAN_IN_LOTUS_POSITION_MEDIUM_SKIN_TONE: crate::Emoji = crate::Emoji {
    glyph: "🧘🏽\u{200d}♂\u{fe0f}",
    codepoint: "1F9D8 1F3FD 200D 2642 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 5f32,
    name: "man in lotus position: medium skin tone",
    group: "People & Body",
    subgroup: "person-resting",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "🧘🏽\u{200d}♂",
        codepoint: "1F9D8 1F3FD 200D 2642",
        status: crate::Status::MinimallyQualified,
        introduction_version: 5f32,
        name: "man in lotus position: medium skin tone",
        group: "People & Body",
        subgroup: "person-resting",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[],
};
#[doc = "🧘🏾\u{200d}♂\u{fe0f}"]
pub const MAN_IN_LOTUS_POSITION_MEDIUM_DARK_SKIN_TONE: crate::Emoji = crate::Emoji {
    glyph: "🧘🏾\u{200d}♂\u{fe0f}",
    codepoint: "1F9D8 1F3FE 200D 2642 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 5f32,
    name: "man in lotus position: medium-dark skin tone",
    group: "People & Body",
    subgroup: "person-resting",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "🧘🏾\u{200d}♂",
        codepoint: "1F9D8 1F3FE 200D 2642",
        status: crate::Status::MinimallyQualified,
        introduction_version: 5f32,
        name: "man in lotus position: medium-dark skin tone",
        group: "People & Body",
        subgroup: "person-resting",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[],
};
#[doc = "🧘🏿\u{200d}♂\u{fe0f}"]
pub const MAN_IN_LOTUS_POSITION_DARK_SKIN_TONE: crate::Emoji = crate::Emoji {
    glyph: "🧘🏿\u{200d}♂\u{fe0f}",
    codepoint: "1F9D8 1F3FF 200D 2642 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 5f32,
    name: "man in lotus position: dark skin tone",
    group: "People & Body",
    subgroup: "person-resting",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "🧘🏿\u{200d}♂",
        codepoint: "1F9D8 1F3FF 200D 2642",
        status: crate::Status::MinimallyQualified,
        introduction_version: 5f32,
        name: "man in lotus position: dark skin tone",
        group: "People & Body",
        subgroup: "person-resting",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[],
};
#[doc = "🧘\u{200d}♀\u{fe0f}"]
pub const WOMAN_IN_LOTUS_POSITION: crate::Emoji = crate::Emoji {
    glyph: "🧘\u{200d}♀\u{fe0f}",
    codepoint: "1F9D8 200D 2640 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 5f32,
    name: "woman in lotus position",
    group: "People & Body",
    subgroup: "person-resting",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "🧘\u{200d}♀",
        codepoint: "1F9D8 200D 2640",
        status: crate::Status::MinimallyQualified,
        introduction_version: 5f32,
        name: "woman in lotus position",
        group: "People & Body",
        subgroup: "person-resting",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("woman in lotus position"),
        keywords: &["meditation", "woman in lotus position", "yoga"],
    }],
};
#[doc = "🧘🏻\u{200d}♀\u{fe0f}"]
pub const WOMAN_IN_LOTUS_POSITION_LIGHT_SKIN_TONE: crate::Emoji = crate::Emoji {
    glyph: "🧘🏻\u{200d}♀\u{fe0f}",
    codepoint: "1F9D8 1F3FB 200D 2640 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 5f32,
    name: "woman in lotus position: light skin tone",
    group: "People & Body",
    subgroup: "person-resting",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "🧘🏻\u{200d}♀",
        codepoint: "1F9D8 1F3FB 200D 2640",
        status: crate::Status::MinimallyQualified,
        introduction_version: 5f32,
        name: "woman in lotus position: light skin tone",
        group: "People & Body",
        subgroup: "person-resting",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[],
};
#[doc = "🧘🏼\u{200d}♀\u{fe0f}"]
pub const WOMAN_IN_LOTUS_POSITION_MEDIUM_LIGHT_SKIN_TONE: crate::Emoji = crate::Emoji {
    glyph: "🧘🏼\u{200d}♀\u{fe0f}",
    codepoint: "1F9D8 1F3FC 200D 2640 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 5f32,
    name: "woman in lotus position: medium-light skin tone",
    group: "People & Body",
    subgroup: "person-resting",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "🧘🏼\u{200d}♀",
        codepoint: "1F9D8 1F3FC 200D 2640",
        status: crate::Status::MinimallyQualified,
        introduction_version: 5f32,
        name: "woman in lotus position: medium-light skin tone",
        group: "People & Body",
        subgroup: "person-resting",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[],
};
#[doc = "🧘🏽\u{200d}♀\u{fe0f}"]
pub const WOMAN_IN_LOTUS_POSITION_MEDIUM_SKIN_TONE: crate::Emoji = crate::Emoji {
    glyph: "🧘🏽\u{200d}♀\u{fe0f}",
    codepoint: "1F9D8 1F3FD 200D 2640 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 5f32,
    name: "woman in lotus position: medium skin tone",
    group: "People & Body",
    subgroup: "person-resting",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "🧘🏽\u{200d}♀",
        codepoint: "1F9D8 1F3FD 200D 2640",
        status: crate::Status::MinimallyQualified,
        introduction_version: 5f32,
        name: "woman in lotus position: medium skin tone",
        group: "People & Body",
        subgroup: "person-resting",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[],
};
#[doc = "🧘🏾\u{200d}♀\u{fe0f}"]
pub const WOMAN_IN_LOTUS_POSITION_MEDIUM_DARK_SKIN_TONE: crate::Emoji = crate::Emoji {
    glyph: "🧘🏾\u{200d}♀\u{fe0f}",
    codepoint: "1F9D8 1F3FE 200D 2640 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 5f32,
    name: "woman in lotus position: medium-dark skin tone",
    group: "People & Body",
    subgroup: "person-resting",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "🧘🏾\u{200d}♀",
        codepoint: "1F9D8 1F3FE 200D 2640",
        status: crate::Status::MinimallyQualified,
        introduction_version: 5f32,
        name: "woman in lotus position: medium-dark skin tone",
        group: "People & Body",
        subgroup: "person-resting",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[],
};
#[doc = "🧘🏿\u{200d}♀\u{fe0f}"]
pub const WOMAN_IN_LOTUS_POSITION_DARK_SKIN_TONE: crate::Emoji = crate::Emoji {
    glyph: "🧘🏿\u{200d}♀\u{fe0f}",
    codepoint: "1F9D8 1F3FF 200D 2640 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 5f32,
    name: "woman in lotus position: dark skin tone",
    group: "People & Body",
    subgroup: "person-resting",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "🧘🏿\u{200d}♀",
        codepoint: "1F9D8 1F3FF 200D 2640",
        status: crate::Status::MinimallyQualified,
        introduction_version: 5f32,
        name: "woman in lotus position: dark skin tone",
        group: "People & Body",
        subgroup: "person-resting",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[],
};
#[doc = "🛀"]
pub const PERSON_TAKING_BATH: crate::Emoji = crate::Emoji {
    glyph: "🛀",
    codepoint: "1F6C0",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "person taking bath",
    group: "People & Body",
    subgroup: "person-resting",
    is_variant: false,
    variants: &[],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("person taking bath"),
        keywords: &["bath", "bathtub", "person taking bath"],
    }],
};
#[doc = "🛀🏻"]
pub const PERSON_TAKING_BATH_LIGHT_SKIN_TONE: crate::Emoji = crate::Emoji {
    glyph: "🛀🏻",
    codepoint: "1F6C0 1F3FB",
    status: crate::Status::FullyQualified,
    introduction_version: 1f32,
    name: "person taking bath: light skin tone",
    group: "People & Body",
    subgroup: "person-resting",
    is_variant: false,
    variants: &[],
    annotations: &[],
};
#[doc = "🛀🏼"]
pub const PERSON_TAKING_BATH_MEDIUM_LIGHT_SKIN_TONE: crate::Emoji = crate::Emoji {
    glyph: "🛀🏼",
    codepoint: "1F6C0 1F3FC",
    status: crate::Status::FullyQualified,
    introduction_version: 1f32,
    name: "person taking bath: medium-light skin tone",
    group: "People & Body",
    subgroup: "person-resting",
    is_variant: false,
    variants: &[],
    annotations: &[],
};
#[doc = "🛀🏽"]
pub const PERSON_TAKING_BATH_MEDIUM_SKIN_TONE: crate::Emoji = crate::Emoji {
    glyph: "🛀🏽",
    codepoint: "1F6C0 1F3FD",
    status: crate::Status::FullyQualified,
    introduction_version: 1f32,
    name: "person taking bath: medium skin tone",
    group: "People & Body",
    subgroup: "person-resting",
    is_variant: false,
    variants: &[],
    annotations: &[],
};
#[doc = "🛀🏾"]
pub const PERSON_TAKING_BATH_MEDIUM_DARK_SKIN_TONE: crate::Emoji = crate::Emoji {
    glyph: "🛀🏾",
    codepoint: "1F6C0 1F3FE",
    status: crate::Status::FullyQualified,
    introduction_version: 1f32,
    name: "person taking bath: medium-dark skin tone",
    group: "People & Body",
    subgroup: "person-resting",
    is_variant: false,
    variants: &[],
    annotations: &[],
};
#[doc = "🛀🏿"]
pub const PERSON_TAKING_BATH_DARK_SKIN_TONE: crate::Emoji = crate::Emoji {
    glyph: "🛀🏿",
    codepoint: "1F6C0 1F3FF",
    status: crate::Status::FullyQualified,
    introduction_version: 1f32,
    name: "person taking bath: dark skin tone",
    group: "People & Body",
    subgroup: "person-resting",
    is_variant: false,
    variants: &[],
    annotations: &[],
};
#[doc = "🛌"]
pub const PERSON_IN_BED: crate::Emoji = crate::Emoji {
    glyph: "🛌",
    codepoint: "1F6CC",
    status: crate::Status::FullyQualified,
    introduction_version: 1f32,
    name: "person in bed",
    group: "People & Body",
    subgroup: "person-resting",
    is_variant: false,
    variants: &[],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("person in bed"),
        keywords: &["hotel", "person in bed", "sleep"],
    }],
};
#[doc = "🛌🏻"]
pub const PERSON_IN_BED_LIGHT_SKIN_TONE: crate::Emoji = crate::Emoji {
    glyph: "🛌🏻",
    codepoint: "1F6CC 1F3FB",
    status: crate::Status::FullyQualified,
    introduction_version: 4f32,
    name: "person in bed: light skin tone",
    group: "People & Body",
    subgroup: "person-resting",
    is_variant: false,
    variants: &[],
    annotations: &[],
};
#[doc = "🛌🏼"]
pub const PERSON_IN_BED_MEDIUM_LIGHT_SKIN_TONE: crate::Emoji = crate::Emoji {
    glyph: "🛌🏼",
    codepoint: "1F6CC 1F3FC",
    status: crate::Status::FullyQualified,
    introduction_version: 4f32,
    name: "person in bed: medium-light skin tone",
    group: "People & Body",
    subgroup: "person-resting",
    is_variant: false,
    variants: &[],
    annotations: &[],
};
#[doc = "🛌🏽"]
pub const PERSON_IN_BED_MEDIUM_SKIN_TONE: crate::Emoji = crate::Emoji {
    glyph: "🛌🏽",
    codepoint: "1F6CC 1F3FD",
    status: crate::Status::FullyQualified,
    introduction_version: 4f32,
    name: "person in bed: medium skin tone",
    group: "People & Body",
    subgroup: "person-resting",
    is_variant: false,
    variants: &[],
    annotations: &[],
};
#[doc = "🛌🏾"]
pub const PERSON_IN_BED_MEDIUM_DARK_SKIN_TONE: crate::Emoji = crate::Emoji {
    glyph: "🛌🏾",
    codepoint: "1F6CC 1F3FE",
    status: crate::Status::FullyQualified,
    introduction_version: 4f32,
    name: "person in bed: medium-dark skin tone",
    group: "People & Body",
    subgroup: "person-resting",
    is_variant: false,
    variants: &[],
    annotations: &[],
};
#[doc = "🛌🏿"]
pub const PERSON_IN_BED_DARK_SKIN_TONE: crate::Emoji = crate::Emoji {
    glyph: "🛌🏿",
    codepoint: "1F6CC 1F3FF",
    status: crate::Status::FullyQualified,
    introduction_version: 4f32,
    name: "person in bed: dark skin tone",
    group: "People & Body",
    subgroup: "person-resting",
    is_variant: false,
    variants: &[],
    annotations: &[],
};
