#[doc = "🏁"]
pub const CHEQUERED_FLAG: crate::Emoji = crate::Emoji {
    glyph: "🏁",
    codepoint: "1F3C1",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "chequered flag",
    group: "Flags",
    subgroup: "flag",
    is_variant: false,
    variants: &[],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("chequered flag"),
        keywords: &["checkered", "chequered", "chequered flag", "racing"],
    }],
};
#[doc = "🚩"]
pub const TRIANGULAR_FLAG: crate::Emoji = crate::Emoji {
    glyph: "🚩",
    codepoint: "1F6A9",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "triangular flag",
    group: "Flags",
    subgroup: "flag",
    is_variant: false,
    variants: &[],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("triangular flag"),
        keywords: &["post", "triangular flag"],
    }],
};
#[doc = "🎌"]
pub const CROSSED_FLAGS: crate::Emoji = crate::Emoji {
    glyph: "🎌",
    codepoint: "1F38C",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "crossed flags",
    group: "Flags",
    subgroup: "flag",
    is_variant: false,
    variants: &[],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("crossed flags"),
        keywords: &[
            "Japanese",
            "celebration",
            "cross",
            "crossed",
            "crossed flags",
        ],
    }],
};
#[doc = "🏴"]
pub const BLACK_FLAG: crate::Emoji = crate::Emoji {
    glyph: "🏴",
    codepoint: "1F3F4",
    status: crate::Status::FullyQualified,
    introduction_version: 1f32,
    name: "black flag",
    group: "Flags",
    subgroup: "flag",
    is_variant: false,
    variants: &[],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("black flag"),
        keywords: &["black flag", "waving"],
    }],
};
#[doc = "🏳\u{fe0f}"]
pub const WHITE_FLAG: crate::Emoji = crate::Emoji {
    glyph: "🏳\u{fe0f}",
    codepoint: "1F3F3 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.7f32,
    name: "white flag",
    group: "Flags",
    subgroup: "flag",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "🏳",
        codepoint: "1F3F3",
        status: crate::Status::Unqualified,
        introduction_version: 0.7f32,
        name: "white flag",
        group: "Flags",
        subgroup: "flag",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("white flag"),
        keywords: &["waving", "white flag"],
    }],
};
#[doc = "🏳\u{fe0f}\u{200d}🌈"]
pub const RAINBOW_FLAG: crate::Emoji = crate::Emoji {
    glyph: "🏳\u{fe0f}\u{200d}🌈",
    codepoint: "1F3F3 FE0F 200D 1F308",
    status: crate::Status::FullyQualified,
    introduction_version: 4f32,
    name: "rainbow flag",
    group: "Flags",
    subgroup: "flag",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "🏳\u{200d}🌈",
        codepoint: "1F3F3 200D 1F308",
        status: crate::Status::Unqualified,
        introduction_version: 4f32,
        name: "rainbow flag",
        group: "Flags",
        subgroup: "flag",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("rainbow flag"),
        keywords: &["pride", "rainbow", "rainbow flag"],
    }],
};
#[doc = "🏳\u{fe0f}\u{200d}⚧\u{fe0f}"]
pub const TRANSGENDER_FLAG: crate::Emoji = crate::Emoji {
    glyph: "🏳\u{fe0f}\u{200d}⚧\u{fe0f}",
    codepoint: "1F3F3 FE0F 200D 26A7 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 13f32,
    name: "transgender flag",
    group: "Flags",
    subgroup: "flag",
    is_variant: false,
    variants: &[
        crate::Emoji {
            glyph: "🏳\u{200d}⚧\u{fe0f}",
            codepoint: "1F3F3 200D 26A7 FE0F",
            status: crate::Status::Unqualified,
            introduction_version: 13f32,
            name: "transgender flag",
            group: "Flags",
            subgroup: "flag",
            is_variant: true,
            variants: &[],
            annotations: &[],
        },
        crate::Emoji {
            glyph: "🏳\u{fe0f}\u{200d}⚧",
            codepoint: "1F3F3 FE0F 200D 26A7",
            status: crate::Status::Unqualified,
            introduction_version: 13f32,
            name: "transgender flag",
            group: "Flags",
            subgroup: "flag",
            is_variant: true,
            variants: &[],
            annotations: &[],
        },
        crate::Emoji {
            glyph: "🏳\u{200d}⚧",
            codepoint: "1F3F3 200D 26A7",
            status: crate::Status::Unqualified,
            introduction_version: 13f32,
            name: "transgender flag",
            group: "Flags",
            subgroup: "flag",
            is_variant: true,
            variants: &[],
            annotations: &[],
        },
    ],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("transgender flag"),
        keywords: &["flag", "light blue", "pink", "transgender", "white"],
    }],
};
#[doc = "🏴\u{200d}☠\u{fe0f}"]
pub const PIRATE_FLAG: crate::Emoji = crate::Emoji {
    glyph: "🏴\u{200d}☠\u{fe0f}",
    codepoint: "1F3F4 200D 2620 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 11f32,
    name: "pirate flag",
    group: "Flags",
    subgroup: "flag",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "🏴\u{200d}☠",
        codepoint: "1F3F4 200D 2620",
        status: crate::Status::MinimallyQualified,
        introduction_version: 11f32,
        name: "pirate flag",
        group: "Flags",
        subgroup: "flag",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("pirate flag"),
        keywords: &[
            "Jolly Roger",
            "pirate",
            "pirate flag",
            "plunder",
            "treasure",
        ],
    }],
};
