#[doc = "✏\u{fe0f}"]
pub const PENCIL: crate::Emoji = crate::Emoji {
    glyph: "✏\u{fe0f}",
    codepoint: "270F FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "pencil",
    group: "Objects",
    subgroup: "writing",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "✏",
        codepoint: "270F",
        status: crate::Status::Unqualified,
        introduction_version: 0.6f32,
        name: "pencil",
        group: "Objects",
        subgroup: "writing",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("pencil"),
        keywords: &["pencil"],
    }],
};
#[doc = "✒\u{fe0f}"]
pub const BLACK_NIB: crate::Emoji = crate::Emoji {
    glyph: "✒\u{fe0f}",
    codepoint: "2712 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "black nib",
    group: "Objects",
    subgroup: "writing",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "✒",
        codepoint: "2712",
        status: crate::Status::Unqualified,
        introduction_version: 0.6f32,
        name: "black nib",
        group: "Objects",
        subgroup: "writing",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("black nib"),
        keywords: &["black nib", "nib", "pen"],
    }],
};
#[doc = "🖋\u{fe0f}"]
pub const FOUNTAIN_PEN: crate::Emoji = crate::Emoji {
    glyph: "🖋\u{fe0f}",
    codepoint: "1F58B FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.7f32,
    name: "fountain pen",
    group: "Objects",
    subgroup: "writing",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "🖋",
        codepoint: "1F58B",
        status: crate::Status::Unqualified,
        introduction_version: 0.7f32,
        name: "fountain pen",
        group: "Objects",
        subgroup: "writing",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("fountain pen"),
        keywords: &["fountain", "pen"],
    }],
};
#[doc = "🖊\u{fe0f}"]
pub const PEN: crate::Emoji = crate::Emoji {
    glyph: "🖊\u{fe0f}",
    codepoint: "1F58A FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.7f32,
    name: "pen",
    group: "Objects",
    subgroup: "writing",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "🖊",
        codepoint: "1F58A",
        status: crate::Status::Unqualified,
        introduction_version: 0.7f32,
        name: "pen",
        group: "Objects",
        subgroup: "writing",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("pen"),
        keywords: &["ballpoint", "pen"],
    }],
};
#[doc = "🖌\u{fe0f}"]
pub const PAINTBRUSH: crate::Emoji = crate::Emoji {
    glyph: "🖌\u{fe0f}",
    codepoint: "1F58C FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.7f32,
    name: "paintbrush",
    group: "Objects",
    subgroup: "writing",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "🖌",
        codepoint: "1F58C",
        status: crate::Status::Unqualified,
        introduction_version: 0.7f32,
        name: "paintbrush",
        group: "Objects",
        subgroup: "writing",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("paintbrush"),
        keywords: &["paintbrush", "painting"],
    }],
};
#[doc = "🖍\u{fe0f}"]
pub const CRAYON: crate::Emoji = crate::Emoji {
    glyph: "🖍\u{fe0f}",
    codepoint: "1F58D FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.7f32,
    name: "crayon",
    group: "Objects",
    subgroup: "writing",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "🖍",
        codepoint: "1F58D",
        status: crate::Status::Unqualified,
        introduction_version: 0.7f32,
        name: "crayon",
        group: "Objects",
        subgroup: "writing",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("crayon"),
        keywords: &["crayon"],
    }],
};
#[doc = "📝"]
pub const MEMO: crate::Emoji = crate::Emoji {
    glyph: "📝",
    codepoint: "1F4DD",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "memo",
    group: "Objects",
    subgroup: "writing",
    is_variant: false,
    variants: &[],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("memo"),
        keywords: &["memo", "pencil"],
    }],
};
