#[doc = "🤠"]
pub const COWBOY_HAT_FACE : crate :: Emoji = crate :: Emoji { glyph : "🤠" , codepoint : "1F920" , status : crate :: Status :: FullyQualified , introduction_version : 3f32 , name : "cowboy hat face" , group : "Smileys & Emotion" , subgroup : "face-hat" , is_variant : false , variants : & [] , annotations : & [crate :: Annotation { lang : "af" , tts : Some ("gesig met cowboy-hoed") , keywords : & ["cowboy" , "gesig" , "gesig met cowboy-hoed" , "hoed"] , } , crate :: Annotation { lang : "am" , tts : Some ("የከብት ጠባቂ ኮፍያ ፊት") , keywords : & ["ከብት ጠባቂ" , "ኮፍያ" , "የከብት ጠባቂ ኮፍያ ፊት" , "ፊት"] , } , crate :: Annotation { lang : "ar" , tts : Some ("وجه بقبعة راعي بقر") , keywords : & ["راعي بقر" , "قبعة" , "وجه" , "وجه بقبعة راعي بقر"] , } , crate :: Annotation { lang : "as" , tts : Some ("গৰখীয\u{9bc}\u{9be} ট\u{9c1}পী পৰিহিত চেহেৰ\u{9be}") , keywords : & ["গৰখীয\u{9bc}\u{9be}" , "গৰখীয\u{9bc}\u{9be} ট\u{9c1}পী পৰিহিত চেহেৰ\u{9be}" , "ট\u{9c1}পী" , "ম\u{9c1}খ"] , } , crate :: Annotation { lang : "az" , tts : Some ("papaqlı qaqaş üzü") , keywords : & ["papaqlı" , "papaqlı qaqaş üzü" , "qaqaş" , "üz"] , } , crate :: Annotation { lang : "be" , tts : Some ("каўбой у капелюшы") , keywords : & ["капялюш" , "каўбой" , "каўбой у капелюшы"] , } , crate :: Annotation { lang : "bg" , tts : Some ("лице с каубойска шапка") , keywords : & ["каубой" , "каубойка" , "лице" , "лице с каубойска шапка" , "шапка"] , } , crate :: Annotation { lang : "bn" , tts : Some ("ক\u{9be}উবয\u{9bc} ট\u{9c1}পি পর\u{9be} ম\u{9c1}খ") , keywords : & ["ক\u{9be}উগ\u{9be}র\u{9cd}ল" , "ক\u{9be}উবয\u{9bc}" , "ক\u{9be}উবয\u{9bc} ট\u{9c1}পি পর\u{9be} ম\u{9c1}খ" , "ট\u{9c1}পি" , "ম\u{9c1}খ"] , } , crate :: Annotation { lang : "bs" , tts : Some ("lice s kaubojskim šeširom") , keywords : & ["kauboj" , "lice" , "lice s kaubojskim šeširom" , "šešir"] , } , crate :: Annotation { lang : "ca" , tts : Some ("cara amb barret de vaquer") , keywords : & ["barret" , "cara" , "cara amb barret de vaquer" , "cowboy" , "vaquer" , "vaquera"] , } , crate :: Annotation { lang : "chr" , tts : Some ("ᏗᏍᎳᏗᏍᎩ ᎤᎵᏍᏇᏚᎩ ᎤᎧᏛ") , keywords : & ["ᎤᎧᏛ" , "ᎤᎵᏍᏇᏚᎩ" , "ᏗᏍᎳᏗᏍᎩ"] , } , crate :: Annotation { lang : "cs" , tts : Some ("obličej s kovbojským kloboukem") , keywords : & ["klobouk" , "kovboj" , "obličej s kovbojským kloboukem" , "smajlík" , "tvář" , "výraz"] , } , crate :: Annotation { lang : "cy" , tts : Some ("wyneb het cowboi") , keywords : & ["cowboi" , "cowmones" , "het" , "wyneb"] , } , crate :: Annotation { lang : "da" , tts : Some ("ansigt med cowboyhat") , keywords : & ["ansigt" , "ansigt med cowboyhat" , "cowboy" , "cowboyhat" , "cowgirl" , "hat"] , } , crate :: Annotation { lang : "de" , tts : Some ("Gesicht mit Cowboyhut") , keywords : & ["Cowboy" , "Gesicht" , "Gesicht mit Cowboyhut" , "Hut"] , } , crate :: Annotation { lang : "el" , tts : Some ("καουμπόης με καπέλο") , keywords : & ["καουμπόης" , "καουμπόης με καπέλο" , "καουμπόισσα" , "καπέλο" , "πρόσωπο"] , } , crate :: Annotation { lang : "en" , tts : Some ("cowboy hat face") , keywords : & ["cowboy" , "cowgirl" , "face" , "hat"] , } , crate :: Annotation { lang : "en_AU" , tts : Some ("↑↑↑") , keywords : & ["↑↑↑"] , } , crate :: Annotation { lang : "en_CA" , tts : Some ("↑↑↑") , keywords : & ["↑↑↑"] , } , crate :: Annotation { lang : "en_GB" , tts : Some ("↑↑↑") , keywords : & ["↑↑↑"] , } , crate :: Annotation { lang : "en_IN" , tts : Some ("↑↑↑") , keywords : & ["↑↑↑"] , } , crate :: Annotation { lang : "es" , tts : Some ("cara con sombrero de vaquero") , keywords : & ["cara" , "cara con sombrero de vaquero" , "sombrero" , "vaquera" , "vaquero"] , } , crate :: Annotation { lang : "es_419" , tts : Some ("↑↑↑") , keywords : & ["cara" , "cara con sombrero de vaquero" , "sombrero" , "vaquera" , "vaquero"] , } , crate :: Annotation { lang : "es_MX" , tts : Some ("↑↑↑") , keywords : & ["↑↑↑"] , } , crate :: Annotation { lang : "es_US" , tts : Some ("↑↑↑") , keywords : & ["↑↑↑"] , } , crate :: Annotation { lang : "et" , tts : Some ("kauboimütsiga nägu") , keywords : & ["kauboi" , "kauboimütsiga nägu" , "müts" , "nägu"] , } , crate :: Annotation { lang : "eu" , tts : Some ("behizain txanodunaren aurpegia") , keywords : & ["aurpegi" , "behizain" , "behizain txanodunaren aurpegia" , "txano" , "unai"] , } , crate :: Annotation { lang : "fa" , tts : Some ("کلاه کابوی") , keywords : & ["صورت" , "صورت کلاه\u{200c}به\u{200c}سر" , "کلاه" , "کلاه کابوی" , "گاوچران"] , } , crate :: Annotation { lang : "fi" , tts : Some ("cowboy-hattu") , keywords : & ["cowboy" , "cowboy-hattu" , "hattu" , "kasvot"] , } , crate :: Annotation { lang : "fil" , tts : Some ("mukha na may cowboy hat") , keywords : & ["cowboy" , "cowgirl" , "mukha" , "mukha na may cowboy hat" , "sombrero"] , } , crate :: Annotation { lang : "fo" , tts : Some ("andlit við cowboyhatti") , keywords : & ["andlit" , "andlit við cowboyhatti" , "cowboy" , "hattur" , "kovboy"] , } , crate :: Annotation { lang : "fr" , tts : Some ("visage avec chapeau de cowboy") , keywords : & ["chapeau" , "cowboy" , "visage" , "visage avec chapeau de cowboy"] , } , crate :: Annotation { lang : "fr_CA" , tts : Some ("visage avec chapeau de cowboy") , keywords : & ["↑↑↑"] , } , crate :: Annotation { lang : "ga" , tts : Some ("straoiseog le hata buachaill bó") , keywords : & ["aghaidh" , "buachaill bó" , "cailín" , "hata" , "hata buachaill bó" , "straoiseog le hata buachaill bó"] , } , crate :: Annotation { lang : "gd" , tts : Some ("aodann le ad cowboy") , keywords : & ["ad" , "aodann" , "aodann le ad cowboy" , "cowboy" , "cowgirl"] , } , crate :: Annotation { lang : "gl" , tts : Some ("sombreiro de vaqueiro") , keywords : & ["cara" , "sombreiro" , "sombreiro de vaqueiro" , "vaqueira" , "vaqueiro"] , } , crate :: Annotation { lang : "gu" , tts : Some ("કાઉબૉય હ\u{ac5}ટવાળો ચહ\u{ac7}રો") , keywords : & ["કાઉગર\u{acd}લ" , "કાઉબૉય" , "કાઉબૉય હ\u{ac5}ટવાળો ચહ\u{ac7}રો" , "ચહ\u{ac7}રો" , "હ\u{ac5}ટ"] , } , crate :: Annotation { lang : "ha" , tts : Some ("fuska mai hular kaboyi") , keywords : & ["fuska" , "fuska mai hular kaboyi" , "hula" , "kaboyi" , "kaboyi na mace"] , } , crate :: Annotation { lang : "he" , tts : Some ("פרצוף עם כובע בוקרים") , keywords : & ["בוקרים" , "כובע" , "פרצוף" , "פרצוף עם כובע בוקרים" , "קאובוי"] , } , crate :: Annotation { lang : "hi" , tts : Some ("काउबॉय ह\u{948}ट क\u{947} साथ च\u{947}हरा") , keywords : & ["काउगर\u{94d}ल" , "काउबॉय" , "काउबॉय ह\u{948}ट क\u{947} साथ च\u{947}हरा" , "च\u{947}हरा" , "टोपी"] , } , crate :: Annotation { lang : "hr" , tts : Some ("kauboj sa šeširom") , keywords : & ["kauboj" , "kauboj sa šeširom" , "lice" , "šešir"] , } , crate :: Annotation { lang : "hu" , tts : Some ("cowboykalapos fej") , keywords : & ["cowboy" , "cowboykalapos fej" , "fej" , "kalap"] , } , crate :: Annotation { lang : "hy" , tts : Some ("կովբոյի դեմք") , keywords : & ["գլխարկ" , "դեմք" , "կովբոյ" , "կովբոյի դեմք"] , } , crate :: Annotation { lang : "id" , tts : Some ("wajah koboi") , keywords : & ["cowboy" , "cowgirl" , "koboi" , "topi" , "wajah koboi"] , } , crate :: Annotation { lang : "ig" , tts : Some ("ihu okpu onye ọchụụ nnama") , keywords : & ["ihu" , "ihu okpu onye ọchụụ nnama" , "nwanyị ọchụụ nnama" , "nwoke ọchụụ nnama" , "okpu"] , } , crate :: Annotation { lang : "is" , tts : Some ("kúreki") , keywords : & ["hattur" , "kúreki"] , } , crate :: Annotation { lang : "it" , tts : Some ("faccina con cappello da cowboy") , keywords : & ["cappello" , "cowboy" , "faccina" , "faccina con cappello da cowboy"] , } , crate :: Annotation { lang : "ja" , tts : Some ("カウボーイの顔") , keywords : & ["カウガール" , "カウボーイ" , "カウボーイの顔" , "顔"] , } , crate :: Annotation { lang : "jv" , tts : Some ("rai nganggo topi koboi") , keywords : & ["koboi lanang" , "koboi wadon" , "rai" , "rai nganggo topi koboi" , "topi"] , } , crate :: Annotation { lang : "ka" , tts : Some ("სახე კოვბოის ქუდით") , keywords : & ["კოვბოი" , "კოვბოი გოგონა" , "სახე" , "სახე კოვბოის ქუდით" , "ქუდი"] , } , crate :: Annotation { lang : "kk" , tts : Some ("ковбой қалпағы") , keywords : & ["ковбой" , "ковбой қалпағы" , "қалпақ"] , } , crate :: Annotation { lang : "kl" , tts : Some ("cowboyhat ansigt") , keywords : & ["ansigt" , "cowboyhat" , "cowgirl" , "hat"] , } , crate :: Annotation { lang : "km" , tts : Some ("ម\u{17bb}ខពាក\u{17cb}ម\u{17bd}កខ\u{17bc}វប\u{17ca}យ") , keywords : & ["ខ\u{17bc}វប\u{17ca}យ" , "ខ\u{17bc}វហ\u{17d2}គ\u{17ba}ល" , "ម\u{17bb}ខ" , "ម\u{17bb}ខពាក\u{17cb}ម\u{17bd}កខ\u{17bc}វប\u{17ca}យ" , "ម\u{17bd}ក"] , } , crate :: Annotation { lang : "kn" , tts : Some ("ಕ\u{ccc}ಬಾಯ\u{ccd} ಟೋಪ\u{cbf} ಮುಖ") , keywords : & ["ಕ\u{ccc}ಗರ\u{ccd}ಲ\u{ccd}" , "ಕ\u{ccc}ಬಾಯ\u{ccd}" , "ಟೋಪ\u{cbf}" , "ಮುಖ"] , } , crate :: Annotation { lang : "ko" , tts : Some ("카우보이 모자 쓴 얼굴") , keywords : & ["모자" , "얼굴" , "카우보이" , "카우보이 모자 쓴 얼굴"] , } , crate :: Annotation { lang : "kok" , tts : Some ("कावबॉय ह\u{945}ट घाल\u{94d}लो च\u{947}रो") , keywords : & ["कावगर\u{94d}ल" , "कावबॉय" , "कावबॉय ह\u{945}ट घाल\u{94d}लो च\u{947}रो" , "च\u{947}रो" , "ह\u{945}ट"] , } , crate :: Annotation { lang : "ky" , tts : Some ("ковбойдун шляпасын кийген бет") , keywords : & ["бет" , "ковбой" , "ковбойдун шляпасын кийген бет" , "шляпа"] , } , crate :: Annotation { lang : "lb" , tts : Some ("Gesiicht mat Cowboyshutt") , keywords : & ["Cowboy" , "Cowgirl" , "Gesiicht" , "Gesiicht mat Cowboyshutt" , "Hutt"] , } , crate :: Annotation { lang : "lo" , tts : Some ("ໜ\u{ec9}າໃສ\u{ec8}ໝວກຄາວບອຍ") , keywords : & ["ຄາວບອຍ" , "ຄາວເກ\u{eb5}" , "ໜ\u{ec9}າ" , "ໜ\u{ec9}າໃສ\u{ec8}ໝວກຄາວບອຍ" , "ໝວກ"] , } , crate :: Annotation { lang : "lt" , tts : Some ("kaubojaus veidas su skrybėle") , keywords : & ["kaubojaus veidas su skrybėle" , "kaubojus" , "skrybėlė" , "veidas"] , } , crate :: Annotation { lang : "lv" , tts : Some ("seja kovboja cepurē") , keywords : & ["cepure" , "kovbojs" , "seja" , "seja ar kovboja cepuri" , "seja kovboja cepurē"] , } , crate :: Annotation { lang : "mi" , tts : Some ("kanohi pōtae kaupoi") , keywords : & ["kanohi" , "kauhine" , "kaupoi" , "pōtae"] , } , crate :: Annotation { lang : "mk" , tts : Some ("каубој") , keywords : & ["каубој" , "лице" , "шешир"] , } , crate :: Annotation { lang : "ml" , tts : Some ("ക\u{d57}ബോയ\u{d4d} തൊപ\u{d4d}പിയ\u{d41}ള\u{d4d}ള മ\u{d41}ഖം") , keywords : & ["ക\u{d57}ഗേൾ" , "ക\u{d57}ബോയി" , "ക\u{d57}ബോയ\u{d4d} തൊപ\u{d4d}പിയ\u{d41}ള\u{d4d}ള മ\u{d41}ഖം" , "തൊപ\u{d4d}പി" , "മ\u{d41}ഖം" , "ഹ\u{d3e}റ\u{d4d}റ\u{d4d}"] , } , crate :: Annotation { lang : "mn" , tts : Some ("ковбой малгайтай царай") , keywords : & ["ковбой" , "ковбой малгайтай царай" , "малгай" , "охин" , "царай"] , } , crate :: Annotation { lang : "mr" , tts : Some ("काऊबॉय ह\u{945}ट लावल\u{947}ला च\u{947}हरा") , keywords : & ["काऊगर\u{94d}ल" , "काऊबॉय" , "काऊबॉय ह\u{945}ट लावल\u{947}ला च\u{947}हरा" , "च\u{947}हरा" , "ह\u{945}ट"] , } , crate :: Annotation { lang : "ms" , tts : Some ("muka koboi") , keywords : & ["koboi" , "muka" , "topi"] , } , crate :: Annotation { lang : "mt" , tts : Some ("wiċċ b’kappell tal-cowboys") , keywords : & ["cowboy" , "cowgirl" , "kappell" , "wiċċ" , "wiċċ b’kappell tal-cowboys"] , } , crate :: Annotation { lang : "my" , tts : Some ("န\u{103d}ားကျောင\u{103a}းသား ဦးထ\u{102f}ပ\u{103a} ဆောင\u{103a}းထားသည\u{1037}\u{103a}ရ\u{102f}ပ\u{103a}") , keywords : & ["န\u{103d}ားကျောင\u{103a}းသမ" , "န\u{103d}ားကျောင\u{103a}းသား" , "န\u{103d}ားကျောင\u{103a}းသား ဦးထ\u{102f}ပ\u{103a} ဆောင\u{103a}းထားသည\u{1037}\u{103a}ရ\u{102f}ပ\u{103a}" , "မျက\u{103a}န\u{103e}ာ" , "ဦးထ\u{102f}တ\u{103a}"] , } , crate :: Annotation { lang : "nb" , tts : Some ("fjes med cowboyhatt") , keywords : & ["cowboy" , "cowgirl" , "fjes" , "fjes med cowboyhatt" , "hatt"] , } , crate :: Annotation { lang : "ne" , tts : Some ("काउव\u{94d}वाइ ह\u{94d}याट अन\u{941}हार") , keywords : & ["अन\u{941}हार" , "काउगर\u{94d}ल" , "काउव\u{94d}वाइ" , "ह\u{94d}याट"] , } , crate :: Annotation { lang : "nl" , tts : Some ("gezicht met cowboyhoed") , keywords : & ["cowboy" , "cowgirl" , "gezicht" , "gezicht met cowboyhoed" , "hoed"] , } , crate :: Annotation { lang : "nn" , tts : Some ("fjes med cowboyhatt") , keywords : & ["cowboy" , "cowgirl" , "fjes" , "fjes med cowboyhatt" , "hatt"] , } , crate :: Annotation { lang : "or" , tts : Some ("କ\u{b3e}ଓବଏ ଟୋପ\u{b3f} ପ\u{b3f}ନ\u{b4d}ଧ\u{b3f}ଥ\u{b3f}ବ\u{b3e} ମ\u{b41}ହ\u{b01}") , keywords : & ["କ\u{b3e}ଓଗ\u{b3e}ର\u{b4d}ଲ" , "କ\u{b3e}ଓବଏ" , "କ\u{b3e}ଓବଏ ଟୋପ\u{b3f} ପ\u{b3f}ନ\u{b4d}ଧ\u{b3f}ଥ\u{b3f}ବ\u{b3e} ମ\u{b41}ହ\u{b01}" , "ଟୋପ\u{b3f}" , "ମ\u{b41}ହ\u{b01}"] , } , crate :: Annotation { lang : "pa" , tts : Some ("ਕਾਓਬ\u{a4c}ਏ ਹ\u{a48}ਟ ਚਿਹਰਾ") , keywords : & ["ਕਾਓਗਰਲ" , "ਕਾਓਬ\u{a41}ਆਏ" , "ਕਾਓਬ\u{a41}ਆਏ ਹ\u{a48}ਟ ਚਿਹਰਾ" , "ਕਾਓਬ\u{a4c}ਏ ਹ\u{a48}ਟ ਚਿਹਰਾ" , "ਟ\u{a4b}ਪੀ" , "ਹ\u{a48}ਟ ਚਿਹਰਾ"] , } , crate :: Annotation { lang : "pa_Arab" , tts : Some ("گوالے دے کلاے دی شکل") , keywords : & ["دی شکل" , "گوالا" , "گوالن" , "گوالے دے کلاے دی شکل" , "ہیٹ"] , } , crate :: Annotation { lang : "pcm" , tts : Some ("Kaúbọi Hát Fes") , keywords : & ["Fes" , "Hat" , "Kaúbọi" , "Kaúbọi Hát Fes" , "Kaúgẹl"] , } , crate :: Annotation { lang : "pl" , tts : Some ("głowa w kapeluszu kowbojskim") , keywords : & ["głowa w kapeluszu kowbojskim" , "kapelusz" , "kowboj" , "kowbojka"] , } , crate :: Annotation { lang : "ps" , tts : Some ("د چروایي خولۍ مخ") , keywords : & ["خولۍ" , "د چروایي خولۍ مخ" , "غوبنه" , "غوبه" , "مخ"] , } , crate :: Annotation { lang : "pt" , tts : Some ("rosto com chapéu de caubói") , keywords : & ["caubói" , "rosto" , "rosto com chapéu de caubói"] , } , crate :: Annotation { lang : "pt_PT" , tts : Some ("cara sorridente com chapéu de vaqueiro") , keywords : & ["cara" , "cara sorridente com chapéu de vaqueiro" , "caubói" , "chapéu" , "cobói" , "cowboy" , "vaqueira" , "vaqueiro"] , } , crate :: Annotation { lang : "qu" , tts : Some ("baquero uya chukuwan") , keywords : & ["baquera" , "baquero" , "baquero uya chukuwan" , "chuku" , "uya"] , } , crate :: Annotation { lang : "ro" , tts : Some ("față cu pălărie de cowboy") , keywords : & ["cowboy" , "cowgirl" , "față" , "față cu pălărie de cowboy" , "pălărie"] , } , crate :: Annotation { lang : "root" , tts : Some ("E10-1026") , keywords : & ["E10-1026"] , } , crate :: Annotation { lang : "ru" , tts : Some ("в ковбойской шляпе") , keywords : & ["в ковбойской шляпе" , "в шляпе" , "ковбой" , "лицо" , "шляпа"] , } , crate :: Annotation { lang : "rw" , tts : Some ("isura yambaye ingofero z’abakoboyi") , keywords : & ["ingofero" , "isura" , "isura yambaye ingofero z’abakoboyi" , "umushumba" , "umushumbakazi"] , } , crate :: Annotation { lang : "sd" , tts : Some ("ڪائوبوائي ٽوپي وارو چهرو") , keywords : & ["ٽوپي" , "چهرو" , "ڪائو بوائي" , "ڪائو گرل" , "ڪائوبوائي ٽوپي وارو چهرو"] , } , crate :: Annotation { lang : "si" , tts : Some ("ගොප තොප\u{dca}ප\u{dd2} ම\u{dd4}හ\u{dd4}ණ") , keywords : & ["ගොප තොප\u{dca}ප\u{dd2} ම\u{dd4}හ\u{dd4}ණ" , "ගොපල\u{dca}ල\u{dcf}" , "ගොපල\u{dd4} කෙල\u{dca}ල" , "ගොපල\u{dd4} තොප\u{dca}ප\u{dd2}ය" , "තොප\u{dca}ප\u{dd2}ය" , "ම\u{dd4}හ\u{dd4}ණ"] , } , crate :: Annotation { lang : "sk" , tts : Some ("tvár s kovbojským klobúkom") , keywords : & ["klobúk" , "kovboj" , "kovbojka" , "tvár" , "tvár s kovbojským klobúkom"] , } , crate :: Annotation { lang : "sl" , tts : Some ("obraz s kavbojskim klobukom") , keywords : & ["kavboj" , "klobuk" , "obraz s kavbojskim klobukom"] , } , crate :: Annotation { lang : "so" , tts : Some ("waji koofid leh") , keywords : & ["koofi" , "koofigabadh" , "koofiwiil" , "waji" , "waji koofid leh"] , } , crate :: Annotation { lang : "sq" , tts : Some ("fytyrë me kapele lopari") , keywords : & ["fytyrë" , "fytyrë me kapele lopari" , "kapele" , "lopar" , "lopare"] , } , crate :: Annotation { lang : "sr" , tts : Some ("лице каубоја") , keywords : & ["каубој" , "лице" , "лице каубоја" , "шешир"] , } , crate :: Annotation { lang : "sr_Cyrl_BA" , tts : Some ("↑↑↑") , keywords : & ["лице каубоја"] , } , crate :: Annotation { lang : "sr_Latn" , tts : Some ("lice kauboja") , keywords : & ["kauboj" , "lice" , "lice kauboja" , "šešir"] , } , crate :: Annotation { lang : "sr_Latn_BA" , tts : None , keywords : & ["lice kauboja"] , } , crate :: Annotation { lang : "sv" , tts : Some ("ansikte med cowboyhatt") , keywords : & ["ansikte" , "ansikte med cowboyhatt" , "cowboy" , "cowgirl" , "hatt"] , } , crate :: Annotation { lang : "sw" , tts : Some ("uso wenye kofia") , keywords : & ["kofia" , "uso" , "uso wenye kofia"] , } , crate :: Annotation { lang : "sw_KE" , tts : Some ("↑↑↑") , keywords : & ["↑↑↑"] , } , crate :: Annotation { lang : "ta" , tts : Some ("வேட\u{bcd}டைக\u{bcd}க\u{bbe}ரன\u{bcd}") , keywords : & ["தொப\u{bcd}பி" , "முகம\u{bcd}" , "வேட\u{bcd}டை" , "வேட\u{bcd}டைக\u{bcd}க\u{bbe}ரன\u{bcd}"] , } , crate :: Annotation { lang : "te" , tts : Some ("క\u{c4c}బ\u{c3e}య\u{c4d} ట\u{c4b}ప\u{c40} ముఖం") , keywords : & ["క\u{c4c}గర\u{c4d}ల\u{c4d}" , "క\u{c4c}బ\u{c3e}య\u{c4d}" , "ట\u{c4b}ప\u{c40}" , "ముఖం"] , } , crate :: Annotation { lang : "tg" , tts : Some ("рӯи дорои кулоҳи ковбой") , keywords : & ["ковбой" , "кулоҳ" , "рӯи дорои кулоҳи ковбой" , "рӯй" , "чӯпондухтар"] , } , crate :: Annotation { lang : "th" , tts : Some ("คาวบอยสวมหมวก") , keywords : & ["คน" , "คาวบอย" , "คาวบอยสวมหมวก" , "หน\u{e49}า" , "หมวก"] , } , crate :: Annotation { lang : "tk" , tts : Some ("kowboý papakly ýüz") , keywords : & ["kowboý papakly ýüz" , "padyman" , "padyman gyz" , "papak" , "ýüz"] , } , crate :: Annotation { lang : "to" , tts : Some ("mata moe tatā fakakaupoe") , keywords : & ["mata moe tatā fakakaupoe"] , } , crate :: Annotation { lang : "tr" , tts : Some ("kovboy şapkalı yüz") , keywords : & ["kadın kovboy" , "kovboy" , "kovboy şapkalı yüz" , "yüz" , "şapka"] , } , crate :: Annotation { lang : "ug" , tts : Some ("پادىچى قالپاقلىق چىراي") , keywords : & ["قالپاق" , "يۈز" , "پادىچى قالپاقلىق چىراي" , "پادىچى قىز" , "پادىچى يىگىت"] , } , crate :: Annotation { lang : "uk" , tts : Some ("обличчя у ковбойському капелюсі") , keywords : & ["капелюх" , "ковбой" , "обличчя" , "обличчя у ковбойському капелюсі" , "широко усміхнене обличчя у ковбойському капелюсі"] , } , crate :: Annotation { lang : "ur" , tts : Some ("کاؤ بوائے ہیٹ کے ساتھ چہرہ") , keywords : & ["چہرہ" , "کاؤ بوائے" , "کاؤ بوائے ہیٹ کے ساتھ چہرہ" , "ہیٹ"] , } , crate :: Annotation { lang : "uz" , tts : Some ("kovboyning boshi") , keywords : & ["kovboy" , "kovboyning boshi" , "shlyapa"] , } , crate :: Annotation { lang : "vi" , tts : Some ("mặt đội mũ cao bồi") , keywords : & ["cao bồi" , "mũ" , "mặt" , "mặt đội mũ cao bồi" , "nữ cao bồi"] , } , crate :: Annotation { lang : "wo" , tts : Some ("kanam gu sol mbaxane kaboy") , keywords : & ["kaboy" , "kanam" , "kanam gu sol mbaxane kaboy" , "mbaxane" , "sàmm-bu-jigéen"] , } , crate :: Annotation { lang : "xh" , tts : Some ("ubuso bomnqwazi we-cowboy") , keywords : & ["i-cowboy" , "i-cowgirl" , "ubuso" , "ubuso bomnqwazi we-cowboy" , "umnqwazi"] , } , crate :: Annotation { lang : "yo" , tts : Some ("Oju Fila Adaran") , keywords : & ["Oju Fila Adaran" , "adaran" , "fìlà" , "obìnrin ẹlẹ\u{301}ṣin" , "ojú"] , } , crate :: Annotation { lang : "yue" , tts : Some ("戴牛仔帽嘅臉") , keywords : & ["帽" , "戴牛仔帽嘅臉" , "牛仔" , "牛女" , "臉"] , } , crate :: Annotation { lang : "yue_Hans" , tts : Some ("戴牛仔帽嘅脸") , keywords : & ["帽" , "戴牛仔帽嘅脸" , "牛仔" , "牛女" , "脸"] , } , crate :: Annotation { lang : "zh" , tts : Some ("牛仔帽脸") , keywords : & ["帽" , "牛仔" , "牛仔帽脸" , "脸"] , } , crate :: Annotation { lang : "zh_Hant" , tts : Some ("牛仔") , keywords : & ["仔" , "牛" , "牛仔"] , } , crate :: Annotation { lang : "zh_Hant_HK" , tts : Some ("牛仔樣") , keywords : & ["牛仔" , "牛仔樣"] , } , crate :: Annotation { lang : "zu" , tts : Some ("umfana wezinkomo") , keywords : & ["intombazane yezinkomo" , "isigqoko" , "ubuso" , "umfana wezinkomo"] , }] , } ;
#[doc = "🥳"]
pub const PARTYING_FACE : crate :: Emoji = crate :: Emoji { glyph : "🥳" , codepoint : "1F973" , status : crate :: Status :: FullyQualified , introduction_version : 11f32 , name : "partying face" , group : "Smileys & Emotion" , subgroup : "face-hat" , is_variant : false , variants : & [] , annotations : & [crate :: Annotation { lang : "af" , tts : Some ("partytjie gesig") , keywords : & ["blaas" , "hoedjie" , "partytjie" , "partytjie gesig" , "vier"] , } , crate :: Annotation { lang : "am" , tts : Some ("የድግስ ፊት") , keywords : & ["ቀንድ" , "ክብረ በዓል" , "ኮፍያ" , "የድግስ ፊት" , "ድግስ"] , } , crate :: Annotation { lang : "ar" , tts : Some ("وجه محتفل") , keywords : & ["احتفال" , "بوق" , "حفلة" , "قبعة" , "وجه محتفل"] , } , crate :: Annotation { lang : "as" , tts : Some ("প\u{9be}ৰ\u{9cd}টী উদয\u{9be}পন কৰ\u{9be} চেহেৰ\u{9be}") , keywords : & ["উদয\u{9be}পন" , "ট\u{9c1}পী" , "প\u{9be}ৰ\u{9cd}টী" , "প\u{9be}ৰ\u{9cd}টী উদয\u{9be}পন কৰ\u{9be} চেহেৰ\u{9be}" , "পে\u{981}প\u{9be}"] , } , crate :: Annotation { lang : "az" , tts : Some ("parti edən üz") , keywords : & ["bayram etmək" , "buynuz" , "papaq" , "parti" , "parti edən üz"] , } , crate :: Annotation { lang : "be" , tts : Some ("святкуе") , keywords : & ["вечарына" , "дудка" , "капялюш" , "свята" , "святкуе"] , } , crate :: Annotation { lang : "bg" , tts : Some ("купонджийско лице") , keywords : & ["купон" , "купонджийско лице" , "надувалка" , "празненство" , "шапка"] , } , crate :: Annotation { lang : "bn" , tts : Some ("ট\u{9c1}পি পরে ব\u{9be}\u{981}শি ব\u{9be}জিয\u{9bc}ে প\u{9be}র\u{9cd}টি উদয\u{9be}পন কর\u{9be} ম\u{9c1}খ") , keywords : & ["উদয\u{9be}পন" , "ট\u{9c1}পি" , "ট\u{9c1}পি পরে ব\u{9be}\u{981}শি ব\u{9be}জিয\u{9bc}ে প\u{9be}র\u{9cd}টি উদয\u{9be}পন কর\u{9be} ম\u{9c1}খ" , "প\u{9be}র\u{9cd}টি" , "ব\u{9be}\u{981}শি"] , } , crate :: Annotation { lang : "bs" , tts : Some ("lice koje se zabavlja") , keywords : & ["lice koje se zabavlja" , "party" , "proslava" , "slavlje" , "zabava" , "šešir"] , } , crate :: Annotation { lang : "ca" , tts : Some ("cara festiva") , keywords : & ["barret" , "cara festiva" , "celebració" , "espanta-sogres" , "festa"] , } , crate :: Annotation { lang : "chr" , tts : Some ("ᎤᎧᏛ ᎤᎾᏓᏡᎨᏍᎬ") , keywords : & ["ᎠᎵᏍᏇᏔᏬ" , "ᎤᎧᏛ ᎤᎾᏓᏡᎨᏍᎬ" , "ᎤᎾᏓᏡᎨᏍᎬ" , "ᎤᎾᏕᏘᏰᏍᎬ" , "ᎤᏲᎾ"] , } , crate :: Annotation { lang : "cs" , tts : Some ("oslavující obličej") , keywords : & ["frkačka" , "oslava" , "oslavující obličej" , "párty" , "čepice" , "čepička"] , } , crate :: Annotation { lang : "cy" , tts : Some ("wyneb yn partïo") , keywords : & ["corn" , "dathliad" , "het" , "parti" , "wyneb yn partïo"] , } , crate :: Annotation { lang : "da" , tts : Some ("festansigt") , keywords : & ["fejring" , "fest" , "festansigt" , "hat" , "truthorn"] , } , crate :: Annotation { lang : "de" , tts : Some ("Partygesicht") , keywords : & ["Feiern" , "Party" , "Partygesicht"] , } , crate :: Annotation { lang : "el" , tts : Some ("προσωπάκι πάρτι") , keywords : & ["γιορτή" , "καπέλο" , "κόρνα" , "πάρτι" , "προσωπάκι πάρτι"] , } , crate :: Annotation { lang : "en" , tts : Some ("partying face") , keywords : & ["celebration" , "hat" , "horn" , "party" , "partying face"] , } , crate :: Annotation { lang : "en_AU" , tts : Some ("↑↑↑") , keywords : & ["↑↑↑"] , } , crate :: Annotation { lang : "en_CA" , tts : Some ("↑↑↑") , keywords : & ["↑↑↑"] , } , crate :: Annotation { lang : "en_GB" , tts : Some ("↑↑↑") , keywords : & ["↑↑↑"] , } , crate :: Annotation { lang : "en_IN" , tts : Some ("↑↑↑") , keywords : & ["↑↑↑"] , } , crate :: Annotation { lang : "es" , tts : Some ("cara de fiesta") , keywords : & ["capirote" , "cara de fiesta" , "celebración" , "fiesta" , "gorro" , "matasuegras"] , } , crate :: Annotation { lang : "es_419" , tts : Some ("↑↑↑") , keywords : & ["↑↑↑"] , } , crate :: Annotation { lang : "es_MX" , tts : Some ("cara de fiesta") , keywords : & ["cara de fiesta" , "celebración" , "fiesta" , "gorro" , "matasuegras"] , } , crate :: Annotation { lang : "es_US" , tts : Some ("cara de fiesta") , keywords : & ["cara de fiesta"] , } , crate :: Annotation { lang : "et" , tts : Some ("pidutsev nägu") , keywords : & ["müts" , "peovile" , "pidu" , "pidutsemine" , "pidutsev nägu"] , } , crate :: Annotation { lang : "eu" , tts : Some ("parrandan dabilen aurpegia") , keywords : & ["adar" , "festa" , "kapelu" , "ospakizun" , "parrandan dabilen aurpegia"] , } , crate :: Annotation { lang : "fa" , tts : Some ("جشن و سور") , keywords : & ["بوغ" , "جشن" , "جشن و سور" , "سور" , "مهمانی" , "کلاه"] , } , crate :: Annotation { lang : "fi" , tts : Some ("juhliva") , keywords : & ["hattu" , "juhla" , "juhlia" , "juhliva" , "pilli"] , } , crate :: Annotation { lang : "fil" , tts : Some ("nagdiriwang na mukha") , keywords : & ["nagdiriwang na mukha" , "pagdiriwang" , "salu-salo" , "sombrero" , "sungay"] , } , crate :: Annotation { lang : "fo" , tts : Some ("veitslu andlit") , keywords : & ["hattur" , "veitsla" , "veitslu andlit" , "veitslu horn"] , } , crate :: Annotation { lang : "fr" , tts : Some ("visage festif") , keywords : & ["chapeau" , "célébration" , "fête" , "sifflet" , "visage festif"] , } , crate :: Annotation { lang : "fr_CA" , tts : Some ("↑↑↑") , keywords : & ["chapeau" , "célébration" , "fête" , "sifflet" , "visage" , "visage festif"] , } , crate :: Annotation { lang : "ga" , tts : Some ("straoiseog chóisireachta") , keywords : & ["ceiliúradh" , "corn" , "cóisir" , "hata" , "straoiseog chóisireachta"] , } , crate :: Annotation { lang : "gd" , tts : Some ("aodann aig pàrtaidh") , keywords : & ["ad" , "aodann aig pàrtaidh" , "comharrachadh" , "cèilidh" , "dùdag" , "pàrtaidh"] , } , crate :: Annotation { lang : "gl" , tts : Some ("cara de festa") , keywords : & ["alegría" , "aniversario" , "cara de festa" , "celebración" , "feliz" , "festa"] , } , crate :: Annotation { lang : "gu" , tts : Some ("પાર\u{acd}ટી કરતો ચહ\u{ac7}રો") , keywords : & ["પાર\u{acd}ટી કરતો ચહ\u{ac7}રો"] , } , crate :: Annotation { lang : "he" , tts : Some ("חגיגה") , keywords : & ["חגיגה" , "יום הולדת" , "מסיבה" , "פרצוף חוגג"] , } , crate :: Annotation { lang : "hi" , tts : Some ("उत\u{94d}सवी च\u{947}हरा") , keywords : & ["उत\u{94d}सव" , "उत\u{94d}सवी च\u{947}हरा" , "जलसा" , "जश\u{94d}न" , "टोपी" , "पार\u{94d}टी"] , } , crate :: Annotation { lang : "hr" , tts : Some ("lice koje se zabavlja") , keywords : & ["lice koje se zabavlja" , "proslava" , "slavlje" , "zabava" , "šešir"] , } , crate :: Annotation { lang : "hu" , tts : Some ("bulizó arc") , keywords : & ["buli" , "bulizó arc" , "csákó" , "duda" , "ünneplés"] , } , crate :: Annotation { lang : "hy" , tts : Some ("խնջույք անող դեմք") , keywords : & ["գլխարկ" , "խնջույք" , "խնջույք անող դեմք" , "ուրախություն" , "տոն"] , } , crate :: Annotation { lang : "id" , tts : Some ("wajah pesta") , keywords : & ["perayaan" , "pesta" , "terompet" , "topi" , "wajah pesta"] , } , crate :: Annotation { lang : "is" , tts : Some ("partíandlit") , keywords : & ["fagna" , "flauta" , "hattur" , "partí" , "partíandlit"] , } , crate :: Annotation { lang : "it" , tts : Some ("faccina che festeggia") , keywords : & ["cappellino" , "faccina che festeggia" , "festa" , "festeggiamenti" , "party" , "trombetta"] , } , crate :: Annotation { lang : "ja" , tts : Some ("パーティーの顔") , keywords : & ["お祝い" , "パーティー" , "パーティーの顔" , "帽子" , "笛"] , } , crate :: Annotation { lang : "jv" , tts : Some ("rai pista") , keywords : & ["pista" , "rai pista" , "seneng-seneng" , "topi" , "trompet"] , } , crate :: Annotation { lang : "ka" , tts : Some ("მოზეიმე სახე") , keywords : & ["ზეიმი" , "მოზეიმე სახე" , "ფართი" , "ქუდი" , "წვეულება"] , } , crate :: Annotation { lang : "kk" , tts : Some ("тойлау") , keywords : & ["кеш" , "мүйіз" , "тойлау" , "шляпа"] , } , crate :: Annotation { lang : "km" , tts : Some ("ម\u{17bb}ខជប\u{17cb}លៀង") , keywords : & ["ការប\u{17d2}រារព\u{17d2}ធព\u{17b7}ធ\u{17b8}" , "ប\u{17c9}\u{17b8}" , "ព\u{17b7}ធ\u{17b8}ជប\u{17cb}លៀង" , "ម\u{17bb}ខជប\u{17cb}លៀង" , "ម\u{17bd}ក"] , } , crate :: Annotation { lang : "kn" , tts : Some ("ಪಾರ\u{ccd}ಟ\u{cbf} ಮಾಡುತ\u{ccd}ತ\u{cbf}ರುವ ಮುಖ") , keywords : & ["ಆಚರಣ\u{cc6}" , "ಪಾರ\u{ccd}ಟ\u{cbf}" , "ಪಾರ\u{ccd}ಟ\u{cbf} ಮಾಡುತ\u{ccd}ತ\u{cbf}ರುವ ಮುಖ" , "ಹಾರ\u{ccd}ನ\u{ccd}" , "ಹ\u{ccd}ಯಾಟ\u{ccd}"] , } , crate :: Annotation { lang : "ko" , tts : Some ("파티하는 얼굴") , keywords : & ["고깔모자" , "나팔" , "축하" , "파티" , "파티하는 얼굴"] , } , crate :: Annotation { lang : "kok" , tts : Some ("पार\u{94d}टी करपी च\u{947}रो") , keywords : & ["पार\u{94d}टी" , "पार\u{94d}टी करपी च\u{947}रो" , "स\u{941}वाळो" , "ह\u{945}ट" , "हॉर\u{94d}न"] , } , crate :: Annotation { lang : "ky" , tts : Some ("майрамдаган жүз") , keywords : & ["баш кийим" , "кече" , "майрамдаган жүз" , "майрамдоо" , "ышкырык"] , } , crate :: Annotation { lang : "lo" , tts : Some ("ໃບໜ\u{ec9}າໃນງານປາຕ\u{eb5}") , keywords : & ["ການສະໜອງ" , "ງານປາຕ\u{eb5}" , "ແກ" , "ໃບໜ\u{ec9}າໃນງານປາຕ\u{eb5}" , "ໝວກ"] , } , crate :: Annotation { lang : "lt" , tts : Some ("švenčiantis veidas") , keywords : & ["skrybėlė" , "šventimas" , "šventė" , "švenčiantis veidas" , "švilpynė"] , } , crate :: Annotation { lang : "lv" , tts : Some ("ballīšu seja") , keywords : & ["ballīte" , "ballīšu seja" , "cepure" , "svinības" , "taurīte"] , } , crate :: Annotation { lang : "mk" , tts : Some ("лице што се забавува") , keywords : & ["забава" , "капа" , "лице што се забавува" , "прослава"] , } , crate :: Annotation { lang : "ml" , tts : Some ("പ\u{d3e}ർട\u{d4d}ടി ചെയ\u{d4d}യ\u{d41}ന\u{d4d}ന മ\u{d41}ഖം") , keywords : & ["ആഘോഷം" , "തൊപ\u{d4d}പി" , "പ\u{d3e}ർട\u{d4d}ടി" , "പ\u{d3e}ർട\u{d4d}ടി ചെയ\u{d4d}യ\u{d41}ന\u{d4d}ന മ\u{d41}ഖം" , "ഹോൺ"] , } , crate :: Annotation { lang : "mn" , tts : Some ("үдэшлэг дээр баярлаж буй царай") , keywords : & ["баяр тэмдэглэх" , "малгай" , "үдэшлэг" , "үдэшлэг дээр баярлаж буй царай" , "үлээх"] , } , crate :: Annotation { lang : "mr" , tts : Some ("पार\u{94d}टीचा च\u{947}हरा") , keywords : & ["आन\u{902}दोत\u{94d}सव" , "पार\u{94d}टी" , "पार\u{94d}टीचा च\u{947}हरा" , "ह\u{945}ट" , "हॉर\u{94d}न"] , } , crate :: Annotation { lang : "ms" , tts : Some ("muka berparti") , keywords : & ["hon" , "muka berparti" , "parti" , "perayaan" , "topi"] , } , crate :: Annotation { lang : "my" , tts : Some ("ပါတ\u{102e}ပ\u{103d}\u{1032}တက\u{103a} မျက\u{103a}န\u{103e}ာ") , keywords : & ["ပါတ\u{102e}" , "ပါတ\u{102e}ပ\u{103d}\u{1032}တက\u{103a} မျက\u{103a}န\u{103e}ာ" , "အောင\u{103a}ပ\u{103d}\u{1032}ခ\u{1036}ခြင\u{103a}း" , "ဦးချ\u{102d}\u{102f}" , "ဦးထ\u{102f}ပ\u{103a}"] , } , crate :: Annotation { lang : "nb" , tts : Some ("partyfjes") , keywords : & ["feiring" , "fest" , "fløyte" , "hatt" , "party" , "partyfjes"] , } , crate :: Annotation { lang : "ne" , tts : Some ("पार\u{94d}टीमा रम\u{947}को अन\u{941}हार") , keywords : & ["उत\u{94d}सव मनाउन\u{947} कार\u{94d}य" , "टोप" , "पार\u{94d}टी" , "पार\u{94d}टीमा रम\u{947}को अन\u{941}हार" , "हर\u{94d}न"] , } , crate :: Annotation { lang : "nl" , tts : Some ("feestend gezicht") , keywords : & ["feest" , "feestend gezicht" , "hoedje" , "roltong" , "viering"] , } , crate :: Annotation { lang : "nn" , tts : Some ("partyfjes") , keywords : & ["feiring" , "fest" , "fløyte" , "hatt" , "party" , "partyfjes"] , } , crate :: Annotation { lang : "or" , tts : Some ("ପ\u{b3e}ର\u{b4d}ଟ\u{b3f} କର\u{b41}ଥ\u{b3f}ବ\u{b3e} ମ\u{b41}ହ\u{b01}") , keywords : & ["ଉତ\u{b4d}ସବ" , "ପ\u{b3e}ର\u{b4d}ଟ\u{b3f}" , "ପ\u{b3e}ର\u{b4d}ଟ\u{b3f} କର\u{b41}ଥ\u{b3f}ବ\u{b3e} ମ\u{b41}ହ\u{b01}" , "ହର\u{b4d}ନ" , "ହ\u{b3e}ଟ\u{b4d}\u{200c}"] , } , crate :: Annotation { lang : "pa" , tts : Some ("ਪਾਰਟੀ ਮਨਾਉ\u{a02}ਦਾ ਚਿਹਰਾ") , keywords : & ["ਜਸ\u{a3c}ਨ" , "ਪਾਰਟੀ" , "ਪਾਰਟੀ ਮਨਾਉ\u{a02}ਦਾ ਚਿਹਰਾ" , "ਹਾਰਨ" , "ਹ\u{a48}ਟ"] , } , crate :: Annotation { lang : "pcm" , tts : Some ("Fes Wé Dé Fọ Patí") , keywords : & ["Fes Wé Dé Fọ Patí" , "Họn" , "Kap" , "Patí" , "Sẹlíbréshọn"] , } , crate :: Annotation { lang : "pl" , tts : Some ("świętująca twarz") , keywords : & ["czapeczka" , "piszczałka" , "przyjęcie" , "trąbka" , "świętowanie" , "świętująca buźka" , "świętująca twarz"] , } , crate :: Annotation { lang : "ps" , tts : Some ("پارټي کوونکی مخ") , keywords : & ["خولۍ" , "نمانځنه" , "پارټي" , "پارټي کوونکی مخ" , "ښکر"] , } , crate :: Annotation { lang : "pt" , tts : Some ("rosto festivo") , keywords : & ["apito" , "chapéu" , "comemoração" , "festa" , "rosto festivo"] , } , crate :: Annotation { lang : "pt_PT" , tts : Some ("cara de festa") , keywords : & ["apito" , "cara de festa" , "chapéu" , "comemoração" , "festa"] , } , crate :: Annotation { lang : "qu" , tts : Some ("qʼuchukusqa uya") , keywords : & ["chuku" , "jarana" , "qʼuchukusqa uya" , "raymi" , "waqra"] , } , crate :: Annotation { lang : "ro" , tts : Some ("față de petrecere") , keywords : & ["coif" , "față de petrecere" , "petrecere" , "sărbătorire" , "trompetă"] , } , crate :: Annotation { lang : "root" , tts : Some ("E11-013") , keywords : & ["E11-013"] , } , crate :: Annotation { lang : "ru" , tts : Some ("на вечеринке") , keywords : & ["веселится" , "вечеринка" , "день рождения" , "на вечеринке" , "праздник"] , } , crate :: Annotation { lang : "sd" , tts : Some ("پارٽي ڪندڙ چهرو") , keywords : & ["جشن" , "هارن" , "ٽوپي" , "پارٽي" , "پارٽي ڪندڙ چهرو"] , } , crate :: Annotation { lang : "si" , tts : Some ("උත\u{dca}සව ම\u{dd4}හ\u{dd4}ණ") , keywords : & ["උත\u{dca}සව ම\u{dd4}හ\u{dd4}ණ" , "උත\u{dca}සවය" , "තොප\u{dd2}ය" , "නල\u{dcf}ව" , "සැමර\u{dd3}ම"] , } , crate :: Annotation { lang : "sk" , tts : Some ("oslavujúca tvár") , keywords : & ["oslava" , "oslavujúca tvár" , "párty" , "večierok" , "žúr"] , } , crate :: Annotation { lang : "sl" , tts : Some ("praznujoči obraz") , keywords : & ["hupa" , "klobuček" , "praznovanje" , "praznujoči obraz" , "zabava"] , } , crate :: Annotation { lang : "so" , tts : Some ("waji farxadeysan") , keywords : & ["dabaaldeg" , "gees" , "koofi" , "waji farxadeysan" , "xaflad"] , } , crate :: Annotation { lang : "sq" , tts : Some ("fytyrë festive") , keywords : & ["bori" , "festë" , "fytyrë festive" , "kapelë" , "mbrëmje festive"] , } , crate :: Annotation { lang : "sr" , tts : Some ("лице на журци") , keywords : & ["журка" , "лице на журци" , "прослава" , "шешир"] , } , crate :: Annotation { lang : "sr_Cyrl_BA" , tts : Some ("↑↑↑") , keywords : & ["лице на журци"] , } , crate :: Annotation { lang : "sr_Latn" , tts : Some ("lice na žurci") , keywords : & ["lice na žurci" , "proslava" , "šešir" , "žurka"] , } , crate :: Annotation { lang : "sr_Latn_BA" , tts : None , keywords : & ["lice na žurci"] , } , crate :: Annotation { lang : "sv" , tts : Some ("festande ansikte") , keywords : & ["fest" , "festande ansikte" , "hatt" , "kalas" , "party" , "tuta"] , } , crate :: Annotation { lang : "sw" , tts : Some ("uso wenye kofia ya karamu") , keywords : & ["filimbi" , "karamu" , "kofia" , "sherehe" , "uso wenye kofia ya karamu"] , } , crate :: Annotation { lang : "sw_KE" , tts : Some ("↑↑↑") , keywords : & ["↑↑↑"] , } , crate :: Annotation { lang : "ta" , tts : Some ("ப\u{bbe}ர\u{bcd}ட\u{bcd}டி முகம\u{bcd}") , keywords : & ["கொண\u{bcd}ட\u{bbe}ட\u{bcd}டம\u{bcd}" , "கொம\u{bcd}பு" , "தொப\u{bcd}பி" , "ப\u{bbe}ர\u{bcd}ட\u{bcd}டி" , "ப\u{bbe}ர\u{bcd}ட\u{bcd}டி முகம\u{bcd}"] , } , crate :: Annotation { lang : "te" , tts : Some ("ప\u{c3e}ర\u{c4d}ట\u{c40}ల\u{c4b} వ\u{c46}ల\u{c3f}గ\u{c3f}ప\u{c4b}తున\u{c4d}న ముఖం") , keywords : & ["ట\u{c4b}ప\u{c40}" , "ప\u{c3e}ర\u{c4d}ట\u{c40}" , "ప\u{c3e}ర\u{c4d}ట\u{c40}ల\u{c4b} వ\u{c46}ల\u{c3f}గ\u{c3f}ప\u{c4b}తున\u{c4d}న ముఖం" , "వ\u{c47}డుకలు" , "హ\u{c3e}ర\u{c4d}న\u{c4d}"] , } , crate :: Annotation { lang : "th" , tts : Some ("ไปปาร\u{e4c}ต\u{e35}\u{e49}") , keywords : & ["งานเล\u{e35}\u{e49}ยง" , "ฉลอง" , "ปาร\u{e4c}ต\u{e35}\u{e49}" , "หมวกปาร\u{e4c}ต\u{e35}\u{e49}" , "ไปปาร\u{e4c}ต\u{e35}\u{e49}"] , } , crate :: Annotation { lang : "tk" , tts : Some ("şagalaňly ýüz") , keywords : & ["baýramçylyk" , "telpek" , "tüýdük" , "şagalaň" , "şagalaňly ýüz"] , } , crate :: Annotation { lang : "to" , tts : Some ("mata paati") , keywords : & ["mata paati"] , } , crate :: Annotation { lang : "tr" , tts : Some ("partide eğlenen yüz") , keywords : & ["kutlama" , "parti" , "parti düdüğü" , "partide eğlenen yüz" , "şapka"] , } , crate :: Annotation { lang : "uk" , tts : Some ("святкове обличчя") , keywords : & ["вечірка" , "дудка" , "ковпак" , "святкове обличчя" , "святкування"] , } , crate :: Annotation { lang : "ur" , tts : Some ("پارٹی سے لطف اندوز ہوتا چہرہ") , keywords : & ["باجا" , "جشن" , "ٹوپی" , "پارٹی" , "پارٹی سے لطف اندوز ہوتا چہرہ"] , } , crate :: Annotation { lang : "uz" , tts : Some ("ziyofatda") , keywords : & ["bayram" , "kecha" , "nishonlash" , "o‘yin-kulgu" , "quvnash" , "tug‘ilgan kun" , "xursandchilik" , "ziyofatda"] , } , crate :: Annotation { lang : "vi" , tts : Some ("mặt tiệc tùng") , keywords : & ["buổi tiệc" , "lễ kỷ niệm" , "mũ" , "mặt tiệc tùng" , "sừng"] , } , crate :: Annotation { lang : "yue" , tts : Some ("開派對嘅臉") , keywords : & ["帽" , "慶祝" , "派對" , "號角" , "開派對嘅臉"] , } , crate :: Annotation { lang : "yue_Hans" , tts : Some ("开派对嘅脸") , keywords : & ["号角" , "帽" , "庆祝" , "开派对嘅脸" , "派对"] , } , crate :: Annotation { lang : "zh" , tts : Some ("聚会笑脸") , keywords : & ["号角" , "帽子" , "庆祝" , "聚会" , "聚会笑脸"] , } , crate :: Annotation { lang : "zh_Hant" , tts : Some ("慶祝的表情") , keywords : & ["帽子" , "慶祝" , "慶祝的表情" , "紙喇叭"] , } , crate :: Annotation { lang : "zh_Hant_HK" , tts : Some ("↑↑↑") , keywords : & ["↑↑↑"] , } , crate :: Annotation { lang : "zu" , tts : Some ("ubuso bobumnandi") , keywords : & ["celebration" , "hat" , "horn" , "party" , "ubuso bobumnandi"] , }] , } ;
#[doc = "🥸"]
pub const DISGUISED_FACE: crate::Emoji = crate::Emoji {
    glyph: "🥸",
    codepoint: "1F978",
    status: crate::Status::FullyQualified,
    introduction_version: 13f32,
    name: "disguised face",
    group: "Smileys & Emotion",
    subgroup: "face-hat",
    is_variant: false,
    variants: &[],
    annotations: &[
        crate::Annotation {
            lang: "af",
            tts: Some("vermomde gesig"),
            keywords: &[
                "bril",
                "gesig",
                "incognito",
                "neus",
                "vermom",
                "vermomde gesig",
            ],
        },
        crate::Annotation {
            lang: "am",
            tts: Some("አሳሳች ፊት"),
            keywords: &["አሳሳች ፊት"],
        },
        crate::Annotation {
            lang: "ar",
            tts: Some("وجع مقن\u{651}ع"),
            keywords: &["أنف", "قناع", "متخفي", "نظارات", "وجع مقن\u{651}ع", "وجه"],
        },
        crate::Annotation {
            lang: "as",
            tts: Some("ছদ\u{9cd}মবেশী ম\u{9c1}খ"),
            keywords: &[
                "গ\u{9c1}প\u{9cd}ত",
                "ছদ\u{9cd}মবেশ",
                "ছদ\u{9cd}মবেশী ম\u{9c1}খ",
                "ছশম\u{9be}",
                "ন\u{9be}ক",
                "ম\u{9c1}খ",
            ],
        },
        crate::Annotation {
            lang: "az",
            tts: Some("maskalanmış üz"),
            keywords: &[
                "burun",
                "eynəklər",
                "inkoqnito",
                "maskalama",
                "maskalanmış üz",
                "üz",
            ],
        },
        crate::Annotation {
            lang: "be",
            tts: Some("твар пад маскіроўкай"),
            keywords: &[
                "акуляры",
                "маскіроўка",
                "нос",
                "твар",
                "твар пад маскіроўкай",
                "інкогніта",
            ],
        },
        crate::Annotation {
            lang: "bg",
            tts: Some("маскирано лице"),
            keywords: &[
                "инкогнито",
                "лице",
                "маскирано лице",
                "маскировка",
                "очила",
                "фалшив нос",
            ],
        },
        crate::Annotation {
            lang: "bn",
            tts: Some("ছদ\u{9cd}মবেশী"),
            keywords: &[
                "চশম\u{9be}",
                "ছদ\u{9cd}মবেশ",
                "ছদ\u{9cd}মবেশী",
                "ন\u{9be}ক",
                "ম\u{9c1}খ",
            ],
        },
        crate::Annotation {
            lang: "bs",
            tts: Some("prerušeno lice"),
            keywords: &[
                "inkognito",
                "lice",
                "naočale",
                "nos",
                "prerušavanje",
                "prerušeno lice",
            ],
        },
        crate::Annotation {
            lang: "ca",
            tts: Some("cara disfressada"),
            keywords: &[
                "cara",
                "cara disfressada",
                "disfressa",
                "incògnit",
                "nas",
                "ulleres",
            ],
        },
        crate::Annotation {
            lang: "chr",
            tts: Some("ᎠᏣᏅᏙᏗ ᎤᎧᏛ"),
            keywords: &["ᎠᏣᏅᏙᏗ", "ᎤᎧᏛ", "ᎤᎵᏕᎵᏍᏗ", "ᎧᏴᏐᎵ", "ᏗᎦᏘᏅᏗ"],
        },
        crate::Annotation {
            lang: "cs",
            tts: Some("obličej v přestrojení"),
            keywords: &[
                "brýle",
                "incognito",
                "inkognito",
                "obličej v přestrojení",
                "přestrojení",
                "převlek",
                "smajlík",
                "tvář",
                "výraz",
            ],
        },
        crate::Annotation {
            lang: "cy",
            tts: Some("wyneb mewn cuddwisg"),
            keywords: &[
                "cuddwisg",
                "incognito",
                "sbectol",
                "trwyn",
                "wyneb",
                "wyneb mewn cuddwisg",
            ],
        },
        crate::Annotation {
            lang: "da",
            tts: Some("maske"),
            keywords: &["ansigt", "briller", "maske", "maskeret", "næse"],
        },
        crate::Annotation {
            lang: "de",
            tts: Some("verkleidet"),
            keywords: &[
                "Brille mit Nase",
                "Verkleidung",
                "inkognito",
                "verkleidet",
                "verkleidetes Gesicht",
            ],
        },
        crate::Annotation {
            lang: "de_CH",
            tts: Some("Gesicht mit Maske"),
            keywords: &[
                "Brille",
                "Gesicht",
                "Gesicht mit Maske",
                "Maske",
                "Nase",
                "incognito",
            ],
        },
        crate::Annotation {
            lang: "el",
            tts: Some("μεταμφιεσμένο πρόσωπο"),
            keywords: &[
                "γυαλιά",
                "ινκόγκνιτο",
                "μεταμφίεση",
                "μεταμφιεσμένο πρόσωπο",
                "μύτη",
                "πρόσωπο",
            ],
        },
        crate::Annotation {
            lang: "en",
            tts: Some("disguised face"),
            keywords: &[
                "disguise",
                "disguised face",
                "face",
                "glasses",
                "incognito",
                "nose",
            ],
        },
        crate::Annotation {
            lang: "en_AU",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "en_CA",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "en_GB",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "en_IN",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "es",
            tts: Some("cara disfrazada"),
            keywords: &[
                "cara disfrazada",
                "careta",
                "disfraz",
                "disimulo",
                "gafas",
                "incógnito",
                "nariz",
            ],
        },
        crate::Annotation {
            lang: "es_419",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "es_MX",
            tts: Some("cara disfrazada"),
            keywords: &[
                "anteojos",
                "cara",
                "cara disfrazada",
                "disfraz",
                "incognito",
                "nariz",
            ],
        },
        crate::Annotation {
            lang: "es_US",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "et",
            tts: Some("maskeeritud nägu"),
            keywords: &[
                "inkognito",
                "maskeerima",
                "maskeeritud nägu",
                "nina",
                "nägu",
                "prillid",
            ],
        },
        crate::Annotation {
            lang: "eu",
            tts: Some("mozorrotutako aurpegia"),
            keywords: &[
                "aurpegi",
                "betaurrekoak",
                "ezkutu",
                "mozorro",
                "mozorrotutako aurpegia",
                "sudur",
            ],
        },
        crate::Annotation {
            lang: "fa",
            tts: Some("تغییرقیافه داده"),
            keywords: &[
                "بینی",
                "تغییرقیافه",
                "تغییرقیافه داده",
                "عینک",
                "ناشناس",
                "چهره",
            ],
        },
        crate::Annotation {
            lang: "fi",
            tts: Some("naamioitunut"),
            keywords: &[
                "lasit",
                "naama",
                "naamio",
                "naamioitunut",
                "nenä",
                "tuntematon",
                "valepuku",
            ],
        },
        crate::Annotation {
            lang: "fil",
            tts: Some("nakatagong mukha"),
            keywords: &[
                "ilong",
                "incognito",
                "mukha",
                "nakatago",
                "nakatagong mukha",
                "salamin sa mata",
            ],
        },
        crate::Annotation {
            lang: "fo",
            tts: Some("grýlu andlit"),
            keywords: &["andlit", "brillur", "grýla", "grýlu andlit", "nøs"],
        },
        crate::Annotation {
            lang: "fr",
            tts: Some("visage déguisé"),
            keywords: &[
                "déguisement",
                "faux nez",
                "incognito",
                "lunettes",
                "postiche",
                "visage déguisé",
            ],
        },
        crate::Annotation {
            lang: "fr_CA",
            tts: Some("visage déguisé"),
            keywords: &[
                "déguisement",
                "faux nez",
                "incognito",
                "lunettes",
                "postiche",
                "visage déguisé",
            ],
        },
        crate::Annotation {
            lang: "ga",
            tts: Some("straiseog faoi bhréagriocht"),
            keywords: &[
                "aghaidh",
                "bréagriocht",
                "spéaclaí",
                "srón",
                "straiseog faoi bhréagriocht",
            ],
        },
        crate::Annotation {
            lang: "gd",
            tts: Some("aodann le riochd air"),
            keywords: &[
                "aodann",
                "aodann le riochd air",
                "incognito",
                "riochd",
                "speuclairean",
                "sròn",
            ],
        },
        crate::Annotation {
            lang: "gl",
            tts: Some("cara disfrazada"),
            keywords: &[
                "cara disfrazada",
                "disfrazarse",
                "enmascarar",
                "incógnito",
                "lentes",
                "nariz",
            ],
        },
        crate::Annotation {
            lang: "gu",
            tts: Some("બનાવટી દ\u{ac7}ખાવવાળો ચહ\u{ac7}રો"),
            keywords: &[
                "અજ\u{acd}ઞાત વ\u{ac7}શ\u{ac7}",
                "ચશ\u{acd}મા\u{a82}",
                "ચહ\u{ac7}રો",
                "નાક",
                "બનાવટી દ\u{ac7}ખાવ",
                "બનાવટી દ\u{ac7}ખાવવાળો ચહ\u{ac7}રો",
                "વ\u{ac7}ષધારી",
            ],
        },
        crate::Annotation {
            lang: "he",
            tts: Some("פרצוף עם תחפושת"),
            keywords: &[
                "הסוואה",
                "מסיכה",
                "משקפיים",
                "פרצוף",
                "פרצוף עם תחפושת",
                "שפם",
                "תחפושת",
            ],
        },
        crate::Annotation {
            lang: "hi",
            tts: Some("छिपाया ह\u{941}आ च\u{947}हरा"),
            keywords: &[
                "ग\u{941}प\u{94d}त",
                "चश\u{94d}मा",
                "च\u{947}हरा",
                "छद\u{94d}म व\u{947}ष",
                "छिपाया ह\u{941}आ च\u{947}हरा",
                "नाक",
            ],
        },
        crate::Annotation {
            lang: "hr",
            tts: Some("prerušeno lice"),
            keywords: &[
                "krinka",
                "lice",
                "maska",
                "naočale",
                "nos",
                "prerušeno lice",
            ],
        },
        crate::Annotation {
            lang: "hu",
            tts: Some("álcázott arc"),
            keywords: &[
                "arc",
                "inkognító",
                "orr",
                "szemüveg",
                "álca",
                "álcázott arc",
            ],
        },
        crate::Annotation {
            lang: "hy",
            tts: Some("դիմակով դեմք"),
            keywords: &[
                "ակնոց",
                "դիմակ",
                "դիմակով դեմք",
                "ինկոգնիտո",
                "քիթ",
                "քողարկված",
            ],
        },
        crate::Annotation {
            lang: "id",
            tts: Some("wajah menyamar"),
            keywords: &["hidung", "kacamata", "menyamar", "penyamaran", "wajah"],
        },
        crate::Annotation {
            lang: "is",
            tts: Some("dulargervi"),
            keywords: &["andlit", "dulargervi", "gleraugu", "nef", "óþekkjanlegt"],
        },
        crate::Annotation {
            lang: "it",
            tts: Some("faccina travestita"),
            keywords: &[
                "faccina",
                "faccina travestita",
                "incognito",
                "naso",
                "occhiali",
                "travestimento",
            ],
        },
        crate::Annotation {
            lang: "ja",
            tts: Some("変装した顔"),
            keywords: &["ひげ", "メガネ", "仮装", "変装", "変装した顔", "顔"],
        },
        crate::Annotation {
            lang: "jv",
            tts: Some("rai disamarno"),
            keywords: &[
                "irung",
                "kaca mripat",
                "nyamarake",
                "nyamarke",
                "rai",
                "rai disamarno",
            ],
        },
        crate::Annotation {
            lang: "ka",
            tts: Some("შენიღბული სახე"),
            keywords: &[
                "გადაცმა",
                "ინკოგნიტო",
                "სახე",
                "შენიღბვა",
                "შენიღბული სახე",
                "ცხვირა",
            ],
        },
        crate::Annotation {
            lang: "kk",
            tts: Some("бетін бүркеп алу"),
            keywords: &[
                "бет",
                "бетін бүркеп алу",
                "бүркеп алу",
                "инкогнито",
                "көзілдірік",
                "мұрын",
            ],
        },
        crate::Annotation {
            lang: "km",
            tts: Some("ម\u{17bb}ខប\u{17b7}ទបា\u{17c6}ង"),
            keywords: &[
                "ក\u{17d2}លែង",
                "ច\u{17d2}រម\u{17bb}ះ",
                "ម\u{17bb}ខ",
                "ម\u{17bb}ខប\u{17b7}ទបា\u{17c6}ង",
                "វ\u{17c9}ែនតា",
                "សម\u{17d2}ងាត\u{17cb}",
            ],
        },
        crate::Annotation {
            lang: "kn",
            tts: Some("ಮಾರುವೇಷ ಮುಖ"),
            keywords: &[
                "ಅಜ\u{ccd}ಞಾತ",
                "ಗ\u{ccd}ಲಾಸ\u{ccd}",
                "ಮಾರುವೇಷ",
                "ಮುಖ",
                "ಮ\u{cc2}ಗು",
            ],
        },
        crate::Annotation {
            lang: "ko",
            tts: Some("변장한 얼굴"),
            keywords: &["가면", "변장", "변장한 얼굴", "안경", "얼굴", "코"],
        },
        crate::Annotation {
            lang: "kok",
            tts: Some("व\u{947}शा\u{902}तर क\u{947}ल\u{94d}लो च\u{947}रो"),
            keywords: &[
                "ग\u{941}पीत",
                "ग\u{94d}लास",
                "च\u{947}रो",
                "नाक",
                "व\u{947}शा\u{902}तर",
                "व\u{947}शा\u{902}तर क\u{947}ल\u{94d}लो च\u{947}रो",
            ],
        },
        crate::Annotation {
            lang: "ky",
            tts: Some("маска тагынып алган жүз"),
            keywords: &["маска тагынып алган жүз"],
        },
        crate::Annotation {
            lang: "lo",
            tts: Some("ໜ\u{ec9}າປອມໂຕ"),
            keywords: &[
                "ດ\u{eb1}ງ",
                "ບ\u{ecd}\u{ec8}ລະບ\u{eb8}ຕ\u{ebb}ວຕ\u{ebb}ນ",
                "ປອມຕ\u{ebb}ວ",
                "ແວ\u{ec8}ນຕາ",
                "ໜ\u{ec9}າ",
                "ໜ\u{ec9}າປອມໂຕ",
            ],
        },
        crate::Annotation {
            lang: "lt",
            tts: Some("paslėptas veidas"),
            keywords: &[
                "akiniai",
                "inkognito",
                "nosis",
                "pasislėpęs",
                "paslėptas veidas",
                "veidas",
            ],
        },
        crate::Annotation {
            lang: "lv",
            tts: Some("paslēpta seja"),
            keywords: &[
                "brilles",
                "deguns",
                "inkognito",
                "maska",
                "paslēpta seja",
                "seja",
            ],
        },
        crate::Annotation {
            lang: "mk",
            tts: Some("лице со маска"),
            keywords: &[
                "инкогнито",
                "лице",
                "лице со маска",
                "маска",
                "нос",
                "очила",
            ],
        },
        crate::Annotation {
            lang: "ml",
            tts: Some("തെറ\u{d4d}റിദ\u{d4d}ധരിപ\u{d4d}പിക\u{d4d}ക\u{d41}ന\u{d4d}ന മ\u{d41}ഖം"),
            keywords: &[
                "അജ\u{d4d}ഞ\u{d3e}തമ\u{d3e}യ",
                "ഗ\u{d4d}ല\u{d3e}സ\u{d4d}സ\u{d41}കൾ",
                "തെറ\u{d4d}റിദ\u{d4d}ധരിപ\u{d4d}പിക\u{d4d}ക\u{d41}ന\u{d4d}ന",
                "മ\u{d41}ഖം",
                "മ\u{d42}ക\u{d4d}ക\u{d4d}",
            ],
        },
        crate::Annotation {
            lang: "mn",
            tts: Some("өнгөлөн далдалсан царай"),
            keywords: &[
                "зүсээ хувиргасан",
                "зүсээ хувиргах",
                "хамар",
                "царай",
                "шилтэй",
                "үл танигдах",
                "өнгөлөн далдалсан царай",
            ],
        },
        crate::Annotation {
            lang: "mr",
            tts: Some("व\u{947}षा\u{902}तर क\u{947}ल\u{947}ला च\u{947}हरा"),
            keywords: &[
                "ग\u{941}प\u{94d}त",
                "चष\u{94d}मा घातल\u{947}ला",
                "च\u{947}हरा",
                "नाक",
                "व\u{947}षा\u{902}तर",
                "व\u{947}षा\u{902}तर क\u{947}ल\u{947}ला च\u{947}हरा",
            ],
        },
        crate::Annotation {
            lang: "ms",
            tts: Some("muka samaran"),
            keywords: &[
                "cermin mata",
                "hidung",
                "menyamar",
                "muka",
                "muka samaran",
                "penyamaran",
            ],
        },
        crate::Annotation {
            lang: "my",
            tts: Some("ဟန\u{103a}ဆောင\u{103a}မျက\u{103a}န\u{103e}ာ"),
            keywords: &[
                "န\u{103e}ာခေါင\u{103a}း",
                "မျက\u{103a}န\u{103e}ာ",
                "မျက\u{103a}မ\u{103e}န\u{103a}",
                "ရ\u{102f}ပ\u{103a}ဖျက\u{103a}ခြင\u{103a}း",
                "ရ\u{102f}ပ\u{103a}ဖျက\u{103a}ထားသော မျက\u{103a}န\u{103e}ာ",
                "ဟန\u{103a}ဆောင\u{103a}မျက\u{103a}န\u{103e}ာ",
            ],
        },
        crate::Annotation {
            lang: "nb",
            tts: Some("fjes med forkledning"),
            keywords: &[
                "briller",
                "fjes",
                "fjes med forkledning",
                "forkledning",
                "inkognito",
                "nese",
            ],
        },
        crate::Annotation {
            lang: "ne",
            tts: Some("भ\u{947}ष बद\u{94d}ल\u{947}को अन\u{941}हार"),
            keywords: &[
                "अन\u{941}हार",
                "गोप\u{94d}य",
                "चस\u{94d}मा",
                "नाक",
                "भ\u{947}ष बद\u{94d}ल\u{947}को",
                "भ\u{947}ष बद\u{94d}ल\u{947}को अन\u{941}हार",
            ],
        },
        crate::Annotation {
            lang: "nl",
            tts: Some("vermomd gezicht"),
            keywords: &[
                "bril",
                "gezicht",
                "incognito",
                "neus",
                "vermomd gezicht",
                "vermomming",
            ],
        },
        crate::Annotation {
            lang: "nn",
            tts: Some("fjes med forkleding"),
            keywords: &[
                "briller",
                "fjes",
                "fjes med forkleding",
                "forkleding",
                "inkognito",
                "nase",
            ],
        },
        crate::Annotation {
            lang: "or",
            tts: Some("ଛଦ\u{b4d}ମବେଶୀ ମ\u{b41}ହ\u{b01}"),
            keywords: &[
                "ଅପର\u{b3f}ଚ\u{b3f}ତ",
                "ଚଷମ\u{b3e}",
                "ଛଦ\u{b4d}ମବେଶ",
                "ଛଦ\u{b4d}ମବେଶୀ ମ\u{b41}ହ\u{b01}",
                "ନ\u{b3e}କ",
                "ମ\u{b41}ହ\u{b01}",
            ],
        },
        crate::Annotation {
            lang: "pa",
            tts: Some("ਢ\u{a4c}\u{a02}ਗੀ ਚਿਹਰਾ"),
            keywords: &[
                "ਇਨਕ\u{a4b}ਗਨਿਟ\u{a4b}",
                "ਗਲਾਸ",
                "ਚਿਹਰਾ",
                "ਢ\u{a4c}\u{a02}ਗ",
                "ਢ\u{a4c}\u{a02}ਗੀ ਚਿਹਰਾ",
                "ਨ\u{a71}ਕ",
            ],
        },
        crate::Annotation {
            lang: "pcm",
            tts: Some("Fes Wé Dẹm De Haid"),
            keywords: &[
                "Chénj Haú Yu Bi",
                "Fes",
                "Fes Wé Dẹm Chénj Haú I Bì",
                "Fes Wé Dẹm De Haid",
                "Glásis",
                "Nóz",
                "To Mék Pípul Nọ\u{301} Nó Hú Yu Bì",
            ],
        },
        crate::Annotation {
            lang: "pl",
            tts: Some("buźka w przebraniu"),
            keywords: &[
                "anonimowy",
                "buźka w przebraniu",
                "incognito",
                "nos",
                "okulary",
                "przebranie",
                "twarz",
                "wąsy",
            ],
        },
        crate::Annotation {
            lang: "ps",
            tts: Some("اصل ماهيت بدلوونکی مخ"),
            keywords: &[
                "اصل ماهيت بدلوونکی مخ",
                "عېنکې",
                "ماهيت بدلول",
                "مخ",
                "نه پېژندونکی",
                "پوزه",
            ],
        },
        crate::Annotation {
            lang: "pt",
            tts: Some("rosto disfarçado"),
            keywords: &[
                "disfarce",
                "incógnito",
                "nariz",
                "rosto",
                "rosto disfarçado",
                "óculos",
            ],
        },
        crate::Annotation {
            lang: "pt_PT",
            tts: Some("cara disfarçada"),
            keywords: &[
                "cara",
                "cara disfarçada",
                "disfarce",
                "incógnito",
                "nariz",
                "óculos",
            ],
        },
        crate::Annotation {
            lang: "qu",
            tts: Some("pakasqa uya"),
            keywords: &["lentekuna", "mana riqsiqisqa", "pakasqa", "sinqa", "uya"],
        },
        crate::Annotation {
            lang: "ro",
            tts: Some("față deghizată"),
            keywords: &[
                "deghizare",
                "față",
                "față deghizată",
                "incognito",
                "nas",
                "ochelari",
            ],
        },
        crate::Annotation {
            lang: "root",
            tts: Some("E13-003"),
            keywords: &["E13-003"],
        },
        crate::Annotation {
            lang: "ru",
            tts: Some("маскировка"),
            keywords: &["инкогнито", "лицо", "маскировка", "нос", "очки"],
        },
        crate::Annotation {
            lang: "sd",
            tts: Some("لڪيل چهرو"),
            keywords: &["انڪوگنيٽو", "لڪيل چهرو", "نڪ", "ڀيس بدلايو", "چشما", "چهرو"],
        },
        crate::Annotation {
            lang: "si",
            tts: Some("වෙස\u{dca}වල\u{dcf}ගත\u{dca} ම\u{dd4}හ\u{dd4}ණ"),
            keywords: &[
                "කණ\u{dca}න\u{dcf}ඩ\u{dd2}",
                "න\u{dcf}සය",
                "නොපැහැද\u{dd2}ල\u{dd2}",
                "ම\u{dd4}හ\u{dd4}ණ",
                "වෙස\u{dca}වල\u{dcf}ගත\u{dca} ම\u{dd4}හ\u{dd4}ණ",
                "වෙස\u{dca}වළ\u{dcf}ගෙන",
            ],
        },
        crate::Annotation {
            lang: "sk",
            tts: Some("maskovaná tvár"),
            keywords: &[
                "inkognito",
                "maska",
                "maskovaná tvár",
                "nos",
                "okuliare",
                "prestrojenie",
                "tvár",
            ],
        },
        crate::Annotation {
            lang: "sl",
            tts: Some("maska"),
            keywords: &["inkognito", "maska", "nos", "obraz", "očala", "preobleka"],
        },
        crate::Annotation {
            lang: "so",
            tts: Some("waji badalan"),
            keywords: &["ookiyaale", "waji badalan"],
        },
        crate::Annotation {
            lang: "sq",
            tts: Some("fytyrë e maskuar"),
            keywords: &[
                "fshehtas",
                "fytyrë",
                "fytyrë e maskuar",
                "hundë",
                "maskim",
                "syze",
            ],
        },
        crate::Annotation {
            lang: "sr",
            tts: Some("прерушено лице"),
            keywords: &["маска", "наочари", "нос", "прерушено лице"],
        },
        crate::Annotation {
            lang: "sr_Cyrl_BA",
            tts: Some("↑↑↑"),
            keywords: &["прерушено лице"],
        },
        crate::Annotation {
            lang: "sr_Latn",
            tts: Some("prerušeno lice"),
            keywords: &["maska", "naočari", "nos", "prerušeno lice"],
        },
        crate::Annotation {
            lang: "sr_Latn_BA",
            tts: None,
            keywords: &["prerušeno lice"],
        },
        crate::Annotation {
            lang: "sv",
            tts: Some("maskerat ansikte"),
            keywords: &[
                "anonym",
                "ansikte",
                "glasögon",
                "mask",
                "maskerat ansikte",
                "näsa",
            ],
        },
        crate::Annotation {
            lang: "sw",
            tts: Some("uso uliogeuzwa ili kuficha"),
            keywords: &[
                "kujificha",
                "kujifunika",
                "miwani",
                "pua",
                "uso",
                "uso uliogeuzwa ili kuficha",
            ],
        },
        crate::Annotation {
            lang: "sw_KE",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "ta",
            tts: Some("முகமூடி முகம\u{bcd}"),
            keywords: &[
                "கண\u{bcd}ண\u{bbe}டிகள\u{bcd}",
                "ம\u{bbe}றுவேடம\u{bcd}",
                "முகமூடி முகம\u{bcd}",
                "முகம\u{bcd}",
                "மூக\u{bcd}கு",
            ],
        },
        crate::Annotation {
            lang: "te",
            tts: Some("మ\u{c3e}రువ\u{c47}షంల\u{c4b} ఉన\u{c4d}న ముఖం"),
            keywords: &[
                "కళ\u{c4d}లద\u{c4d}ద\u{c3e}లు",
                "గుర\u{c4d}తుపట\u{c4d}టల\u{c47}న\u{c3f}",
                "మ\u{c3e}రువ\u{c47}షం",
                "మ\u{c3e}రువ\u{c47}షంల\u{c4b} ఉన\u{c4d}న ముఖం",
                "ముక\u{c4d}కున\u{c3f} కల\u{c3f}గ\u{c3f} ఉన\u{c4d}న ముఖం",
                "ముఖం",
            ],
        },
        crate::Annotation {
            lang: "th",
            tts: Some("ปลอมต\u{e31}ว"),
            keywords: &[
                "จม\u{e39}ก",
                "ปลอมต\u{e31}ว",
                "หน\u{e49}า",
                "แว\u{e48}นตา",
                "ไม\u{e48}เป\u{e34}ดเผยต\u{e31}ว",
            ],
        },
        crate::Annotation {
            lang: "tk",
            tts: Some("ýüzi gizlenen"),
            keywords: &[
                "burun",
                "gizlemek",
                "näbelli",
                "äýnek",
                "ýüz",
                "ýüzi gizlenen",
            ],
        },
        crate::Annotation {
            lang: "to",
            tts: Some("mata fakapuli"),
            keywords: &["mata fakapuli"],
        },
        crate::Annotation {
            lang: "tr",
            tts: Some("gizlenmiş yüz"),
            keywords: &[
                "burun",
                "gizlenmiş yüz",
                "gizli",
                "gözlük",
                "kimliğini gizleyen",
                "maskeli",
                "yüz",
            ],
        },
        crate::Annotation {
            lang: "uk",
            tts: Some("замасковане обличчя"),
            keywords: &[
                "замасковане обличчя",
                "камуфляж",
                "маска",
                "ніс",
                "обличчя",
                "окуляри",
                "інкогніто",
            ],
        },
        crate::Annotation {
            lang: "ur",
            tts: Some("بہروپ چہرہ"),
            keywords: &["بہروپ", "خفیہ", "ناک", "چشمہ", "چہرہ"],
        },
        crate::Annotation {
            lang: "uz",
            tts: Some("niqoblangan yuz"),
            keywords: &[
                "burun",
                "koʻzoynak",
                "niqoblangan yuz",
                "niqoblash",
                "yashirin",
                "yashirincha",
                "yuz",
            ],
        },
        crate::Annotation {
            lang: "vi",
            tts: Some("mặt trá hình"),
            keywords: &[
                "kính",
                "mũi",
                "mặt",
                "mặt trá hình",
                "ngụy trang",
                "ẩn danh",
            ],
        },
        crate::Annotation {
            lang: "yue",
            tts: Some("面具"),
            keywords: &["假扮", "匿名", "眼鏡", "面", "面具", "鼻"],
        },
        crate::Annotation {
            lang: "yue_Hans",
            tts: Some("面具"),
            keywords: &["假扮", "匿名", "眼镜", "面", "面具", "鼻"],
        },
        crate::Annotation {
            lang: "zh",
            tts: Some("伪装的脸"),
            keywords: &["伪装", "伪装的脸", "眼镜", "脸", "隐瞒身份", "鼻子"],
        },
        crate::Annotation {
            lang: "zh_Hant",
            tts: Some("假扮的臉"),
            keywords: &["假扮", "假扮的臉", "假鼻子", "眼鏡", "鬍子"],
        },
        crate::Annotation {
            lang: "zh_Hant_HK",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "zu",
            tts: Some("ubuso obuzifihlile"),
            keywords: &[
                "ikhala",
                "izibuko",
                "okunye",
                "ubuso",
                "ubuso obuzifihlile",
                "zifihle",
            ],
        },
    ],
};
