#[doc = "🦰"]
pub const RED_HAIR: crate::Emoji = crate::Emoji {
    glyph: "🦰",
    codepoint: "1F9B0",
    status: crate::Status::Component,
    introduction_version: 11f32,
    name: "red hair",
    group: "Component",
    subgroup: "hair-style",
    is_variant: false,
    variants: &[],
    annotations: &[
        crate::Annotation {
            lang: "af",
            tts: Some("rooi hare"),
            keywords: &["gemmer", "rooi hare", "rooikop"],
        },
        crate::Annotation {
            lang: "am",
            tts: Some("ቀይ ጸጉር"),
            keywords: &["ቀይ ጸጉር", "ጂንጀር"],
        },
        crate::Annotation {
            lang: "ar",
            tts: Some("شعر أحمر"),
            keywords: &["أصهب", "رأس حمراء", "شعر أحمر"],
        },
        crate::Annotation {
            lang: "as",
            tts: Some("ৰঙ\u{9be} চ\u{9c1}লি"),
            keywords: &[
                "ৰঙচ\u{9c1}ৱ\u{9be} চ\u{9c1}লি",
                "ৰঙ\u{9be} চ\u{9c1}লি",
                "ৰঙ\u{9be} চ\u{9c1}লিৰ লোক",
            ],
        },
        crate::Annotation {
            lang: "az",
            tts: Some("qırmızı saç"),
            keywords: &["kürən", "qırmızı saç"],
        },
        crate::Annotation {
            lang: "be",
            tts: Some("рыжыя валасы"),
            keywords: &["руды", "рыжыя валасы"],
        },
        crate::Annotation {
            lang: "bg",
            tts: Some("рижа коса"),
            keywords: &["риж човек", "рижа коса", "червенокос човек"],
        },
        crate::Annotation {
            lang: "bn",
            tts: Some("ল\u{9be}ল চ\u{9c1}ল"),
            keywords: &[
                "ল\u{9be}ল চ\u{9c1}ত\u{9cd}তয\u{9bc}\u{9be}ল\u{9be}",
                "ল\u{9be}ল চ\u{9c1}ল",
                "ল\u{9be}লচে হল\u{9c1}দ",
            ],
        },
        crate::Annotation {
            lang: "br",
            tts: Some("blev ruz"),
            keywords: &["blev", "blev ruz"],
        },
        crate::Annotation {
            lang: "bs",
            tts: Some("crvena kosa"),
            keywords: &["crvena kosa", "crvenokos", "crvenokosa", "riđa", "riđast"],
        },
        crate::Annotation {
            lang: "ca",
            tts: Some("cabells vermells"),
            keywords: &["cabells vermells", "pèl-roig", "pèl-roja"],
        },
        crate::Annotation {
            lang: "chr",
            tts: Some("ᎩᎦᎨ ᎤᏍᏘᎦ"),
            keywords: &["ᎩᎦᎨ ᎠᏍᎪᎵ", "ᎩᎦᎨ ᎤᏍᏘᎦ", "ᎩᎦᎨ ᎤᏍᏘᏰᏅᎢ"],
        },
        crate::Annotation {
            lang: "cs",
            tts: Some("zrzavé vlasy"),
            keywords: &[
                "ryšavé vlasy, rusé vlasy, rudé vlasy, zrzek, zrzka",
                "zrzavé vlasy",
            ],
        },
        crate::Annotation {
            lang: "cy",
            tts: Some("gwallt coch"),
            keywords: &["gwallt coch", "melyngoch", "pen coch"],
        },
        crate::Annotation {
            lang: "da",
            tts: Some("rødt hår"),
            keywords: &["rødhåret", "rødt hår"],
        },
        crate::Annotation {
            lang: "de",
            tts: Some("rotes Haar"),
            keywords: &["Rotschopf", "rote Haare", "rotes Haar", "rothaarig"],
        },
        crate::Annotation {
            lang: "el",
            tts: Some("κόκκινα μαλλιά"),
            keywords: &["κοκκινομάλλης", "κόκκινα μαλλιά", "πυρρόξανθος"],
        },
        crate::Annotation {
            lang: "en",
            tts: Some("red hair"),
            keywords: &["ginger", "red hair", "redhead"],
        },
        crate::Annotation {
            lang: "en_AU",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "en_CA",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "en_GB",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "en_IN",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "es",
            tts: Some("pelo pelirrojo"),
            keywords: &["pelirrojo", "pelo", "rojizo", "rojo"],
        },
        crate::Annotation {
            lang: "es_419",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "es_MX",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "es_US",
            tts: Some("pelirrojo"),
            keywords: &["pelirrojo"],
        },
        crate::Annotation {
            lang: "et",
            tts: Some("punased juuksed"),
            keywords: &["punajuus", "punapea", "punased juuksed"],
        },
        crate::Annotation {
            lang: "eu",
            tts: Some("ilegorri"),
            keywords: &["ilegorri", "kaskagorri"],
        },
        crate::Annotation {
            lang: "fa",
            tts: Some("موقرمز"),
            keywords: &[
                "سرخ\u{200c}مو",
                "سرخ\u{200c}موی",
                "موسرخ",
                "موقرمز",
                "موی قرمز",
            ],
        },
        crate::Annotation {
            lang: "fi",
            tts: Some("punatukkainen"),
            keywords: &["punainen tukka", "punapää", "punatukkainen"],
        },
        crate::Annotation {
            lang: "fil",
            tts: Some("pulang buhok"),
            keywords: &["ginger", "pulang buhok", "pulang ulo"],
        },
        crate::Annotation {
            lang: "fo",
            tts: Some("reytt hár"),
            keywords: &["hár", "reytt hár", "reyðhærdur"],
        },
        crate::Annotation {
            lang: "fr",
            tts: Some("cheveux roux"),
            keywords: &["cheveux roux", "rouquin", "rouquine"],
        },
        crate::Annotation {
            lang: "fr_CA",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "ga",
            tts: Some("gruaig rua"),
            keywords: &["duine le gruaig rua", "gruaig rua", "rua"],
        },
        crate::Annotation {
            lang: "gd",
            tts: Some("falt ruadh"),
            keywords: &["falt", "ruadh"],
        },
        crate::Annotation {
            lang: "gl",
            tts: Some("pelo roxo"),
            keywords: &["cabelo", "pelo roxo", "roibo", "roxo", "rubio"],
        },
        crate::Annotation {
            lang: "gu",
            tts: Some("લાલ વાળ"),
            keywords: &["આછો ક\u{ac7}સરી", "લાલ વાળ", "લાલમાથ\u{ac1}\u{a82}"],
        },
        crate::Annotation {
            lang: "he",
            tts: Some("שיער ג׳ינג׳י"),
            keywords: &["אדמוני", "ג׳ינג׳י", "שיער ג׳ינג׳י"],
        },
        crate::Annotation {
            lang: "hi",
            tts: Some("लाल बाल"),
            keywords: &["लाल बाल", "लाल बालो\u{902} वाला"],
        },
        crate::Annotation {
            lang: "hr",
            tts: Some("crvena kosa"),
            keywords: &["crvena kosa", "crvenokos", "riđokos"],
        },
        crate::Annotation {
            lang: "hu",
            tts: Some("vörös haj"),
            keywords: &["vörös haj", "vöröshajú"],
        },
        crate::Annotation {
            lang: "hy",
            tts: Some("շիկահեր"),
            keywords: &["հրագույն", "շիկահեր", "շիկամազ"],
        },
        crate::Annotation {
            lang: "ia",
            tts: Some("capillos rosse"),
            keywords: &[
                "capillos rosse",
                "rossa",
                "rossastre",
                "rubee",
                "rubie",
                "rubre",
            ],
        },
        crate::Annotation {
            lang: "id",
            tts: Some("rambut merah"),
            keywords: &["cokelat kemerahan", "rambut merah"],
        },
        crate::Annotation {
            lang: "is",
            tts: Some("rautt hár"),
            keywords: &["rautt hár", "rauðleitt hár"],
        },
        crate::Annotation {
            lang: "it",
            tts: Some("capelli rossi"),
            keywords: &["capelli rossi", "pel di carota", "rosso"],
        },
        crate::Annotation {
            lang: "ja",
            tts: Some("赤毛"),
            keywords: &["赤毛", "赤毛の人", "赤茶"],
        },
        crate::Annotation {
            lang: "jv",
            tts: Some("rambut abang"),
            keywords: &["jae", "rambut abang", "rambute abang"],
        },
        crate::Annotation {
            lang: "ka",
            tts: Some("წითელი თმა"),
            keywords: &["ჟღალი თმა", "წითელი თმა", "წითური"],
        },
        crate::Annotation {
            lang: "kab",
            tts: Some("acekkuḥ azeggaɣ"),
            keywords: &["acekkuḥ azeggaɣ"],
        },
        crate::Annotation {
            lang: "kk",
            tts: Some("жирен шаш"),
            keywords: &["жирен", "жирен шаш", "қызыл бас"],
        },
        crate::Annotation {
            lang: "km",
            tts: Some("សក\u{17cb}ក\u{17d2}រហម"),
            keywords: &[
                "ខ\u{17d2}ញ\u{17b8}",
                "មន\u{17bb}ស\u{17d2}សសក\u{17cb}ក\u{17d2}រហម",
                "សក\u{17cb}ក\u{17d2}រហម",
            ],
        },
        crate::Annotation {
            lang: "kn",
            tts: Some("ಕ\u{cc6}ಂಪು ಕ\u{cc2}ದಲು"),
            keywords: &[
                "ಕ\u{cc6}ಂಪು ಕ\u{cc2}ದಲು",
                "ಕ\u{cc6}ಂಪು ತಲ\u{cc6}",
                "ಶುಂಠ\u{cbf}",
            ],
        },
        crate::Annotation {
            lang: "ko",
            tts: Some("빨간 머리"),
            keywords: &["빨간 머리", "적갈색"],
        },
        crate::Annotation {
            lang: "kok",
            tts: Some("ता\u{902}बश\u{947}\u{902} क\u{947}\u{902}स"),
            keywords: &[
                "ता\u{902}बश\u{947}\u{902}",
                "ता\u{902}बश\u{947}\u{902} क\u{947}\u{902}स",
                "ता\u{902}बश\u{947}\u{902} क\u{947}\u{902}स आशिल\u{94d}ल\u{947}",
            ],
        },
        crate::Annotation {
            lang: "ky",
            tts: Some("кызыл чач"),
            keywords: &["кызгылтым сары", "кызгылтым сары чачтуу", "кызыл чач"],
        },
        crate::Annotation {
            lang: "lo",
            tts: Some("ຜ\u{ebb}ມແດງ"),
            keywords: &["ຜ\u{ebb}ມແດງ", "ສ\u{eb5}ຂ\u{eb5}ງດອງ", "ຫ\u{ebb}ວແດງ"],
        },
        crate::Annotation {
            lang: "lt",
            tts: Some("raudoni plaukai"),
            keywords: &["raudoni plaukai", "raudonplaukis", "rausvas"],
        },
        crate::Annotation {
            lang: "lv",
            tts: Some("sarkani mati"),
            keywords: &["rudi mati", "sarkani mati"],
        },
        crate::Annotation {
            lang: "mk",
            tts: Some("црвена коса"),
            keywords: &["црвена коса", "црвено-жолтеникава"],
        },
        crate::Annotation {
            lang: "ml",
            tts: Some("ച\u{d41}വന\u{d4d}ന മ\u{d41}ടി"),
            keywords: &[
                "ച\u{d41}വന\u{d4d}ന മ\u{d41}ടി",
                "ച\u{d41}വന\u{d4d}നതല",
                "ജിഞ\u{d4d}ചർ",
            ],
        },
        crate::Annotation {
            lang: "mn",
            tts: Some("улаан үс"),
            keywords: &["улаан шаргал", "улаан үс", "улаан үстэй толгой"],
        },
        crate::Annotation {
            lang: "mr",
            tts: Some("लाल क\u{947}स"),
            keywords: &["आल\u{947}", "लाल क\u{947}स", "लालडोक\u{947}"],
        },
        crate::Annotation {
            lang: "ms",
            tts: Some("rambut merah"),
            keywords: &["berambut merah", "perang", "rambut merah"],
        },
        crate::Annotation {
            lang: "my",
            tts: Some("ဆ\u{1036}ပင\u{103a}န\u{102e}"),
            keywords: &[
                "ချင\u{103a}းတက\u{103a}န\u{102e}ရောင\u{103a}",
                "ဆ\u{1036}ပင\u{103a}န\u{102e}",
            ],
        },
        crate::Annotation {
            lang: "nb",
            tts: Some("rødt hår"),
            keywords: &["rødhåring", "rødt hår"],
        },
        crate::Annotation {
            lang: "ne",
            tts: Some("रातो कपाल"),
            keywords: &["अद\u{941}\u{901}वा", "रातो कपाल", "रातो टाउको"],
        },
        crate::Annotation {
            lang: "nl",
            tts: Some("rood haar"),
            keywords: &["rood haar", "rooie", "rossig"],
        },
        crate::Annotation {
            lang: "nn",
            tts: Some("raudt hår"),
            keywords: &["raudhåring", "raudt hår"],
        },
        crate::Annotation {
            lang: "or",
            tts: Some("ନ\u{b3e}ଲ\u{b3f} କେଶ"),
            keywords: &[
                "ଅଦ\u{b3e}",
                "ନ\u{b3e}ଲ\u{b3f} କେଶ",
                "ନ\u{b3e}ଲ\u{b3f} ମ\u{b41}ଣ\u{b4d}ଡ",
            ],
        },
        crate::Annotation {
            lang: "pa",
            tts: Some("ਲਾਲ ਰ\u{a70}ਗ ਦ\u{a47} ਵਾਲ"),
            keywords: &[
                "ਲਾਲ ਰ\u{a70}ਗ ਦ\u{a47} ਵਾਲ",
                "ਲਾਲ ਵਾਲ",
                "ਲਾਲੀ ਮਾਰਦਾ ਪੀਲਾ ਰ\u{a70}ਗ",
            ],
        },
        crate::Annotation {
            lang: "pcm",
            tts: Some("Rẹ\u{301}d Hea"),
            keywords: &["Jínja", "Rẹ\u{301}d Hea", "Rẹ\u{301}dhẹd"],
        },
        crate::Annotation {
            lang: "pl",
            tts: Some("rude włosy"),
            keywords: &["ruda", "rude", "rude włosy", "rudy"],
        },
        crate::Annotation {
            lang: "ps",
            tts: Some("سره ويښتان"),
            keywords: &["جينګر", "سره ويښتان", "سور سر"],
        },
        crate::Annotation {
            lang: "pt",
            tts: Some("cabelo vermelho"),
            keywords: &["cabelo vermelho", "ruivo"],
        },
        crate::Annotation {
            lang: "pt_PT",
            tts: Some("cabelo ruivo"),
            keywords: &["cabelo ruivo", "ruiva", "ruivo"],
        },
        crate::Annotation {
            lang: "qu",
            tts: Some("puka chukcha"),
            keywords: &["puka chukcha", "pukachukcha", "qillu niqcha"],
        },
        crate::Annotation {
            lang: "rm",
            tts: Some("chavels cotschens"),
            keywords: &["chavels cotschens"],
        },
        crate::Annotation {
            lang: "ro",
            tts: Some("păr roșcat"),
            keywords: &["păr roșcat", "roșcat", "roșcată"],
        },
        crate::Annotation {
            lang: "root",
            tts: Some("E11-033"),
            keywords: &["E11-033"],
        },
        crate::Annotation {
            lang: "ru",
            tts: Some("рыжие волосы"),
            keywords: &["красный", "медный", "рыжая", "рыжие волосы", "рыжий"],
        },
        crate::Annotation {
            lang: "sd",
            tts: Some("ڳاڙها وار"),
            keywords: &["ادرڪ", "ڳاڙها وار", "ڳاڙهو مٿو"],
        },
        crate::Annotation {
            lang: "si",
            tts: Some("රත\u{dd4} කොණ\u{dca}ඩය"),
            keywords: &[
                "ඉඟ\u{dd4}ර\u{dd4}",
                "රත\u{dd4} කොණ\u{dca}ඩය",
                "රත\u{dd4} පැහැත\u{dd2}",
            ],
        },
        crate::Annotation {
            lang: "sk",
            tts: Some("ryšavé vlasy"),
            keywords: &["hrdzavý", "ryšavé vlasy", "červený"],
        },
        crate::Annotation {
            lang: "sl",
            tts: Some("rdeči lasje"),
            keywords: &["rdečelasec", "rdeči lasje", "redečelas"],
        },
        crate::Annotation {
            lang: "so",
            tts: Some("timo cas"),
            keywords: &["madax cas", "sinjibiil", "timo cas"],
        },
        crate::Annotation {
            lang: "sq",
            tts: Some("flokë të kuqe"),
            keywords: &["flokë të kuqe", "flokë të kuqërremtë", "kokëkuq", "kuqo"],
        },
        crate::Annotation {
            lang: "sr",
            tts: Some("црвена коса"),
            keywords: &["црвена", "црвена коса", "црвенокос"],
        },
        crate::Annotation {
            lang: "sr_Cyrl_BA",
            tts: Some("↑↑↑"),
            keywords: &["црвена коса"],
        },
        crate::Annotation {
            lang: "sr_Latn",
            tts: Some("crvena kosa"),
            keywords: &["crvena", "crvena kosa", "crvenokos"],
        },
        crate::Annotation {
            lang: "sr_Latn_BA",
            tts: None,
            keywords: &["crvena kosa"],
        },
        crate::Annotation {
            lang: "sv",
            tts: Some("rödhårig"),
            keywords: &["rödhårig", "röllig", "rött hår"],
        },
        crate::Annotation {
            lang: "sw",
            tts: Some("nywele nyekundu"),
            keywords: &["nyekundu", "nywele nyekundu"],
        },
        crate::Annotation {
            lang: "sw_KE",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "ta",
            tts: Some("சிவப\u{bcd}பு முடி"),
            keywords: &[
                "சிவப\u{bcd}பு தலை",
                "சிவப\u{bcd}பு முடி",
                "ஜிஞ\u{bcd}சர\u{bcd}",
            ],
        },
        crate::Annotation {
            lang: "te",
            tts: Some("ఎర\u{c4d}రట\u{c3f} జుట\u{c4d}టు"),
            keywords: &[
                "అల\u{c4d}లంరంగు",
                "ఎర\u{c4d}రజుట\u{c4d}టు ఉన\u{c4d}న తల",
                "ఎర\u{c4d}రట\u{c3f} జుట\u{c4d}టు",
            ],
        },
        crate::Annotation {
            lang: "th",
            tts: Some("ผมแดง"),
            keywords: &["ผมแดง", "ห\u{e31}วแดง"],
        },
        crate::Annotation {
            lang: "tk",
            tts: Some("gyzyl saç"),
            keywords: &["gyzyl saç", "gyzylsaç", "zenjebil"],
        },
        crate::Annotation {
            lang: "to",
            tts: Some("ʻulu kulokula"),
            keywords: &["kulokula", "ʻulu"],
        },
        crate::Annotation {
            lang: "tr",
            tts: Some("kızıl saç"),
            keywords: &["kırmızı", "kızıl", "kızıl saç"],
        },
        crate::Annotation {
            lang: "uk",
            tts: Some("руде волосся"),
            keywords: &["рижий", "руде волосся", "рудий", "рудоволосий"],
        },
        crate::Annotation {
            lang: "ur",
            tts: Some("سرخ بال"),
            keywords: &["ادرک", "سرخ بال", "سرخ سر"],
        },
        crate::Annotation {
            lang: "uz",
            tts: Some("malla soch"),
            keywords: &["malla", "qizil", "soch"],
        },
        crate::Annotation {
            lang: "vi",
            tts: Some("tóc đỏ"),
            keywords: &["tóc màu cam đỏ", "tóc màu đỏ", "tóc đỏ"],
        },
        crate::Annotation {
            lang: "yue",
            tts: Some("紅色頭髮"),
            keywords: &["生薑", "紅色嘅頭", "紅色頭髮"],
        },
        crate::Annotation {
            lang: "yue_Hans",
            tts: Some("红色头发"),
            keywords: &["生姜", "红色嘅头", "红色头发"],
        },
        crate::Annotation {
            lang: "zh",
            tts: Some("红发"),
            keywords: &["姜黄色", "红发"],
        },
        crate::Annotation {
            lang: "zh_Hant",
            tts: Some("紅髮"),
            keywords: &["紅髮", "薑黃"],
        },
        crate::Annotation {
            lang: "zh_Hant_HK",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "zu",
            tts: Some("izinwele ezibomvu"),
            keywords: &["ginger", "izinwele ezibomvu", "redhead"],
        },
    ],
};
#[doc = "🦱"]
pub const CURLY_HAIR: crate::Emoji = crate::Emoji {
    glyph: "🦱",
    codepoint: "1F9B1",
    status: crate::Status::Component,
    introduction_version: 11f32,
    name: "curly hair",
    group: "Component",
    subgroup: "hair-style",
    is_variant: false,
    variants: &[],
    annotations: &[
        crate::Annotation {
            lang: "af",
            tts: Some("krulhare"),
            keywords: &["afro", "krul", "krulhare", "krulletjie"],
        },
        crate::Annotation {
            lang: "am",
            tts: Some("የተጠቀለለ ጸጉር"),
            keywords: &["አፍሮ", "የተጠቀለለ", "የተጠቀለለ ጸጉር", "ጉንጉን"],
        },
        crate::Annotation {
            lang: "ar",
            tts: Some("شعر مجعد"),
            keywords: &["أفريقي", "جدائل", "شعر مجعد", "مجعد"],
        },
        crate::Annotation {
            lang: "as",
            tts: Some("কে\u{981}কোৰ\u{9be} চ\u{9c1}লি"),
            keywords: &[
                "আফ\u{9cd}ৰ’",
                "কে\u{981}কোৰ\u{9be}",
                "কে\u{981}কোৰ\u{9be} চ\u{9c1}লি",
                "জ\u{981}ট লগ\u{9be} চ\u{9c1}লি",
            ],
        },
        crate::Annotation {
            lang: "az",
            tts: Some("buruq saç"),
            keywords: &["afro", "buruq", "buruq saç", "zülf"],
        },
        crate::Annotation {
            lang: "be",
            tts: Some("курчавыя валасы"),
            keywords: &["афра", "завіткі", "курчавыя валасы", "кучары"],
        },
        crate::Annotation {
            lang: "bg",
            tts: Some("къдрава коса"),
            keywords: &["афро", "букли", "къдрава коса", "къдрици"],
        },
        crate::Annotation {
            lang: "bn",
            tts: Some("কো\u{981}কড\u{9bc}\u{9be} চ\u{9c1}ল"),
            keywords: &[
                "আফ\u{9cd}রো",
                "ক\u{9c1}ঞ\u{9cd}চিত",
                "কো\u{981}কড\u{9bc}\u{9be}",
                "কো\u{981}কড\u{9bc}\u{9be} চ\u{9c1}ল",
            ],
        },
        crate::Annotation {
            lang: "br",
            tts: Some("blev rodellek"),
            keywords: &["blev", "blev rodellek"],
        },
        crate::Annotation {
            lang: "bs",
            tts: Some("kovrdžava kosa"),
            keywords: &[
                "afro",
                "kovrdžav",
                "kovrdžava",
                "kovrdžava kosa",
                "kovrdže",
                "uvojci",
            ],
        },
        crate::Annotation {
            lang: "ca",
            tts: Some("cabells arrissats"),
            keywords: &["afro", "cabells arrissats", "rínxols"],
        },
        crate::Annotation {
            lang: "chr",
            tts: Some("ᎤᎵᏥᏍᏆᏁᏓ ᎤᏍᏘᎦ"),
            keywords: &["ᎤᎵᏥᏍᏆᏁᏓ", "ᎤᎵᏥᏍᏆᏁᏓ ᎤᏍᏘᎦ", "ᏙᏳ ᎤᎵᏥᏍᎪᏁᏓ", "ᏧᏃᏓᏊᏒᎵᏍᏗ"],
        },
        crate::Annotation {
            lang: "cs",
            tts: Some("kudrnaté vlasy"),
            keywords: &[
                "afro",
                "kudrnaté vlasy",
                "kudrny",
                "prstýnky",
                "vlnité vlasy",
            ],
        },
        crate::Annotation {
            lang: "cy",
            tts: Some("gwallt cyrliog"),
            keywords: &["afro", "cudynnau", "cyrliog", "gwallt cyrliog"],
        },
        crate::Annotation {
            lang: "da",
            tts: Some("krøllet hår"),
            keywords: &["afro", "krøller", "krøllet hår"],
        },
        crate::Annotation {
            lang: "de",
            tts: Some("lockiges Haar"),
            keywords: &["Afro", "Lockenkopf", "lockig", "lockiges Haar"],
        },
        crate::Annotation {
            lang: "el",
            tts: Some("σγουρά μαλλιά"),
            keywords: &["άφρο", "μπούκλες", "σγουρά", "σγουρά μαλλιά"],
        },
        crate::Annotation {
            lang: "en",
            tts: Some("curly hair"),
            keywords: &["afro", "curly", "curly hair", "ringlets"],
        },
        crate::Annotation {
            lang: "en_AU",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "en_CA",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "en_GB",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "en_IN",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "es",
            tts: Some("pelo rizado"),
            keywords: &[
                "afro",
                "bucle",
                "pelo rizado",
                "rizado",
                "rizo",
                "tirabuzón",
            ],
        },
        crate::Annotation {
            lang: "es_419",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "es_MX",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "es_US",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "et",
            tts: Some("lokkis juuksed"),
            keywords: &["afrojuuksed", "krussis juuksed", "lokid", "lokkis juuksed"],
        },
        crate::Annotation {
            lang: "eu",
            tts: Some("ile kizkur"),
            keywords: &["afro", "ile kizkur", "kiribil", "kizkur"],
        },
        crate::Annotation {
            lang: "fa",
            tts: Some("موفرفری"),
            keywords: &[
                "تابدار",
                "فرفری",
                "مجعد",
                "موفرفری",
                "موی فرفری",
                "موی مجعد",
            ],
        },
        crate::Annotation {
            lang: "fi",
            tts: Some("kiharatukkainen"),
            keywords: &["afrotukka", "kihara tukka", "kiharatukkainen"],
        },
        crate::Annotation {
            lang: "fil",
            tts: Some("kulot na buhok"),
            keywords: &["afro", "kulot", "kulot na buhok", "ringlets"],
        },
        crate::Annotation {
            lang: "fo",
            tts: Some("purlut hár"),
            keywords: &["afro", "hár", "krúllut", "purlut"],
        },
        crate::Annotation {
            lang: "fr",
            tts: Some("cheveux bouclés"),
            keywords: &["afro", "boucles", "bouclés", "cheveux bouclés"],
        },
        crate::Annotation {
            lang: "fr_CA",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "ga",
            tts: Some("gruaig chatach"),
            keywords: &["afró", "catach", "gruaig chatach", "lúba"],
        },
        crate::Annotation {
            lang: "gd",
            tts: Some("falt dualach"),
            keywords: &["Afraganach", "bachlach", "dualach", "falt"],
        },
        crate::Annotation {
            lang: "gl",
            tts: Some("pelo rizado"),
            keywords: &["bucles", "cabelo", "pelo afro", "pelo rizado", "rizo"],
        },
        crate::Annotation {
            lang: "gu",
            tts: Some("વા\u{a82}કડિયા વાળ"),
            keywords: &[
                "આફ\u{acd}રિકન વાળ",
                "વા\u{a82}કડિયા",
                "વા\u{a82}કડિયા વાળ",
                "વા\u{a82}કડિયાવાળની લટ",
            ],
        },
        crate::Annotation {
            lang: "he",
            tts: Some("שיער מתולתל"),
            keywords: &["אפרו", "מתולתל", "שיער מתולתל", "תלתלים"],
        },
        crate::Annotation {
            lang: "hi",
            tts: Some("घ\u{941}\u{901}घराल\u{947} बाल"),
            keywords: &[
                "अफ\u{93c}\u{94d}रीकी",
                "घ\u{941}\u{901}घराला",
                "घ\u{941}\u{901}घराल\u{947} बाल",
                "बालो\u{902} की लट",
            ],
        },
        crate::Annotation {
            lang: "hr",
            tts: Some("kovrčava kosa"),
            keywords: &["afro", "kovrčava", "kovrčava kosa", "lokne"],
        },
        crate::Annotation {
            lang: "hu",
            tts: Some("göndör haj"),
            keywords: &["afro", "göndör", "göndör haj", "loknis"],
        },
        crate::Annotation {
            lang: "hy",
            tts: Some("գանգրահեր"),
            keywords: &["աֆրո", "գանգուր", "գանգրահեր", "գանգրամազ", "խոպոպներ"],
        },
        crate::Annotation {
            lang: "ia",
            tts: Some("capillos crispe"),
            keywords: &["afro", "buclate", "buclettas", "capillos", "crispe"],
        },
        crate::Annotation {
            lang: "id",
            tts: Some("rambut keriting"),
            keywords: &["afro", "ikal", "keriting", "rambut keriting"],
        },
        crate::Annotation {
            lang: "is",
            tts: Some("krullur"),
            keywords: &["afró", "krullað hár", "krullur", "lokkar"],
        },
        crate::Annotation {
            lang: "it",
            tts: Some("capelli ricci"),
            keywords: &["afro", "boccoli", "capelli ricci", "ricci"],
        },
        crate::Annotation {
            lang: "ja",
            tts: Some("巻き毛"),
            keywords: &["くせ毛", "アフロ", "カール", "パンチパーマ", "巻き毛"],
        },
        crate::Annotation {
            lang: "jv",
            tts: Some("rambut brintik"),
            keywords: &["afro", "brintik", "prenthel-prenthel", "rambut brintik"],
        },
        crate::Annotation {
            lang: "ka",
            tts: Some("ხვეული თმა"),
            keywords: &["კულულები", "ხვეული თმა"],
        },
        crate::Annotation {
            lang: "kab",
            tts: Some("acekkuḥ\u{a0}imdewweṛ"),
            keywords: &["acekkuḥ\u{a0}imdewweṛ"],
        },
        crate::Annotation {
            lang: "kk",
            tts: Some("бұйра шаш"),
            keywords: &["афро", "бұйра", "бұйра шаш", "бұйраланған"],
        },
        crate::Annotation {
            lang: "km",
            tts: Some("សក\u{17cb}ក\u{17d2}រញាញ\u{17cb}"),
            keywords: &[
                "សក\u{17cb}ក\u{17d2}រញាញ\u{17cb}",
                "សក\u{17cb}ក\u{17d2}រញាញ\u{17cb}ទម\u{17d2}លាក\u{17cb}ច\u{17bb}ះក\u{17d2}រោម",
                "សក\u{17cb}ប\u{17c9}ោងក\u{17d2}រញាញ\u{17cb}",
            ],
        },
        crate::Annotation {
            lang: "kn",
            tts: Some("ಗುಂಗುರು ಕ\u{cc2}ದಲು"),
            keywords: &[
                "ಆಫ\u{ccd}ರೋ",
                "ಕರ\u{ccd}ಲ\u{cbf}",
                "ಗುಂಗುರು ಕ\u{cc2}ದಲು",
                "ರ\u{cbf}ಂಗ\u{ccd}ಲ\u{cc6}\u{200c}ಟ\u{ccd}\u{200c}ಗಳು",
            ],
        },
        crate::Annotation {
            lang: "ko",
            tts: Some("곱슬머리"),
            keywords: &["고수머리", "곱슬머리", "아프로"],
        },
        crate::Annotation {
            lang: "kok",
            tts: Some("क\u{941}रळ\u{947} म\u{941}दयाळ\u{947}\u{902} क\u{947}\u{902}स"),
            keywords: &[
                "आफ\u{94d}रो",
                "क\u{941}रळ\u{947}",
                "क\u{941}रळ\u{947} क\u{947}\u{902}स",
                "क\u{941}रळ\u{947} म\u{941}दयाळ\u{947}\u{902} क\u{947}\u{902}स",
                "म\u{941}दयाळ\u{947}\u{902}",
                "रि\u{902}गल\u{947}ट\u{94d}स",
            ],
        },
        crate::Annotation {
            lang: "ky",
            tts: Some("тармал чач"),
            keywords: &["афро", "тармал", "тармал чач", "тармалдашкан"],
        },
        crate::Annotation {
            lang: "lo",
            tts: Some("ຜ\u{ebb}ມກ\u{eb9}ດ"),
            keywords: &[
                "ຜ\u{ebb}ມກ\u{eb9}ດ",
                "ຜ\u{ebb}ມອາຟ\u{eb4}ກ",
                "ເປ\u{eb1}ນກ\u{ec9}ວນເປ\u{eb1}ນລອນ",
            ],
        },
        crate::Annotation {
            lang: "lt",
            tts: Some("garbanoti plaukai"),
            keywords: &["afro", "garbanos", "garbanotas", "garbanoti plaukai"],
        },
        crate::Annotation {
            lang: "lv",
            tts: Some("sprogaini mati"),
            keywords: &["afrikāņu", "sprogaini", "sprogaini mati", "sprogas"],
        },
        crate::Annotation {
            lang: "mk",
            tts: Some("кадрава коса"),
            keywords: &["афро", "кадрава", "кадрава коса", "локни"],
        },
        crate::Annotation {
            lang: "ml",
            tts: Some("ച\u{d41}ര\u{d41}ണ\u{d4d}ട മ\u{d41}ടി"),
            keywords: &[
                "ആഫ\u{d4d}രോ",
                "ച\u{d41}ര\u{d41}ണ\u{d4d}ട മ\u{d41}ടി",
                "ച\u{d41}ര\u{d41}ണ\u{d4d}ടത\u{d4d}",
                "റിംഗ\u{d4d}\u{200c}ലെറ\u{d4d}റ\u{d41}കൾ",
            ],
        },
        crate::Annotation {
            lang: "mn",
            tts: Some("буржгар үс"),
            keywords: &["афро", "буржгар", "буржгар үс", "ороосон үс"],
        },
        crate::Annotation {
            lang: "mr",
            tts: Some("क\u{941}रळ\u{947} क\u{947}स"),
            keywords: &[
                "अ\u{945}फ\u{94d}रो",
                "क\u{941}रळ\u{947}",
                "क\u{941}रळ\u{947} क\u{947}स",
                "रि\u{902}गल\u{947}ट\u{94d}स",
            ],
        },
        crate::Annotation {
            lang: "ms",
            tts: Some("rambut kerinting"),
            keywords: &["afro", "bergelung", "kerinting", "rambut kerinting"],
        },
        crate::Annotation {
            lang: "my",
            tts: Some("ဆ\u{1036}ပင\u{103a}ကောက\u{103a}"),
            keywords: &[
                "ဆ\u{1036}န\u{103d}ယ\u{103a}ခ\u{103d}ေ",
                "ဆ\u{1036}ပင\u{103a}ကောက\u{103a}",
                "လ\u{1030}မည\u{103a}းဆ\u{1036}ပင\u{103a}",
            ],
        },
        crate::Annotation {
            lang: "nb",
            tts: Some("kruset hår"),
            keywords: &["afrikansk", "afro", "kruset hår", "krøllet"],
        },
        crate::Annotation {
            lang: "ne",
            tts: Some("घ\u{941}म\u{94d}र\u{947}को कपाल"),
            keywords: &[
                "एफ\u{94d}रो",
                "घ\u{941}म\u{94d}र\u{947}को",
                "घ\u{941}म\u{94d}र\u{947}को कपाल",
                "रिङल\u{947}ट\u{94d}स",
            ],
        },
        crate::Annotation {
            lang: "nl",
            tts: Some("krullend haar"),
            keywords: &["afro", "krulhaar", "krullen", "krullend haar"],
        },
        crate::Annotation {
            lang: "nn",
            tts: Some("krusete hår"),
            keywords: &["afrikansk", "afro", "krusete hår", "krøllete"],
        },
        crate::Annotation {
            lang: "or",
            tts: Some("କ\u{b41}ଞ\u{b4d}ଚ\u{b3f}ତ କେଶ"),
            keywords: &[
                "ଆଫ\u{b4d}ରୋ",
                "କ\u{b41}ଞ\u{b4d}ଚ\u{b3f}ତ",
                "କ\u{b41}ଞ\u{b4d}ଚ\u{b3f}ତ କେଶ",
                "ର\u{b3f}ଙ\u{b4d}ଗଲେଟସ\u{b4d}\u{200c}",
            ],
        },
        crate::Annotation {
            lang: "pa",
            tts: Some("ਘ\u{a41}\u{a70}ਗਰਾਲ\u{a47} ਵਾਲ"),
            keywords: &[
                "ਐਫ\u{a4d}ਰ\u{a4b}",
                "ਘ\u{a41}\u{a70}ਗਰਾਲ\u{a47}",
                "ਘ\u{a41}\u{a70}ਗਰਾਲ\u{a47} ਵਾਲ",
                "ਵਾਲਾ\u{a02} ਦ\u{a47} ਕ\u{a41}\u{a70}ਡਲ",
            ],
        },
        crate::Annotation {
            lang: "pcm",
            tts: Some("Kọ\u{301}lí Hea"),
            keywords: &[
                "Kọ\u{301}li",
                "Kọ\u{301}lí Hea",
                "Lọ\u{301}ng Kọ\u{301}lí Hea",
                "Rínglẹts",
                "Áfró",
            ],
        },
        crate::Annotation {
            lang: "pl",
            tts: Some("kręcone włosy"),
            keywords: &[
                "afro",
                "kręcone",
                "kręcone włosy",
                "kędzierzawe",
                "kędzierzawy",
            ],
        },
        crate::Annotation {
            lang: "ps",
            tts: Some("لوپه ويښتان"),
            keywords: &["افرو", "لوپه", "لوپه ويښتان", "کجک"],
        },
        crate::Annotation {
            lang: "pt",
            tts: Some("cabelo cacheado"),
            keywords: &["afro", "cabelo cacheado", "cacheado", "encaracolado"],
        },
        crate::Annotation {
            lang: "pt_PT",
            tts: Some("cabelo encaracolado"),
            keywords: &["afro", "cabelo encaracolado", "caracóis", "encaracolado"],
        },
        crate::Annotation {
            lang: "qu",
            tts: Some("qaspa chukcha"),
            keywords: &["afro", "qaspa", "qaspa chukcha", "qiwicha"],
        },
        crate::Annotation {
            lang: "rm",
            tts: Some("chavels ritschads"),
            keywords: &["chavels ritschads"],
        },
        crate::Annotation {
            lang: "ro",
            tts: Some("păr creț"),
            keywords: &["afro", "bucle", "creț", "cârlionți", "păr creț"],
        },
        crate::Annotation {
            lang: "root",
            tts: Some("E11-034"),
            keywords: &["E11-034"],
        },
        crate::Annotation {
            lang: "ru",
            tts: Some("кудрявые волосы"),
            keywords: &[
                "афро",
                "кудри",
                "кудрявые волосы",
                "кудрявый",
                "химическая завивка",
                "химия",
            ],
        },
        crate::Annotation {
            lang: "sd",
            tts: Some("گهنگرالو وار"),
            keywords: &[
                "ايفرو",
                "رنگليٽس",
                "گهنگرالو وار",
                "گهنگهرالو",
                "گهنگهرالو وار",
            ],
        },
        crate::Annotation {
            lang: "si",
            tts: Some("රොද සහ\u{dd2}ත කොණ\u{dca}ඩය"),
            keywords: &[
                "අප\u{dca}\u{200d}ර\u{dd2}ක\u{dcf}න\u{dd4}",
                "ක\u{dd4}ඩ\u{dcf} ම\u{dd4}ද\u{dd4}",
                "රොද සහ\u{dd2}ත",
                "රොද සහ\u{dd2}ත කොණ\u{dca}ඩය",
            ],
        },
        crate::Annotation {
            lang: "sk",
            tts: Some("kučeravé vlasy"),
            keywords: &["afro", "kučeravé vlasy", "vlnistý"],
        },
        crate::Annotation {
            lang: "sl",
            tts: Some("kodrasti lasje"),
            keywords: &["afro", "koder", "kodrast", "kodrasti lasje"],
        },
        crate::Annotation {
            lang: "so",
            tts: Some("timo walaaqan"),
            keywords: &["timo adag", "timo laalaada", "timo walaaqan", "walaaqan"],
        },
        crate::Annotation {
            lang: "sq",
            tts: Some("flokë kaçurrele"),
            keywords: &["afro", "flokë kaçurrele", "kaçurrele", "rrica"],
        },
        crate::Annotation {
            lang: "sr",
            tts: Some("коврџава коса"),
            keywords: &["афро", "коврџава коса", "коврџе"],
        },
        crate::Annotation {
            lang: "sr_Cyrl_BA",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "sr_Latn",
            tts: Some("kovrdžava kosa"),
            keywords: &["afro", "kovrdžava kosa", "kovrdže"],
        },
        crate::Annotation {
            lang: "sv",
            tts: Some("lockigt hår"),
            keywords: &["afrohår", "korkskruvar", "lockar", "lockigt hår"],
        },
        crate::Annotation {
            lang: "sw",
            tts: Some("nywele yenye mawimbi"),
            keywords: &["afro", "mawimbi", "nywele yenye mawimbi"],
        },
        crate::Annotation {
            lang: "sw_KE",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "ta",
            tts: Some("சுருட\u{bcd}டை முடி"),
            keywords: &[
                "ஆஃப\u{bcd}ரோ",
                "சுருட\u{bcd}டை",
                "சுருட\u{bcd}டை முடி",
                "சுருள\u{bcd}",
            ],
        },
        crate::Annotation {
            lang: "te",
            tts: Some("ఉంగర\u{c3e}ల జుట\u{c4d}టు"),
            keywords: &[
                "ఆఫ\u{c4d}ర\u{c4b}",
                "ఉంగర\u{c3e}ల జుట\u{c4d}టు",
                "ఉంగర\u{c3e}లు",
                "ర\u{c3f}ంగుల జుట\u{c4d}టు",
            ],
        },
        crate::Annotation {
            lang: "th",
            tts: Some("ผมหย\u{e34}ก"),
            keywords: &["ผมลอน", "ผมหย\u{e34}ก", "หย\u{e34}ก", "แอฟโฟร"],
        },
        crate::Annotation {
            lang: "tk",
            tts: Some("buýra saç"),
            keywords: &["afro", "buýra", "buýra saç", "halkajyklar"],
        },
        crate::Annotation {
            lang: "to",
            tts: Some("ʻulu mingimingi"),
            keywords: &["mingimingi", "ʻulu"],
        },
        crate::Annotation {
            lang: "tr",
            tts: Some("kıvırcık saç"),
            keywords: &["afro", "kıvırcık", "kıvırcık saç", "lüle"],
        },
        crate::Annotation {
            lang: "uk",
            tts: Some("кучеряве волосся"),
            keywords: &[
                "афро",
                "волосся",
                "кудрі",
                "кучеряве волосся",
                "кучерявий",
                "кучері",
            ],
        },
        crate::Annotation {
            lang: "ur",
            tts: Some("گھنگھریالے بال"),
            keywords: &["افریقی", "گھنگھریالے", "گھنگھریالے بال", "گیسو"],
        },
        crate::Annotation {
            lang: "uz",
            tts: Some("jingalak soch"),
            keywords: &[
                "jingalak",
                "jingalak soch",
                "jingalak sochli",
                "kimyoviy",
                "kimyoviy ishlov berish",
            ],
        },
        crate::Annotation {
            lang: "vi",
            tts: Some("tóc xoăn"),
            keywords: &["quăn", "tóc xoăn", "xoăn", "xù"],
        },
        crate::Annotation {
            lang: "yue",
            tts: Some("曲髮"),
            keywords: &["捲曲", "捲髮", "曲髮", "非洲"],
        },
        crate::Annotation {
            lang: "yue_Hans",
            tts: Some("曲发"),
            keywords: &["卷发", "卷曲", "曲发", "非洲"],
        },
        crate::Annotation {
            lang: "zh",
            tts: Some("卷发"),
            keywords: &["卷发", "蓬松发", "鬈发"],
        },
        crate::Annotation {
            lang: "zh_Hant",
            tts: Some("卷髮"),
            keywords: &["卷髮", "圓蓬", "捲髮", "長捲髮"],
        },
        crate::Annotation {
            lang: "zh_Hant_HK",
            tts: Some("曲髮"),
            keywords: &["曲髮", "爆炸頭", "長曲髮"],
        },
        crate::Annotation {
            lang: "zu",
            tts: Some("curly hair"),
            keywords: &["afro", "curly", "curly hair", "ringlets"],
        },
    ],
};
#[doc = "🦳"]
pub const WHITE_HAIR: crate::Emoji = crate::Emoji {
    glyph: "🦳",
    codepoint: "1F9B3",
    status: crate::Status::Component,
    introduction_version: 11f32,
    name: "white hair",
    group: "Component",
    subgroup: "hair-style",
    is_variant: false,
    variants: &[],
    annotations: &[
        crate::Annotation {
            lang: "af",
            tts: Some("wit hare"),
            keywords: &["grys", "hare", "oud", "wit"],
        },
        crate::Annotation {
            lang: "am",
            tts: Some("ነጭ ጸጉር"),
            keywords: &["ነጭ", "አሮጌ", "ገብስማ", "ጸጉር"],
        },
        crate::Annotation {
            lang: "ar",
            tts: Some("شعر أبيض"),
            keywords: &["أبيض", "رمادي", "شعر", "قديم"],
        },
        crate::Annotation {
            lang: "as",
            tts: Some("বগ\u{9be} চ\u{9c1}লি"),
            keywords: &[
                "চ\u{9c1}লি",
                "পক\u{9be} চ\u{9c1}লি",
                "বগ\u{9be}",
                "বয\u{9bc}স\u{9cd}ক",
            ],
        },
        crate::Annotation {
            lang: "az",
            tts: Some("ağ saç"),
            keywords: &["ağ", "boz", "qoca", "saç"],
        },
        crate::Annotation {
            lang: "be",
            tts: Some("сівыя валасы"),
            keywords: &["белы", "валасы", "стары", "сівы", "сівыя валасы"],
        },
        crate::Annotation {
            lang: "bg",
            tts: Some("побеляла коса"),
            keywords: &["бяла", "коса", "побеляла коса", "сива", "старост"],
        },
        crate::Annotation {
            lang: "bn",
            tts: Some("স\u{9be}দ\u{9be} চ\u{9c1}ল"),
            keywords: &[
                "চ\u{9c1}ল",
                "ধ\u{9c2}সর",
                "প\u{9cd}রবীণ",
                "স\u{9be}দ\u{9be}",
            ],
        },
        crate::Annotation {
            lang: "br",
            tts: Some("blev gwenn"),
            keywords: &["blev", "blev gwenn"],
        },
        crate::Annotation {
            lang: "bs",
            tts: Some("sijeda kosa"),
            keywords: &["sijed", "sijeda", "sijeda kosa", "sivo", "star", "stara"],
        },
        crate::Annotation {
            lang: "ca",
            tts: Some("cabells blancs"),
            keywords: &["ancià", "blanc", "cabells", "cabells blancs", "gris"],
        },
        crate::Annotation {
            lang: "chr",
            tts: Some("ᎤᏁᎦ ᎤᏍᏘᎦ"),
            keywords: &["ᎠᎦᏴᎵ", "ᎠᏍᏘᏰᏅ", "ᎤᏁᎦ", "ᎤᏁᎦ ᎤᏍᏘᎦ", "ᎤᏍᎪᎸ ᏌᎪᏂᎨ"],
        },
        crate::Annotation {
            lang: "cs",
            tts: Some("bílé vlasy"),
            keywords: &["bílé vlasy", "stáří", "šediny", "šedé vlasy"],
        },
        crate::Annotation {
            lang: "cy",
            tts: Some("gwallt gwyn"),
            keywords: &["gwallt", "gwyn", "hen", "llwyd"],
        },
        crate::Annotation {
            lang: "da",
            tts: Some("hvidt hår"),
            keywords: &["gammel", "grå", "hvid", "hvidt hår", "hår"],
        },
        crate::Annotation {
            lang: "de",
            tts: Some("weißes Haar"),
            keywords: &[
                "grau",
                "graues Haar",
                "grauhaarig",
                "weißes Haar",
                "weißhaarig",
            ],
        },
        crate::Annotation {
            lang: "de_CH",
            tts: Some("weisses Haar"),
            keywords: &["weisses Haar"],
        },
        crate::Annotation {
            lang: "el",
            tts: Some("άσπρα μαλλιά"),
            keywords: &["άσπρα", "γκρίζα", "ηλικιωμένος", "λευκά", "μαλλιά"],
        },
        crate::Annotation {
            lang: "en",
            tts: Some("white hair"),
            keywords: &["gray", "hair", "old", "white"],
        },
        crate::Annotation {
            lang: "en_001",
            tts: None,
            keywords: &["grey", "hair", "old", "white"],
        },
        crate::Annotation {
            lang: "en_AU",
            tts: Some("↑↑↑"),
            keywords: &["grey", "hair", "old", "white"],
        },
        crate::Annotation {
            lang: "en_CA",
            tts: Some("↑↑↑"),
            keywords: &["gray", "grey", "hair", "old", "white"],
        },
        crate::Annotation {
            lang: "en_GB",
            tts: Some("↑↑↑"),
            keywords: &["grey", "hair", "old", "white"],
        },
        crate::Annotation {
            lang: "en_IN",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "es",
            tts: Some("pelo blanco"),
            keywords: &["blanco", "cana", "gris", "pelo", "viejo"],
        },
        crate::Annotation {
            lang: "es_419",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "es_MX",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "es_US",
            tts: Some("pelo canoso"),
            keywords: &["pelo canoso"],
        },
        crate::Annotation {
            lang: "et",
            tts: Some("heledad juuksed"),
            keywords: &["hallid", "heledad juuksed", "juuksed", "valged", "vana"],
        },
        crate::Annotation {
            lang: "eu",
            tts: Some("ilezuri"),
            keywords: &["gris", "ile", "ilezuri", "zahar", "zuri"],
        },
        crate::Annotation {
            lang: "fa",
            tts: Some("موسفید"),
            keywords: &[
                "خاکستری",
                "سفید",
                "موسفید",
                "موی خاکستری",
                "موی سفید",
                "پیر",
            ],
        },
        crate::Annotation {
            lang: "fi",
            tts: Some("valkotukkainen"),
            keywords: &["harmaa", "hiukset", "valkoinen", "valkotukkainen", "vanha"],
        },
        crate::Annotation {
            lang: "fil",
            tts: Some("puting buhok"),
            keywords: &["buhok", "kulay abo", "matanda", "puti", "puting buhok"],
        },
        crate::Annotation {
            lang: "fo",
            tts: Some("hvítt hár"),
            keywords: &["gamal", "gomul", "hvítt", "hár"],
        },
        crate::Annotation {
            lang: "fr",
            tts: Some("cheveux blancs"),
            keywords: &["blancs", "cheveux", "gris", "vieux"],
        },
        crate::Annotation {
            lang: "fr_CA",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "ga",
            tts: Some("gruaig bhán"),
            keywords: &["bán", "gruaig", "gruaig bhán", "liath", "sean"],
        },
        crate::Annotation {
            lang: "gd",
            tts: Some("falt bàn"),
            keywords: &["bàn", "falt", "liath", "sean"],
        },
        crate::Annotation {
            lang: "gl",
            tts: Some("pelo cano"),
            keywords: &["branco", "canas", "canoso", "gris", "pelo cano"],
        },
        crate::Annotation {
            lang: "gu",
            tts: Some("સફ\u{ac7}દ વાળ"),
            keywords: &["ગ\u{acd}ર\u{ac7}", "ઘરડા\u{a82}", "વાળ", "સફ\u{ac7}દ"],
        },
        crate::Annotation {
            lang: "he",
            tts: Some("שיער לבן"),
            keywords: &["אפור", "זקן", "לבן", "שיער"],
        },
        crate::Annotation {
            lang: "hi",
            tts: Some("सफ\u{93c}\u{947}द बाल"),
            keywords: &[
                "बाल",
                "भ\u{942}रा",
                "व\u{943}द\u{94d}ध",
                "सफ\u{93c}\u{947}द",
            ],
        },
        crate::Annotation {
            lang: "hr",
            tts: Some("sijeda kosa"),
            keywords: &["bijela", "kosa", "sijeda", "star"],
        },
        crate::Annotation {
            lang: "hu",
            tts: Some("ősz haj"),
            keywords: &["haj", "idős", "szürke", "ősz"],
        },
        crate::Annotation {
            lang: "hy",
            tts: Some("սպիտակահեր"),
            keywords: &["ալեհեր", "ծեր", "մազեր", "սպիտակ", "սպիտակահեր"],
        },
        crate::Annotation {
            lang: "ia",
            tts: Some("capillos blanc"),
            keywords: &["blanc", "capillos", "gris", "vetere", "vetule"],
        },
        crate::Annotation {
            lang: "id",
            tts: Some("rambut putih"),
            keywords: &["abu-abu", "putih", "rambut", "tua"],
        },
        crate::Annotation {
            lang: "is",
            tts: Some("hvítt hár"),
            keywords: &["gamalt", "grátt hár", "hvítt", "hár"],
        },
        crate::Annotation {
            lang: "it",
            tts: Some("capelli bianchi"),
            keywords: &["anziani", "bianchi", "capelli", "grigi"],
        },
        crate::Annotation {
            lang: "ja",
            tts: Some("白髪"),
            keywords: &["グレー", "年配", "白髪", "老人", "高齢者"],
        },
        crate::Annotation {
            lang: "jv",
            tts: Some("rambut putih"),
            keywords: &["putih", "rambut", "tuwa", "uwan"],
        },
        crate::Annotation {
            lang: "ka",
            tts: Some("თეთრი თმა"),
            keywords: &["თეთრი", "თმა", "მოხუცი", "ჭაღარა"],
        },
        crate::Annotation {
            lang: "kab",
            tts: Some("acekkuḥ\u{a0}amellal"),
            keywords: &["acekkuḥ\u{a0}amellal"],
        },
        crate::Annotation {
            lang: "kk",
            tts: Some("ақ шаш"),
            keywords: &["ақ", "сұр", "шаш", "қарт"],
        },
        crate::Annotation {
            lang: "km",
            tts: Some("សក\u{17cb}ស"),
            keywords: &[
                "ចាស\u{17cb}",
                "ស",
                "សក\u{17cb}",
                "សក\u{17cb}ស",
                "ស\u{17d2}ក\u{17bc}វ",
            ],
        },
        crate::Annotation {
            lang: "kn",
            tts: Some("ಬ\u{cbf}ಳ\u{cbf} ಕ\u{cc2}ದಲು"),
            keywords: &[
                "ಕ\u{cc2}ದಲು",
                "ಬ\u{cbf}ಳ\u{cbf}",
                "ಬ\u{cc2}ದು",
                "ಹಳ\u{cc6}ಯ",
            ],
        },
        crate::Annotation {
            lang: "ko",
            tts: Some("백발"),
            keywords: &["머리", "백발", "은발", "장년"],
        },
        crate::Annotation {
            lang: "kok",
            tts: Some("धव\u{947} क\u{947}\u{902}स"),
            keywords: &[
                "क\u{947}\u{902}स",
                "जाण\u{94d}ट\u{947}\u{902}",
                "धव\u{947} क\u{947}\u{902}स",
                "धव\u{947}\u{902}",
                "पिक\u{947} क\u{947}\u{902}स",
            ],
        },
        crate::Annotation {
            lang: "ky",
            tts: Some("ак чач"),
            keywords: &["ак", "буурул", "кары", "чач"],
        },
        crate::Annotation {
            lang: "lo",
            tts: Some("ຜ\u{ebb}ມຫອກ"),
            keywords: &[
                "ຂາວ",
                "ຜ\u{ebb}ມຫອກ",
                "ສ\u{eb5}ເທ\u{ebb}າ",
                "ເສ\u{eb1}\u{ec9}ນຜ\u{ebb}ມ",
                "ແກ\u{ec8}",
            ],
        },
        crate::Annotation {
            lang: "lt",
            tts: Some("žili plaukai"),
            keywords: &["baltas", "pilkas", "plaukai", "senas", "žili plaukai"],
        },
        crate::Annotation {
            lang: "lv",
            tts: Some("sirmi mati"),
            keywords: &["mati", "pelēki", "sirmi", "vecs"],
        },
        crate::Annotation {
            lang: "mk",
            tts: Some("бела коса"),
            keywords: &["бела", "коса", "седа", "стар"],
        },
        crate::Annotation {
            lang: "ml",
            tts: Some("വെള\u{d4d}ള മ\u{d41}ടി"),
            keywords: &[
                "ഗ\u{d4d}രേ",
                "മ\u{d41}ടി",
                "വയസ\u{d4d}സ\u{d3e}യത\u{d4d}",
                "വെള\u{d4d}ള",
            ],
        },
        crate::Annotation {
            lang: "mn",
            tts: Some("цагаан үс"),
            keywords: &["настай", "саарал", "цагаан", "үс"],
        },
        crate::Annotation {
            lang: "mr",
            tts: Some("पा\u{902}ढर\u{947} क\u{947}स"),
            keywords: &[
                "करड\u{947}",
                "क\u{947}स",
                "पा\u{902}ढर\u{947}",
                "पिकल\u{947}ल\u{947}",
            ],
        },
        crate::Annotation {
            lang: "ms",
            tts: Some("rambut putih"),
            keywords: &["beruban", "putih", "rambut", "tua"],
        },
        crate::Annotation {
            lang: "my",
            tts: Some("ဆ\u{1036}ပင\u{103a}ဖြ\u{1030}"),
            keywords: &[
                "ဆ\u{1036}ပင\u{103a}",
                "ဆ\u{1036}ပင\u{103a}ဖြ\u{1030}",
                "သက\u{103a}ကြ\u{102e}း",
                "အဖြ\u{1030}",
            ],
        },
        crate::Annotation {
            lang: "nb",
            tts: Some("grått hår"),
            keywords: &["gammel", "grå", "grått hår", "hvit", "hår"],
        },
        crate::Annotation {
            lang: "ne",
            tts: Some("स\u{947}तो कपाल"),
            keywords: &["कपाल", "ख\u{948}रो", "प\u{941}रानो", "स\u{947}तो"],
        },
        crate::Annotation {
            lang: "nl",
            tts: Some("wit haar"),
            keywords: &["grijs", "haar", "oud", "wit"],
        },
        crate::Annotation {
            lang: "nn",
            tts: Some("grått hår"),
            keywords: &["gamal", "grå", "grått hår", "hår", "kvit"],
        },
        crate::Annotation {
            lang: "or",
            tts: Some("ଧଳ\u{b3e} କେଶ"),
            keywords: &["କେଶ", "ଗ\u{b4d}ରେ", "ଧଳ\u{b3e}", "ପ\u{b41}ର\u{b41}ଣ\u{b3e}"],
        },
        crate::Annotation {
            lang: "pa",
            tts: Some("ਚਿ\u{a71}ਟ\u{a47} ਵਾਲ"),
            keywords: &["ਗ\u{a4d}ਰ\u{a47}", "ਚਿ\u{a71}ਟ\u{a47}", "ਵਧਦੀ ਉਮਰ", "ਵਾਲ"],
        },
        crate::Annotation {
            lang: "pcm",
            tts: Some("Waít Hea"),
            keywords: &["Gre", "Hea", "Old", "Wait", "Waít Hea"],
        },
        crate::Annotation {
            lang: "pl",
            tts: Some("białe włosy"),
            keywords: &["białe", "siwe", "starsza", "starszy", "włosy"],
        },
        crate::Annotation {
            lang: "ps",
            tts: Some("سپين ويښتان"),
            keywords: &["بوډا", "خړ", "سپين", "ويښتان"],
        },
        crate::Annotation {
            lang: "pt",
            tts: Some("cabelo branco"),
            keywords: &["branco", "cabelo", "grisalho", "velho"],
        },
        crate::Annotation {
            lang: "pt_PT",
            tts: Some("cabelo branco"),
            keywords: &["brancas", "branco", "cabelho grisalho", "cabelo", "velho"],
        },
        crate::Annotation {
            lang: "qu",
            tts: Some("yuraq chukcha"),
            keywords: &["chukcha", "machu", "uqi", "yuraq"],
        },
        crate::Annotation {
            lang: "ro",
            tts: Some("păr alb"),
            keywords: &["alb", "bătrân", "grizonat", "păr"],
        },
        crate::Annotation {
            lang: "root",
            tts: Some("E11-036"),
            keywords: &["E11-036"],
        },
        crate::Annotation {
            lang: "ru",
            tts: Some("седые волосы"),
            keywords: &[
                "волосы",
                "пожилой",
                "седина",
                "седой",
                "седые волосы",
                "старый",
            ],
        },
        crate::Annotation {
            lang: "sd",
            tts: Some("اڇا وار"),
            keywords: &["اڇا وار", "اڇو", "وار", "پراڻا", "ڀورا"],
        },
        crate::Annotation {
            lang: "si",
            tts: Some("ස\u{dd4}ද\u{dd4} කොන\u{dca}ඩය"),
            keywords: &[
                "අළ\u{dd4}",
                "කොණ\u{dca}ඩය",
                "වයස",
                "ස\u{dd4}ද\u{dd4}",
                "ස\u{dd4}ද\u{dd4} කොන\u{dca}ඩය",
            ],
        },
        crate::Annotation {
            lang: "sk",
            tts: Some("sivé vlasy"),
            keywords: &["biely", "sivé vlasy", "starý"],
        },
        crate::Annotation {
            lang: "sl",
            tts: Some("sivi lasje"),
            keywords: &["bel", "lasje", "siv", "sivi lasje", "star"],
        },
        crate::Annotation {
            lang: "so",
            tts: Some("caddaan"),
            keywords: &["caddaan", "gaboobay", "sibidhi", "timo", "timo cad"],
        },
        crate::Annotation {
            lang: "sq",
            tts: Some("flokë të bardha"),
            keywords: &[
                "flokë",
                "flokë të bardha",
                "gri",
                "i moshuar",
                "thinja",
                "të bardha",
            ],
        },
        crate::Annotation {
            lang: "sr",
            tts: Some("седа коса"),
            keywords: &["бела", "коса", "седа", "старо"],
        },
        crate::Annotation {
            lang: "sr_Cyrl_BA",
            tts: Some("сиједа коса"),
            keywords: &["сиједа коса"],
        },
        crate::Annotation {
            lang: "sr_Latn",
            tts: Some("seda kosa"),
            keywords: &["bela", "kosa", "seda", "staro"],
        },
        crate::Annotation {
            lang: "sr_Latn_BA",
            tts: Some("sijeda kosa"),
            keywords: &["sijeda kosa"],
        },
        crate::Annotation {
            lang: "sv",
            tts: Some("vithårig"),
            keywords: &["gammal", "grått hår", "vithårig", "vitt hår"],
        },
        crate::Annotation {
            lang: "sw",
            tts: Some("nywele nyeupe"),
            keywords: &["kijivu", "mzee", "nyeupe", "nywele"],
        },
        crate::Annotation {
            lang: "sw_KE",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "ta",
            tts: Some("வெள\u{bcd}ளை முடி"),
            keywords: &["நரை", "பழுப\u{bcd}பு", "முடி", "வெள\u{bcd}ளை"],
        },
        crate::Annotation {
            lang: "te",
            tts: Some("త\u{c46}ల\u{c4d}లజుట\u{c4d}టు"),
            keywords: &[
                "జుట\u{c4d}టు",
                "త\u{c46}లుపు",
                "త\u{c46}ల\u{c4d}లజుట\u{c4d}టు",
                "న\u{c46}ర\u{c3f}స\u{c3f}ప\u{c4b}వడం",
                "ముసల\u{c3f}తనం",
            ],
        },
        crate::Annotation {
            lang: "th",
            tts: Some("ผมขาว"),
            keywords: &["ขาว", "ผม", "ผมขาว", "หงอก", "แก\u{e48}"],
        },
        crate::Annotation {
            lang: "tk",
            tts: Some("ak saç"),
            keywords: &["ak", "garry", "saç", "çal"],
        },
        crate::Annotation {
            lang: "to",
            tts: Some("ʻulu hinā"),
            keywords: &["hinā", "ʻulu"],
        },
        crate::Annotation {
            lang: "tr",
            tts: Some("beyaz saç"),
            keywords: &["beyaz", "gri", "saç", "yaşlı"],
        },
        crate::Annotation {
            lang: "uk",
            tts: Some("сиве волосся"),
            keywords: &["білий", "волосся", "сиве волосся", "сивина", "старий"],
        },
        crate::Annotation {
            lang: "ur",
            tts: Some("سفید بال"),
            keywords: &["بال", "بوڑھا", "خاکستری", "سفید"],
        },
        crate::Annotation {
            lang: "uz",
            tts: Some("oqargan soch"),
            keywords: &["oq", "oqargan", "qari", "soch"],
        },
        crate::Annotation {
            lang: "vi",
            tts: Some("tóc trắng"),
            keywords: &["bạc", "trắng", "tóc", "xám"],
        },
        crate::Annotation {
            lang: "yue",
            tts: Some("白色頭髮"),
            keywords: &["灰色", "白色", "白色頭髮", "老", "頭髮"],
        },
        crate::Annotation {
            lang: "yue_Hans",
            tts: Some("白色头发"),
            keywords: &["头发", "灰色", "白色", "白色头发", "老"],
        },
        crate::Annotation {
            lang: "zh",
            tts: Some("白发"),
            keywords: &["头发", "年老", "灰色", "白发", "白色"],
        },
        crate::Annotation {
            lang: "zh_Hant",
            tts: Some("白髮"),
            keywords: &["灰色", "白色", "白髮", "老", "頭髮"],
        },
        crate::Annotation {
            lang: "zh_Hant_HK",
            tts: Some("白頭髮"),
            keywords: &["灰色", "白色", "白頭髮", "老", "頭髮"],
        },
        crate::Annotation {
            lang: "zu",
            tts: Some("izinwele ezimpunga"),
            keywords: &[
                "gray",
                "hair",
                "izinwele ezimhlophe",
                "izinwele ezimpunga",
                "old",
                "white",
            ],
        },
    ],
};
#[doc = "🦲"]
pub const BALD: crate::Emoji = crate::Emoji {
    glyph: "🦲",
    codepoint: "1F9B2",
    status: crate::Status::Component,
    introduction_version: 11f32,
    name: "bald",
    group: "Component",
    subgroup: "hair-style",
    is_variant: false,
    variants: &[],
    annotations: &[
        crate::Annotation {
            lang: "af",
            tts: Some("bles"),
            keywords: &[
                "bles",
                "chemoterapie",
                "haarloos",
                "kaalgeskeerde kop",
                "kaalkop",
            ],
        },
        crate::Annotation {
            lang: "am",
            tts: Some("መላጣ"),
            keywords: &["መላጣ", "ኬሞቴራፒ", "የተላጨ", "ጸጉር የሌለው"],
        },
        crate::Annotation {
            lang: "ar",
            tts: Some("أصلع"),
            keywords: &[
                "أصلع",
                "العلاج الكيميائي",
                "بدون شعر",
                "بلا شعر",
                "شعر محلوق",
            ],
        },
        crate::Annotation {
            lang: "as",
            tts: Some("টপ\u{9be} ম\u{9c2}ৰীয\u{9bc}\u{9be}"),
            keywords: &[
                "কেম’থেৰ\u{9be}পী",
                "চ\u{9c1}লি নোহোৱ\u{9be}",
                "চ\u{9c1}লিবিহীন",
                "টপ\u{9be} ম\u{9c2}ৰীয\u{9bc}\u{9be}",
                "ম\u{9c1}ণ\u{9cd}ডন কৰ\u{9be}",
            ],
        },
        crate::Annotation {
            lang: "az",
            tts: Some("keçəl"),
            keywords: &["keçəl", "kimya terapiyası", "qırxılmış", "saçsız"],
        },
        crate::Annotation {
            lang: "be",
            tts: Some("лысы"),
            keywords: &["без валасоў", "голены", "лысы", "хіміятэрапія"],
        },
        crate::Annotation {
            lang: "bg",
            tts: Some("плешив човек"),
            keywords: &[
                "без коса",
                "без коса от лъчетерапия",
                "избръснат",
                "няма коса",
                "плешив човек",
            ],
        },
        crate::Annotation {
            lang: "bn",
            tts: Some("নেড\u{9bc}\u{9be}"),
            keywords: &[
                "ক\u{9be}ম\u{9be}নো",
                "কেমোথের\u{9be}পি",
                "চ\u{9c1}ল নেই",
                "চ\u{9c1}ল হীন",
                "নেড\u{9bc}\u{9be}",
            ],
        },
        crate::Annotation {
            lang: "br",
            tts: Some("moal"),
            keywords: &["blev", "moal"],
        },
        crate::Annotation {
            lang: "bs",
            tts: Some("ćelavo"),
            keywords: &[
                "bez kose",
                "hemoterapija",
                "obrijan",
                "obrijana",
                "obrijano",
                "ćelavo",
            ],
        },
        crate::Annotation {
            lang: "ca",
            tts: Some("calvície"),
            keywords: &[
                "calb",
                "calba",
                "calvície",
                "cap afaitat",
                "quimioteràpia",
                "sense cabells",
            ],
        },
        crate::Annotation {
            lang: "chr",
            tts: Some("ᎤᎨᏬᏗ"),
            keywords: &["ᎠᏓᏰᏍᎩ ᏳᎾᎵᏍᏓᏁᎯ ᎨᏥᏅᏬᏙᏗ", "ᎤᎨᏬᏗ", "ᎤᎵᏍᏙᏰᏓ", "ᏄᏍᏘᎬᎾ", "Ꮭ ᏳᏍᏘᎦ"],
        },
        crate::Annotation {
            lang: "cs",
            tts: Some("bez vlasů"),
            keywords: &[
                "bez vlasů",
                "chemoterapie",
                "pleš",
                "skin",
                "skinhead",
                "vyholená hlava",
            ],
        },
        crate::Annotation {
            lang: "cy",
            tts: Some("moel"),
            keywords: &["cemotherapi", "dim gwallt", "moel", "wedi eillio"],
        },
        crate::Annotation {
            lang: "da",
            tts: Some("skaldet"),
            keywords: &[
                "barberet",
                "ingen hår",
                "kemoterapi",
                "kronraget",
                "skaldet",
            ],
        },
        crate::Annotation {
            lang: "de",
            tts: Some("Glatze"),
            keywords: &["Chemo", "Glatze", "haarlos", "kein Haar", "rasiert"],
        },
        crate::Annotation {
            lang: "el",
            tts: Some("καραφλός"),
            keywords: &["καραφλός", "ξυρισμένος", "χημειοθεραπεία", "χωρίς μαλλιά"],
        },
        crate::Annotation {
            lang: "en",
            tts: Some("bald"),
            keywords: &["bald", "chemotherapy", "hairless", "no hair", "shaven"],
        },
        crate::Annotation {
            lang: "en_AU",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "en_CA",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "en_GB",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "en_IN",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "es",
            tts: Some("sin pelo"),
            keywords: &[
                "afeitado",
                "bola de billar",
                "calvo",
                "quimioterapia",
                "sin pelo",
            ],
        },
        crate::Annotation {
            lang: "es_419",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "es_MX",
            tts: Some("↑↑↑"),
            keywords: &[
                "calvo",
                "quimioterapia",
                "rapado",
                "sin cabello",
                "sin pelo",
            ],
        },
        crate::Annotation {
            lang: "es_US",
            tts: Some("calvo"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "et",
            tts: Some("kiilaspea"),
            keywords: &[
                "juukseid pole",
                "juusteta",
                "keemiaravi",
                "kiilaspea",
                "raseeritud",
            ],
        },
        crate::Annotation {
            lang: "eu",
            tts: Some("burusoil"),
            keywords: &[
                "burusoil",
                "ilegabe",
                "ilerik gabe",
                "kimioterapia",
                "soildu",
            ],
        },
        crate::Annotation {
            lang: "fa",
            tts: Some("تاس"),
            keywords: &[
                "بدون مو",
                "بی\u{200c}مو",
                "تاس",
                "تراشیده",
                "شیمی\u{200c}درمانی",
                "طاس",
                "کچل",
            ],
        },
        crate::Annotation {
            lang: "fi",
            tts: Some("kalju"),
            keywords: &["ajeltu", "ei tukkaa", "kalju", "kemoterapia"],
        },
        crate::Annotation {
            lang: "fil",
            tts: Some("kalbo"),
            keywords: &["kalbo", "kimoterapya", "kinalbo", "walang buhok"],
        },
        crate::Annotation {
            lang: "fo",
            tts: Some("skallutur"),
            keywords: &["einki hár", "hár", "kemoterapi", "skallut", "skallutur"],
        },
        crate::Annotation {
            lang: "fr",
            tts: Some("chauve"),
            keywords: &[
                "chauve",
                "chimiothérapie",
                "imberbe",
                "rasé",
                "sans cheveux",
            ],
        },
        crate::Annotation {
            lang: "fr_CA",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "ga",
            tts: Some("maol"),
            keywords: &[
                "bearrtha",
                "blagaid",
                "ceimiteiripe",
                "gan ghruaig",
                "gruaig ar bith",
                "maol",
            ],
        },
        crate::Annotation {
            lang: "gd",
            tts: Some("maoilean"),
            keywords: &[
                "aillse",
                "bearradh",
                "bearrte",
                "ceimeo-theiripe",
                "gun fhalt",
                "lom",
                "maoilean",
                "maol",
            ],
        },
        crate::Annotation {
            lang: "gl",
            tts: Some("sen pelo"),
            keywords: &["calva", "quimioterapia", "rapado", "sen pelo"],
        },
        crate::Annotation {
            lang: "gu",
            tts: Some("ટાલ"),
            keywords: &[
                "કીમોથ\u{ac7}રાપી",
                "ટકો",
                "ટાલ",
                "વાળ નહી\u{a82}",
                "વાળ વગર",
            ],
        },
        crate::Annotation {
            lang: "he",
            tts: Some("קירח"),
            keywords: &["בלי שיער", "כימותרפיה", "ללא שיער", "מגולח", "קירח"],
        },
        crate::Annotation {
            lang: "hi",
            tts: Some("ग\u{902}जा"),
            keywords: &[
                "कीमोथ\u{948}र\u{947}पी",
                "ग\u{902}जा",
                "बाल नही\u{902}",
                "बिना बालो\u{902} क\u{947}",
                "म\u{941}\u{901}डा ह\u{941}आ",
            ],
        },
        crate::Annotation {
            lang: "hr",
            tts: Some("bez kose"),
            keywords: &["bez kose", "kemoterapija", "obrijano", "ćelav"],
        },
        crate::Annotation {
            lang: "hu",
            tts: Some("kopasz"),
            keywords: &["borotvált", "haj nélkül", "kemoterápia", "kopasz", "tar"],
        },
        crate::Annotation {
            lang: "hy",
            tts: Some("ճաղատ"),
            keywords: &["անմազ", "ճաղատ", "սափրված", "քաչալ"],
        },
        crate::Annotation {
            lang: "ia",
            tts: Some("calve"),
            keywords: &["calve", "chemotherapia", "glabre", "rasate", "sin capillos"],
        },
        crate::Annotation {
            lang: "id",
            tts: Some("gundul"),
            keywords: &["botak", "gundul", "kemoterapi", "tak berambut"],
        },
        crate::Annotation {
            lang: "is",
            tts: Some("skalli"),
            keywords: &[
                "hárleysi",
                "hárlos",
                "lyfjameðferð",
                "rakað höfuð",
                "skalli",
            ],
        },
        crate::Annotation {
            lang: "it",
            tts: Some("calvo"),
            keywords: &["calvizie", "calvo", "chemioterapia", "pelato", "rasato"],
        },
        crate::Annotation {
            lang: "ja",
            tts: Some("はげ頭"),
            keywords: &["はげ頭", "スキンヘッド", "化学療法", "坊主", "毛がない"],
        },
        crate::Annotation {
            lang: "jv",
            tts: Some("buthak"),
            keywords: &[
                "buthak",
                "gundhul",
                "kemoterapi",
                "ora duwe rambut",
                "plenthas",
            ],
        },
        crate::Annotation {
            lang: "ka",
            tts: Some("მელოტი"),
            keywords: &["მელოტი", "ქიმიოთერაპია"],
        },
        crate::Annotation {
            lang: "kab",
            tts: Some("aferḍas"),
            keywords: &["aferḍas"],
        },
        crate::Annotation {
            lang: "kk",
            tts: Some("тақырбас"),
            keywords: &[
                "тақырбас",
                "химиотерапия",
                "шаш жоқ",
                "шашсыз",
                "қырып тастаған",
            ],
        },
        crate::Annotation {
            lang: "km",
            tts: Some("ទ\u{17c6}ពែក"),
            keywords: &[
                "ការព\u{17d2}យាបាលតាមបែបគ\u{17b8}ម\u{17b8}",
                "គ\u{17d2}មានសក\u{17cb}",
                "ទ\u{17c6}ពែក",
                "បានកោរ",
                "អត\u{17cb}សក\u{17cb}",
            ],
        },
        crate::Annotation {
            lang: "kn",
            tts: Some("ಬಕ\u{ccd}ಕ ತಲ\u{cc6}"),
            keywords: &[
                "ಕೀಮೋಥ\u{cc6}ರಪ\u{cbf}",
                "ಕ\u{cc2}ದಲು ಇಲ\u{ccd}ಲ",
                "ಕ\u{cc2}ದಲುರಹ\u{cbf}ತ",
                "ಕ\u{ccd}ಷ\u{ccc}ರ ಮಾಡ\u{cbf}ರುವುದು",
                "ಬಕ\u{ccd}ಕ ತಲ\u{cc6}",
            ],
        },
        crate::Annotation {
            lang: "ko",
            tts: Some("대머리"),
            keywords: &["대머리", "맨머리", "민머리", "벗겨진 머리"],
        },
        crate::Annotation {
            lang: "kok",
            tts: Some("तकलो"),
            keywords: &[
                "क\u{945}मोथ\u{945}र\u{945}पी",
                "क\u{947}\u{902}स ना",
                "क\u{947}\u{902}सनाशिल\u{94d}लो",
                "तकलो",
                "त\u{941}ळत\u{941}ळीत",
            ],
        },
        crate::Annotation {
            lang: "ky",
            tts: Some("тас"),
            keywords: &["кырылган", "тас", "химия терапия", "чач жок", "чачсыз"],
        },
        crate::Annotation {
            lang: "lo",
            tts: Some("ຫ\u{ebb}ວລ\u{ec9}ານ"),
            keywords: &[
                "ການຮ\u{eb1}ກສາດ\u{ec9}ວຍ ກ\u{eb5}ໂມ",
                "ບ\u{ecd}\u{ec8}ມ\u{eb5}ຜ\u{ebb}ມ",
                "ຜ\u{ebb}ມລ\u{ebb}\u{ec8}ນ",
                "ຫ\u{ebb}ວລ\u{ec9}ານ",
                "ແຖມຜ\u{ebb}ມ",
            ],
        },
        crate::Annotation {
            lang: "lt",
            tts: Some("plikas"),
            keywords: &["beplaukis", "chemoterapija", "plikas", "skustas"],
        },
        crate::Annotation {
            lang: "lv",
            tts: Some("bez matiem"),
            keywords: &["bez matiem", "nav matu", "skūts", "ķīmijterapija"],
        },
        crate::Annotation {
            lang: "mk",
            tts: Some("ќелав"),
            keywords: &[
                "без влакна",
                "без коса",
                "избричено",
                "хемотерапија",
                "ќелав",
            ],
        },
        crate::Annotation {
            lang: "ml",
            tts: Some("കഷണ\u{d4d}ടി"),
            keywords: &[
                "കഷണ\u{d4d}ടി",
                "കഷണ\u{d4d}ടിയ\u{d3e}യ",
                "കീമോതെറ\u{d3e}പ\u{d4d}പി",
                "മ\u{d41}ടിയില\u{d4d}ല",
                "മൊട\u{d4d}ടയടിച\u{d4d}ച",
            ],
        },
        crate::Annotation {
            lang: "mn",
            tts: Some("халзан"),
            keywords: &[
                "халзан",
                "химийн эмчилгээ",
                "үс байхгүй",
                "үсгүй",
                "үсээ хусуулсан",
            ],
        },
        crate::Annotation {
            lang: "mr",
            tts: Some("टक\u{94d}कल"),
            keywords: &[
                "क\u{947}मोथ\u{947}रपी",
                "क\u{947}स नसल\u{947}ल\u{947}",
                "क\u{947}स नाही",
                "टक\u{94d}कल",
                "दाढी क\u{947}ल\u{947}ल\u{947}",
            ],
        },
        crate::Annotation {
            lang: "ms",
            tts: Some("botak"),
            keywords: &[
                "bercukur",
                "botak",
                "kemoterapi",
                "tiada rambut",
                "tidak berambut",
            ],
        },
        crate::Annotation {
            lang: "my",
            tts: Some("ထ\u{102d}ပ\u{103a}ပြောင\u{103a}"),
            keywords: &[
                "က\u{102e}မ\u{102d}\u{102f}",
                "ဆ\u{1036}ပင\u{103a}မရ\u{103e}\u{102d}",
                "ထ\u{102d}ပ\u{103a}ပြောင\u{103a}",
                "ရ\u{102d}တ\u{103a}ထားသည\u{103a}",
                "အမ\u{103d}ေးမရ\u{103e}\u{102d}",
            ],
        },
        crate::Annotation {
            lang: "nb",
            tts: Some("skallet"),
            keywords: &["barbert", "hårløs", "kjemoterapi", "skallet", "uten hår"],
        },
        crate::Annotation {
            lang: "ne",
            tts: Some("ताल\u{941} ख\u{941}इल\u{947}"),
            keywords: &[
                "कपाल नभएको",
                "क\u{947}मोथ\u{947}रापी",
                "ख\u{941}र\u{94d}क\u{947}को",
                "टक\u{94d}ल\u{941}",
                "ताल\u{941} ख\u{941}इल\u{947}",
            ],
        },
        crate::Annotation {
            lang: "nl",
            tts: Some("kaal"),
            keywords: &[
                "chemotherapie",
                "geen haar",
                "geschoren",
                "haarloos",
                "kaal",
            ],
        },
        crate::Annotation {
            lang: "nn",
            tts: Some("skalla"),
            keywords: &["barbert", "hårlaus", "kjemoterapi", "skalla", "utan hår"],
        },
        crate::Annotation {
            lang: "or",
            tts: Some("ଚନ\u{b4d}ଦ\u{b3e}"),
            keywords: &[
                "କ\u{b3f}ମୋଥେର\u{b3e}ପ\u{b3f}",
                "କୌଣସ\u{b3f} କେଶ ନ\u{b3e}ହ\u{b3f}\u{b01}",
                "ଖ\u{b3f}ଅର ହେବ\u{b3e}",
                "ଚନ\u{b4d}ଦ\u{b3e}",
            ],
        },
        crate::Annotation {
            lang: "pa",
            tts: Some("ਗ\u{a70}ਜਾ ਸਿਰ"),
            keywords: &[
                "ਕੀਮ\u{a4b}ਥ\u{a48}ਰ\u{a47}ਪੀ",
                "ਕ\u{a4b}ਈ ਵਾਲ ਨਹੀ\u{a02}",
                "ਗ\u{a70}ਜਾ ਸਿਰ",
                "ਮ\u{a41}\u{a70}ਨਿਆ ਸਿਰ",
                "ਵਾਲ-ਹੀਣ",
            ],
        },
        crate::Annotation {
            lang: "pcm",
            tts: Some("Bọld"),
            keywords: &[
                "Bọld",
                "Kimótẹ\u{301}rápi",
                "Nó Hea",
                "Shév Ọ\u{301}l Hea Kọmọ\u{301}t Fọ Hẹd",
            ],
        },
        crate::Annotation {
            lang: "pl",
            tts: Some("łysy"),
            keywords: &[
                "bez włosów",
                "bezwłosa",
                "bezwłosy",
                "chemioterapia",
                "ogolona",
                "łysy",
            ],
        },
        crate::Annotation {
            lang: "ps",
            tts: Some("ګنجى"),
            keywords: &["بې ويښانو", "بې ويښتو", "خرېدلې", "کيموتراپي", "ګنجى"],
        },
        crate::Annotation {
            lang: "pt",
            tts: Some("careca"),
            keywords: &[
                "careca",
                "nenhum cabelo",
                "quimioterapia",
                "raspado",
                "sem cabelo",
            ],
        },
        crate::Annotation {
            lang: "pt_PT",
            tts: Some("careca"),
            keywords: &[
                "careca",
                "nenhum cabelo",
                "quimioterapia",
                "rapado",
                "raspado",
            ],
        },
        crate::Annotation {
            lang: "qu",
            tts: Some("paqla"),
            keywords: &[
                "hairless",
                "mana chukchayuq",
                "paqla",
                "quimioterapia",
                "rutusqa",
            ],
        },
        crate::Annotation {
            lang: "ro",
            tts: Some("chelie"),
            keywords: &["chelie", "chimioterapie", "fără păr", "ras"],
        },
        crate::Annotation {
            lang: "root",
            tts: Some("E11-035"),
            keywords: &["E11-035"],
        },
        crate::Annotation {
            lang: "ru",
            tts: Some("без волос"),
            keywords: &["без волос", "бритый", "лысый", "химиотерапия"],
        },
        crate::Annotation {
            lang: "sd",
            tts: Some("گنجو"),
            keywords: &["بنا وار", "ڪو به وار نه", "ڪوڙيل", "ڪيمو ٿيراپي", "گنجو"],
        },
        crate::Annotation {
            lang: "si",
            tts: Some("තට\u{dca}ට"),
            keywords: &[
                "කොණ\u{dca}ඩය නැත\u{dd2}",
                "තට\u{dca}ට",
                "ම\u{dd4}ඩ",
                "රස\u{dcf}යන\u{dd2}ක ච\u{dd2}ක\u{dd2}ත\u{dca}ස\u{dcf}ව",
                "හ\u{dd2}සකෙස\u{dca} නැත\u{dd2}",
            ],
        },
        crate::Annotation {
            lang: "sk",
            tts: Some("holá hlava"),
            keywords: &[
                "bezvlasý",
                "holá hlava",
                "lysý",
                "plešatý",
                "plešivý",
                "vyholený",
            ],
        },
        crate::Annotation {
            lang: "sl",
            tts: Some("plešast"),
            keywords: &["brez las", "kamoterapija", "obrit", "plešast"],
        },
        crate::Annotation {
            lang: "so",
            tts: Some("bidaar"),
            keywords: &["bidaar", "bilaa timo", "kimiko ku dawayn", "xiiran"],
        },
        crate::Annotation {
            lang: "sq",
            tts: Some("qeros"),
            keywords: &["kimo-terapi", "kokërruar", "pa flokë", "qeros"],
        },
        crate::Annotation {
            lang: "sr",
            tts: Some("ћелав"),
            keywords: &["без косе", "обријан", "хемотерапија", "ћелав"],
        },
        crate::Annotation {
            lang: "sr_Cyrl_BA",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "sr_Latn",
            tts: Some("ćelav"),
            keywords: &["bez kose", "hemoterapija", "obrijan", "ćelav"],
        },
        crate::Annotation {
            lang: "sv",
            tts: Some("skallig"),
            keywords: &["kemoterapi", "skallig", "skinhead", "utan hår"],
        },
        crate::Annotation {
            lang: "sw",
            tts: Some("upara"),
            keywords: &[
                "bila nywele",
                "kichwa kilichonyolewa",
                "tibakemikali",
                "upara",
            ],
        },
        crate::Annotation {
            lang: "sw_KE",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "ta",
            tts: Some("வழுக\u{bcd}கை"),
            keywords: &[
                "க\u{bc0}மோதெரபி",
                "சவரம\u{bcd}",
                "முடியில\u{bcd}லை",
                "மொட\u{bcd}டை",
                "வழுக\u{bcd}கை",
            ],
        },
        crate::Annotation {
            lang: "te",
            tts: Some("బట\u{c4d}టతల"),
            keywords: &[
                "క\u{c40}మ\u{c4b}థ\u{c46}రప\u{c40}",
                "జుట\u{c4d}టు ర\u{c3e}ల\u{c3f}ప\u{c4b}వడం",
                "జుట\u{c4d}టు ల\u{c47}దు",
                "బట\u{c4d}టతల",
                "బ\u{c4b}డ\u{c3f} చ\u{c47}స\u{c3e}రు",
            ],
        },
        crate::Annotation {
            lang: "th",
            tts: Some("ห\u{e31}วล\u{e49}าน"),
            keywords: &[
                "ค\u{e35}โม",
                "สก\u{e34}นเฮด",
                "ห\u{e31}วล\u{e49}าน",
                "โกนห\u{e31}ว",
                "ไม\u{e48}ม\u{e35}ผม",
            ],
        },
        crate::Annotation {
            lang: "tk",
            tts: Some("kel"),
            keywords: &["himioterapiýa", "kel", "saç ýok", "saçsyz", "syrylan"],
        },
        crate::Annotation {
            lang: "to",
            tts: Some("ʻulu tula"),
            keywords: &["kosi", "tula", "ʻulu", "ʻulupoko"],
        },
        crate::Annotation {
            lang: "tr",
            tts: Some("kel"),
            keywords: &["kel", "kemoterapi", "saç yok", "saçsız", "tıraşlı"],
        },
        crate::Annotation {
            lang: "uk",
            tts: Some("лиса голова"),
            keywords: &[
                "без волосся",
                "виголений",
                "лиса голова",
                "немає волосся",
                "хіміотерапія",
            ],
        },
        crate::Annotation {
            lang: "ur",
            tts: Some("گنجا"),
            keywords: &["شیو کیا ہوا", "کوئی بال نہیں", "کیمیائی علاج", "گنجا"],
        },
        crate::Annotation {
            lang: "uz",
            tts: Some("kal"),
            keywords: &["kal", "kallik", "siyqa", "sochi yo‘q", "toz", "ustara"],
        },
        crate::Annotation {
            lang: "vi",
            tts: Some("hói"),
            keywords: &["cạo nhẵn", "hóa trị", "hói", "không có tóc", "trụi tóc"],
        },
        crate::Annotation {
            lang: "yue",
            tts: Some("光頭"),
            keywords: &["光頭", "剃頭", "化療", "無頭髮"],
        },
        crate::Annotation {
            lang: "yue_Hans",
            tts: Some("光头"),
            keywords: &["光头", "剃头", "化疗", "无头发"],
        },
        crate::Annotation {
            lang: "zh",
            tts: Some("秃顶"),
            keywords: &["光头", "化疗", "秃顶"],
        },
        crate::Annotation {
            lang: "zh_Hant",
            tts: Some("禿頭"),
            keywords: &["光頭", "剃頭", "化療", "沒頭髮", "禿頭"],
        },
        crate::Annotation {
            lang: "zh_Hant_HK",
            tts: Some("↑↑↑"),
            keywords: &["↑↑↑"],
        },
        crate::Annotation {
            lang: "zu",
            tts: Some("imbungculu"),
            keywords: &[
                "chemotherapy",
                "hairless",
                "imbungculu",
                "no hair",
                "shaven",
            ],
        },
    ],
};
