#[doc = "⬆\u{fe0f}"]
pub const UP_ARROW: crate::Emoji = crate::Emoji {
    glyph: "⬆\u{fe0f}",
    codepoint: "2B06 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "up arrow",
    group: "Symbols",
    subgroup: "arrow",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "⬆",
        codepoint: "2B06",
        status: crate::Status::Unqualified,
        introduction_version: 0.6f32,
        name: "up arrow",
        group: "Symbols",
        subgroup: "arrow",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("up arrow"),
        keywords: &["arrow", "cardinal", "direction", "north", "up arrow"],
    }],
};
#[doc = "↗\u{fe0f}"]
pub const UP_RIGHT_ARROW: crate::Emoji = crate::Emoji {
    glyph: "↗\u{fe0f}",
    codepoint: "2197 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "up-right arrow",
    group: "Symbols",
    subgroup: "arrow",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "↗",
        codepoint: "2197",
        status: crate::Status::Unqualified,
        introduction_version: 0.6f32,
        name: "up-right arrow",
        group: "Symbols",
        subgroup: "arrow",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("up-right arrow"),
        keywords: &[
            "arrow",
            "direction",
            "intercardinal",
            "northeast",
            "up-right arrow",
        ],
    }],
};
#[doc = "➡\u{fe0f}"]
pub const RIGHT_ARROW: crate::Emoji = crate::Emoji {
    glyph: "➡\u{fe0f}",
    codepoint: "27A1 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "right arrow",
    group: "Symbols",
    subgroup: "arrow",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "➡",
        codepoint: "27A1",
        status: crate::Status::Unqualified,
        introduction_version: 0.6f32,
        name: "right arrow",
        group: "Symbols",
        subgroup: "arrow",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("right arrow"),
        keywords: &["arrow", "cardinal", "direction", "east", "right arrow"],
    }],
};
#[doc = "↘\u{fe0f}"]
pub const DOWN_RIGHT_ARROW: crate::Emoji = crate::Emoji {
    glyph: "↘\u{fe0f}",
    codepoint: "2198 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "down-right arrow",
    group: "Symbols",
    subgroup: "arrow",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "↘",
        codepoint: "2198",
        status: crate::Status::Unqualified,
        introduction_version: 0.6f32,
        name: "down-right arrow",
        group: "Symbols",
        subgroup: "arrow",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("down-right arrow"),
        keywords: &[
            "arrow",
            "direction",
            "down-right arrow",
            "intercardinal",
            "southeast",
        ],
    }],
};
#[doc = "⬇\u{fe0f}"]
pub const DOWN_ARROW: crate::Emoji = crate::Emoji {
    glyph: "⬇\u{fe0f}",
    codepoint: "2B07 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "down arrow",
    group: "Symbols",
    subgroup: "arrow",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "⬇",
        codepoint: "2B07",
        status: crate::Status::Unqualified,
        introduction_version: 0.6f32,
        name: "down arrow",
        group: "Symbols",
        subgroup: "arrow",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("down arrow"),
        keywords: &["arrow", "cardinal", "direction", "down", "south"],
    }],
};
#[doc = "↙\u{fe0f}"]
pub const DOWN_LEFT_ARROW: crate::Emoji = crate::Emoji {
    glyph: "↙\u{fe0f}",
    codepoint: "2199 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "down-left arrow",
    group: "Symbols",
    subgroup: "arrow",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "↙",
        codepoint: "2199",
        status: crate::Status::Unqualified,
        introduction_version: 0.6f32,
        name: "down-left arrow",
        group: "Symbols",
        subgroup: "arrow",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("down-left arrow"),
        keywords: &[
            "arrow",
            "direction",
            "down-left arrow",
            "intercardinal",
            "southwest",
        ],
    }],
};
#[doc = "⬅\u{fe0f}"]
pub const LEFT_ARROW: crate::Emoji = crate::Emoji {
    glyph: "⬅\u{fe0f}",
    codepoint: "2B05 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "left arrow",
    group: "Symbols",
    subgroup: "arrow",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "⬅",
        codepoint: "2B05",
        status: crate::Status::Unqualified,
        introduction_version: 0.6f32,
        name: "left arrow",
        group: "Symbols",
        subgroup: "arrow",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("left arrow"),
        keywords: &["arrow", "cardinal", "direction", "left arrow", "west"],
    }],
};
#[doc = "↖\u{fe0f}"]
pub const UP_LEFT_ARROW: crate::Emoji = crate::Emoji {
    glyph: "↖\u{fe0f}",
    codepoint: "2196 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "up-left arrow",
    group: "Symbols",
    subgroup: "arrow",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "↖",
        codepoint: "2196",
        status: crate::Status::Unqualified,
        introduction_version: 0.6f32,
        name: "up-left arrow",
        group: "Symbols",
        subgroup: "arrow",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("up-left arrow"),
        keywords: &[
            "arrow",
            "direction",
            "intercardinal",
            "northwest",
            "up-left arrow",
        ],
    }],
};
#[doc = "↕\u{fe0f}"]
pub const UP_DOWN_ARROW: crate::Emoji = crate::Emoji {
    glyph: "↕\u{fe0f}",
    codepoint: "2195 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "up-down arrow",
    group: "Symbols",
    subgroup: "arrow",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "↕",
        codepoint: "2195",
        status: crate::Status::Unqualified,
        introduction_version: 0.6f32,
        name: "up-down arrow",
        group: "Symbols",
        subgroup: "arrow",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("up-down arrow"),
        keywords: &["arrow", "up-down arrow"],
    }],
};
#[doc = "↔\u{fe0f}"]
pub const LEFT_RIGHT_ARROW: crate::Emoji = crate::Emoji {
    glyph: "↔\u{fe0f}",
    codepoint: "2194 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "left-right arrow",
    group: "Symbols",
    subgroup: "arrow",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "↔",
        codepoint: "2194",
        status: crate::Status::Unqualified,
        introduction_version: 0.6f32,
        name: "left-right arrow",
        group: "Symbols",
        subgroup: "arrow",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("left-right arrow"),
        keywords: &["arrow", "left-right arrow"],
    }],
};
#[doc = "↩\u{fe0f}"]
pub const RIGHT_ARROW_CURVING_LEFT: crate::Emoji = crate::Emoji {
    glyph: "↩\u{fe0f}",
    codepoint: "21A9 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "right arrow curving left",
    group: "Symbols",
    subgroup: "arrow",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "↩",
        codepoint: "21A9",
        status: crate::Status::Unqualified,
        introduction_version: 0.6f32,
        name: "right arrow curving left",
        group: "Symbols",
        subgroup: "arrow",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("right arrow curving left"),
        keywords: &["arrow", "right arrow curving left"],
    }],
};
#[doc = "↪\u{fe0f}"]
pub const LEFT_ARROW_CURVING_RIGHT: crate::Emoji = crate::Emoji {
    glyph: "↪\u{fe0f}",
    codepoint: "21AA FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "left arrow curving right",
    group: "Symbols",
    subgroup: "arrow",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "↪",
        codepoint: "21AA",
        status: crate::Status::Unqualified,
        introduction_version: 0.6f32,
        name: "left arrow curving right",
        group: "Symbols",
        subgroup: "arrow",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("left arrow curving right"),
        keywords: &["arrow", "left arrow curving right"],
    }],
};
#[doc = "⤴\u{fe0f}"]
pub const RIGHT_ARROW_CURVING_UP: crate::Emoji = crate::Emoji {
    glyph: "⤴\u{fe0f}",
    codepoint: "2934 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "right arrow curving up",
    group: "Symbols",
    subgroup: "arrow",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "⤴",
        codepoint: "2934",
        status: crate::Status::Unqualified,
        introduction_version: 0.6f32,
        name: "right arrow curving up",
        group: "Symbols",
        subgroup: "arrow",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("right arrow curving up"),
        keywords: &["arrow", "right arrow curving up"],
    }],
};
#[doc = "⤵\u{fe0f}"]
pub const RIGHT_ARROW_CURVING_DOWN: crate::Emoji = crate::Emoji {
    glyph: "⤵\u{fe0f}",
    codepoint: "2935 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "right arrow curving down",
    group: "Symbols",
    subgroup: "arrow",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "⤵",
        codepoint: "2935",
        status: crate::Status::Unqualified,
        introduction_version: 0.6f32,
        name: "right arrow curving down",
        group: "Symbols",
        subgroup: "arrow",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("right arrow curving down"),
        keywords: &["arrow", "down", "right arrow curving down"],
    }],
};
#[doc = "🔃"]
pub const CLOCKWISE_VERTICAL_ARROWS: crate::Emoji = crate::Emoji {
    glyph: "🔃",
    codepoint: "1F503",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "clockwise vertical arrows",
    group: "Symbols",
    subgroup: "arrow",
    is_variant: false,
    variants: &[],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("clockwise vertical arrows"),
        keywords: &["arrow", "clockwise", "clockwise vertical arrows", "reload"],
    }],
};
#[doc = "🔄"]
pub const COUNTERCLOCKWISE_ARROWS_BUTTON: crate::Emoji = crate::Emoji {
    glyph: "🔄",
    codepoint: "1F504",
    status: crate::Status::FullyQualified,
    introduction_version: 1f32,
    name: "counterclockwise arrows button",
    group: "Symbols",
    subgroup: "arrow",
    is_variant: false,
    variants: &[],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("counterclockwise arrows button"),
        keywords: &[
            "anticlockwise",
            "arrow",
            "counterclockwise",
            "counterclockwise arrows button",
            "withershins",
        ],
    }],
};
#[doc = "🔙"]
pub const BACK_ARROW: crate::Emoji = crate::Emoji {
    glyph: "🔙",
    codepoint: "1F519",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "BACK arrow",
    group: "Symbols",
    subgroup: "arrow",
    is_variant: false,
    variants: &[],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("BACK arrow"),
        keywords: &["BACK arrow", "arrow", "back"],
    }],
};
#[doc = "🔚"]
pub const END_ARROW: crate::Emoji = crate::Emoji {
    glyph: "🔚",
    codepoint: "1F51A",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "END arrow",
    group: "Symbols",
    subgroup: "arrow",
    is_variant: false,
    variants: &[],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("END arrow"),
        keywords: &["END arrow", "arrow", "end"],
    }],
};
#[doc = "🔛"]
pub const ON_ARROW: crate::Emoji = crate::Emoji {
    glyph: "🔛",
    codepoint: "1F51B",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "ON! arrow",
    group: "Symbols",
    subgroup: "arrow",
    is_variant: false,
    variants: &[],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("ON! arrow"),
        keywords: &["ON! arrow", "arrow", "mark", "on"],
    }],
};
#[doc = "🔜"]
pub const SOON_ARROW: crate::Emoji = crate::Emoji {
    glyph: "🔜",
    codepoint: "1F51C",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "SOON arrow",
    group: "Symbols",
    subgroup: "arrow",
    is_variant: false,
    variants: &[],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("SOON arrow"),
        keywords: &["SOON arrow", "arrow", "soon"],
    }],
};
#[doc = "🔝"]
pub const TOP_ARROW: crate::Emoji = crate::Emoji {
    glyph: "🔝",
    codepoint: "1F51D",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "TOP arrow",
    group: "Symbols",
    subgroup: "arrow",
    is_variant: false,
    variants: &[],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("TOP arrow"),
        keywords: &["TOP arrow", "arrow", "top", "up"],
    }],
};
