#[doc = "♀\u{fe0f}"]
pub const FEMALE_SIGN: crate::Emoji = crate::Emoji {
    glyph: "♀\u{fe0f}",
    codepoint: "2640 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 4f32,
    name: "female sign",
    group: "Symbols",
    subgroup: "gender",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "♀",
        codepoint: "2640",
        status: crate::Status::Unqualified,
        introduction_version: 4f32,
        name: "female sign",
        group: "Symbols",
        subgroup: "gender",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("female sign"),
        keywords: &["female sign", "woman"],
    }],
};
#[doc = "♂\u{fe0f}"]
pub const MALE_SIGN: crate::Emoji = crate::Emoji {
    glyph: "♂\u{fe0f}",
    codepoint: "2642 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 4f32,
    name: "male sign",
    group: "Symbols",
    subgroup: "gender",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "♂",
        codepoint: "2642",
        status: crate::Status::Unqualified,
        introduction_version: 4f32,
        name: "male sign",
        group: "Symbols",
        subgroup: "gender",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("male sign"),
        keywords: &["male sign", "man"],
    }],
};
#[doc = "⚧\u{fe0f}"]
pub const TRANSGENDER_SYMBOL: crate::Emoji = crate::Emoji {
    glyph: "⚧\u{fe0f}",
    codepoint: "26A7 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 13f32,
    name: "transgender symbol",
    group: "Symbols",
    subgroup: "gender",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "⚧",
        codepoint: "26A7",
        status: crate::Status::Unqualified,
        introduction_version: 13f32,
        name: "transgender symbol",
        group: "Symbols",
        subgroup: "gender",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("transgender symbol"),
        keywords: &["transgender", "transgender symbol"],
    }],
};
