#[doc = "#\u{fe0f}\u{20e3}"]
pub const KEYCAP_POUND: crate::Emoji = crate::Emoji {
    glyph: "#\u{fe0f}\u{20e3}",
    codepoint: "0023 FE0F 20E3",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "keycap: #",
    group: "Symbols",
    subgroup: "keycap",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "#\u{20e3}",
        codepoint: "0023 20E3",
        status: crate::Status::Unqualified,
        introduction_version: 0.6f32,
        name: "keycap: #",
        group: "Symbols",
        subgroup: "keycap",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[],
};
#[doc = "*\u{fe0f}\u{20e3}"]
pub const KEYCAP_ASTERISK: crate::Emoji = crate::Emoji {
    glyph: "*\u{fe0f}\u{20e3}",
    codepoint: "002A FE0F 20E3",
    status: crate::Status::FullyQualified,
    introduction_version: 2f32,
    name: "keycap: *",
    group: "Symbols",
    subgroup: "keycap",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "*\u{20e3}",
        codepoint: "002A 20E3",
        status: crate::Status::Unqualified,
        introduction_version: 2f32,
        name: "keycap: *",
        group: "Symbols",
        subgroup: "keycap",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[],
};
#[doc = "0\u{fe0f}\u{20e3}"]
pub const KEYCAP_0: crate::Emoji = crate::Emoji {
    glyph: "0\u{fe0f}\u{20e3}",
    codepoint: "0030 FE0F 20E3",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "keycap: 0",
    group: "Symbols",
    subgroup: "keycap",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "0\u{20e3}",
        codepoint: "0030 20E3",
        status: crate::Status::Unqualified,
        introduction_version: 0.6f32,
        name: "keycap: 0",
        group: "Symbols",
        subgroup: "keycap",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[],
};
#[doc = "1\u{fe0f}\u{20e3}"]
pub const KEYCAP_1: crate::Emoji = crate::Emoji {
    glyph: "1\u{fe0f}\u{20e3}",
    codepoint: "0031 FE0F 20E3",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "keycap: 1",
    group: "Symbols",
    subgroup: "keycap",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "1\u{20e3}",
        codepoint: "0031 20E3",
        status: crate::Status::Unqualified,
        introduction_version: 0.6f32,
        name: "keycap: 1",
        group: "Symbols",
        subgroup: "keycap",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[],
};
#[doc = "2\u{fe0f}\u{20e3}"]
pub const KEYCAP_2: crate::Emoji = crate::Emoji {
    glyph: "2\u{fe0f}\u{20e3}",
    codepoint: "0032 FE0F 20E3",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "keycap: 2",
    group: "Symbols",
    subgroup: "keycap",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "2\u{20e3}",
        codepoint: "0032 20E3",
        status: crate::Status::Unqualified,
        introduction_version: 0.6f32,
        name: "keycap: 2",
        group: "Symbols",
        subgroup: "keycap",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[],
};
#[doc = "3\u{fe0f}\u{20e3}"]
pub const KEYCAP_3: crate::Emoji = crate::Emoji {
    glyph: "3\u{fe0f}\u{20e3}",
    codepoint: "0033 FE0F 20E3",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "keycap: 3",
    group: "Symbols",
    subgroup: "keycap",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "3\u{20e3}",
        codepoint: "0033 20E3",
        status: crate::Status::Unqualified,
        introduction_version: 0.6f32,
        name: "keycap: 3",
        group: "Symbols",
        subgroup: "keycap",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[],
};
#[doc = "4\u{fe0f}\u{20e3}"]
pub const KEYCAP_4: crate::Emoji = crate::Emoji {
    glyph: "4\u{fe0f}\u{20e3}",
    codepoint: "0034 FE0F 20E3",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "keycap: 4",
    group: "Symbols",
    subgroup: "keycap",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "4\u{20e3}",
        codepoint: "0034 20E3",
        status: crate::Status::Unqualified,
        introduction_version: 0.6f32,
        name: "keycap: 4",
        group: "Symbols",
        subgroup: "keycap",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[],
};
#[doc = "5\u{fe0f}\u{20e3}"]
pub const KEYCAP_5: crate::Emoji = crate::Emoji {
    glyph: "5\u{fe0f}\u{20e3}",
    codepoint: "0035 FE0F 20E3",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "keycap: 5",
    group: "Symbols",
    subgroup: "keycap",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "5\u{20e3}",
        codepoint: "0035 20E3",
        status: crate::Status::Unqualified,
        introduction_version: 0.6f32,
        name: "keycap: 5",
        group: "Symbols",
        subgroup: "keycap",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[],
};
#[doc = "6\u{fe0f}\u{20e3}"]
pub const KEYCAP_6: crate::Emoji = crate::Emoji {
    glyph: "6\u{fe0f}\u{20e3}",
    codepoint: "0036 FE0F 20E3",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "keycap: 6",
    group: "Symbols",
    subgroup: "keycap",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "6\u{20e3}",
        codepoint: "0036 20E3",
        status: crate::Status::Unqualified,
        introduction_version: 0.6f32,
        name: "keycap: 6",
        group: "Symbols",
        subgroup: "keycap",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[],
};
#[doc = "7\u{fe0f}\u{20e3}"]
pub const KEYCAP_7: crate::Emoji = crate::Emoji {
    glyph: "7\u{fe0f}\u{20e3}",
    codepoint: "0037 FE0F 20E3",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "keycap: 7",
    group: "Symbols",
    subgroup: "keycap",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "7\u{20e3}",
        codepoint: "0037 20E3",
        status: crate::Status::Unqualified,
        introduction_version: 0.6f32,
        name: "keycap: 7",
        group: "Symbols",
        subgroup: "keycap",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[],
};
#[doc = "8\u{fe0f}\u{20e3}"]
pub const KEYCAP_8: crate::Emoji = crate::Emoji {
    glyph: "8\u{fe0f}\u{20e3}",
    codepoint: "0038 FE0F 20E3",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "keycap: 8",
    group: "Symbols",
    subgroup: "keycap",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "8\u{20e3}",
        codepoint: "0038 20E3",
        status: crate::Status::Unqualified,
        introduction_version: 0.6f32,
        name: "keycap: 8",
        group: "Symbols",
        subgroup: "keycap",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[],
};
#[doc = "9\u{fe0f}\u{20e3}"]
pub const KEYCAP_9: crate::Emoji = crate::Emoji {
    glyph: "9\u{fe0f}\u{20e3}",
    codepoint: "0039 FE0F 20E3",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "keycap: 9",
    group: "Symbols",
    subgroup: "keycap",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "9\u{20e3}",
        codepoint: "0039 20E3",
        status: crate::Status::Unqualified,
        introduction_version: 0.6f32,
        name: "keycap: 9",
        group: "Symbols",
        subgroup: "keycap",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[],
};
#[doc = "🔟"]
pub const KEYCAP_10: crate::Emoji = crate::Emoji {
    glyph: "🔟",
    codepoint: "1F51F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "keycap: 10",
    group: "Symbols",
    subgroup: "keycap",
    is_variant: false,
    variants: &[],
    annotations: &[],
};
