#[doc = "🛐"]
pub const PLACE_OF_WORSHIP: crate::Emoji = crate::Emoji {
    glyph: "🛐",
    codepoint: "1F6D0",
    status: crate::Status::FullyQualified,
    introduction_version: 1f32,
    name: "place of worship",
    group: "Symbols",
    subgroup: "religion",
    is_variant: false,
    variants: &[],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("place of worship"),
        keywords: &["place of worship", "religion", "worship"],
    }],
};
#[doc = "⚛\u{fe0f}"]
pub const ATOM_SYMBOL: crate::Emoji = crate::Emoji {
    glyph: "⚛\u{fe0f}",
    codepoint: "269B FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 1f32,
    name: "atom symbol",
    group: "Symbols",
    subgroup: "religion",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "⚛",
        codepoint: "269B",
        status: crate::Status::Unqualified,
        introduction_version: 1f32,
        name: "atom symbol",
        group: "Symbols",
        subgroup: "religion",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("atom symbol"),
        keywords: &["atheist", "atom", "atom symbol"],
    }],
};
#[doc = "🕉\u{fe0f}"]
pub const OM: crate::Emoji = crate::Emoji {
    glyph: "🕉\u{fe0f}",
    codepoint: "1F549 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.7f32,
    name: "om",
    group: "Symbols",
    subgroup: "religion",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "🕉",
        codepoint: "1F549",
        status: crate::Status::Unqualified,
        introduction_version: 0.7f32,
        name: "om",
        group: "Symbols",
        subgroup: "religion",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("om"),
        keywords: &["Hindu", "om", "religion"],
    }],
};
#[doc = "✡\u{fe0f}"]
pub const STAR_OF_DAVID: crate::Emoji = crate::Emoji {
    glyph: "✡\u{fe0f}",
    codepoint: "2721 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.7f32,
    name: "star of David",
    group: "Symbols",
    subgroup: "religion",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "✡",
        codepoint: "2721",
        status: crate::Status::Unqualified,
        introduction_version: 0.7f32,
        name: "star of David",
        group: "Symbols",
        subgroup: "religion",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("star of David"),
        keywords: &[
            "David",
            "Jew",
            "Jewish",
            "religion",
            "star",
            "star of David",
        ],
    }],
};
#[doc = "☸\u{fe0f}"]
pub const WHEEL_OF_DHARMA: crate::Emoji = crate::Emoji {
    glyph: "☸\u{fe0f}",
    codepoint: "2638 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.7f32,
    name: "wheel of dharma",
    group: "Symbols",
    subgroup: "religion",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "☸",
        codepoint: "2638",
        status: crate::Status::Unqualified,
        introduction_version: 0.7f32,
        name: "wheel of dharma",
        group: "Symbols",
        subgroup: "religion",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("wheel of dharma"),
        keywords: &["Buddhist", "dharma", "religion", "wheel", "wheel of dharma"],
    }],
};
#[doc = "☯\u{fe0f}"]
pub const YIN_YANG: crate::Emoji = crate::Emoji {
    glyph: "☯\u{fe0f}",
    codepoint: "262F FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.7f32,
    name: "yin yang",
    group: "Symbols",
    subgroup: "religion",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "☯",
        codepoint: "262F",
        status: crate::Status::Unqualified,
        introduction_version: 0.7f32,
        name: "yin yang",
        group: "Symbols",
        subgroup: "religion",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("yin yang"),
        keywords: &["religion", "tao", "taoist", "yang", "yin"],
    }],
};
#[doc = "✝\u{fe0f}"]
pub const LATIN_CROSS: crate::Emoji = crate::Emoji {
    glyph: "✝\u{fe0f}",
    codepoint: "271D FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.7f32,
    name: "latin cross",
    group: "Symbols",
    subgroup: "religion",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "✝",
        codepoint: "271D",
        status: crate::Status::Unqualified,
        introduction_version: 0.7f32,
        name: "latin cross",
        group: "Symbols",
        subgroup: "religion",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("latin cross"),
        keywords: &["Christian", "cross", "latin cross", "religion"],
    }],
};
#[doc = "☦\u{fe0f}"]
pub const ORTHODOX_CROSS: crate::Emoji = crate::Emoji {
    glyph: "☦\u{fe0f}",
    codepoint: "2626 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 1f32,
    name: "orthodox cross",
    group: "Symbols",
    subgroup: "religion",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "☦",
        codepoint: "2626",
        status: crate::Status::Unqualified,
        introduction_version: 1f32,
        name: "orthodox cross",
        group: "Symbols",
        subgroup: "religion",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("orthodox cross"),
        keywords: &["Christian", "cross", "orthodox cross", "religion"],
    }],
};
#[doc = "☪\u{fe0f}"]
pub const STAR_AND_CRESCENT: crate::Emoji = crate::Emoji {
    glyph: "☪\u{fe0f}",
    codepoint: "262A FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.7f32,
    name: "star and crescent",
    group: "Symbols",
    subgroup: "religion",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "☪",
        codepoint: "262A",
        status: crate::Status::Unqualified,
        introduction_version: 0.7f32,
        name: "star and crescent",
        group: "Symbols",
        subgroup: "religion",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("star and crescent"),
        keywords: &["Muslim", "islam", "religion", "star and crescent"],
    }],
};
#[doc = "☮\u{fe0f}"]
pub const PEACE_SYMBOL: crate::Emoji = crate::Emoji {
    glyph: "☮\u{fe0f}",
    codepoint: "262E FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 1f32,
    name: "peace symbol",
    group: "Symbols",
    subgroup: "religion",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "☮",
        codepoint: "262E",
        status: crate::Status::Unqualified,
        introduction_version: 1f32,
        name: "peace symbol",
        group: "Symbols",
        subgroup: "religion",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("peace symbol"),
        keywords: &["peace", "peace symbol"],
    }],
};
#[doc = "🕎"]
pub const MENORAH: crate::Emoji = crate::Emoji {
    glyph: "🕎",
    codepoint: "1F54E",
    status: crate::Status::FullyQualified,
    introduction_version: 1f32,
    name: "menorah",
    group: "Symbols",
    subgroup: "religion",
    is_variant: false,
    variants: &[],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("menorah"),
        keywords: &["candelabrum", "candlestick", "menorah", "religion"],
    }],
};
#[doc = "🔯"]
pub const DOTTED_SIX_POINTED_STAR: crate::Emoji = crate::Emoji {
    glyph: "🔯",
    codepoint: "1F52F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "dotted six-pointed star",
    group: "Symbols",
    subgroup: "religion",
    is_variant: false,
    variants: &[],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("dotted six-pointed star"),
        keywords: &["dotted six-pointed star", "fortune", "star"],
    }],
};
