#[doc = "🏔\u{fe0f}"]
pub const SNOW_CAPPED_MOUNTAIN: crate::Emoji = crate::Emoji {
    glyph: "🏔\u{fe0f}",
    codepoint: "1F3D4 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.7f32,
    name: "snow-capped mountain",
    group: "Travel & Places",
    subgroup: "place-geographic",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "🏔",
        codepoint: "1F3D4",
        status: crate::Status::Unqualified,
        introduction_version: 0.7f32,
        name: "snow-capped mountain",
        group: "Travel & Places",
        subgroup: "place-geographic",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("snow-capped mountain"),
        keywords: &["cold", "mountain", "snow", "snow-capped mountain"],
    }],
};
#[doc = "⛰\u{fe0f}"]
pub const MOUNTAIN: crate::Emoji = crate::Emoji {
    glyph: "⛰\u{fe0f}",
    codepoint: "26F0 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.7f32,
    name: "mountain",
    group: "Travel & Places",
    subgroup: "place-geographic",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "⛰",
        codepoint: "26F0",
        status: crate::Status::Unqualified,
        introduction_version: 0.7f32,
        name: "mountain",
        group: "Travel & Places",
        subgroup: "place-geographic",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("mountain"),
        keywords: &["mountain"],
    }],
};
#[doc = "🌋"]
pub const VOLCANO: crate::Emoji = crate::Emoji {
    glyph: "🌋",
    codepoint: "1F30B",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "volcano",
    group: "Travel & Places",
    subgroup: "place-geographic",
    is_variant: false,
    variants: &[],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("volcano"),
        keywords: &["eruption", "mountain", "volcano"],
    }],
};
#[doc = "🗻"]
pub const MOUNT_FUJI: crate::Emoji = crate::Emoji {
    glyph: "🗻",
    codepoint: "1F5FB",
    status: crate::Status::FullyQualified,
    introduction_version: 0.6f32,
    name: "mount fuji",
    group: "Travel & Places",
    subgroup: "place-geographic",
    is_variant: false,
    variants: &[],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("mount fuji"),
        keywords: &["fuji", "mount fuji", "mountain"],
    }],
};
#[doc = "🏕\u{fe0f}"]
pub const CAMPING: crate::Emoji = crate::Emoji {
    glyph: "🏕\u{fe0f}",
    codepoint: "1F3D5 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.7f32,
    name: "camping",
    group: "Travel & Places",
    subgroup: "place-geographic",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "🏕",
        codepoint: "1F3D5",
        status: crate::Status::Unqualified,
        introduction_version: 0.7f32,
        name: "camping",
        group: "Travel & Places",
        subgroup: "place-geographic",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("camping"),
        keywords: &["camping"],
    }],
};
#[doc = "🏖\u{fe0f}"]
pub const BEACH_WITH_UMBRELLA: crate::Emoji = crate::Emoji {
    glyph: "🏖\u{fe0f}",
    codepoint: "1F3D6 FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.7f32,
    name: "beach with umbrella",
    group: "Travel & Places",
    subgroup: "place-geographic",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "🏖",
        codepoint: "1F3D6",
        status: crate::Status::Unqualified,
        introduction_version: 0.7f32,
        name: "beach with umbrella",
        group: "Travel & Places",
        subgroup: "place-geographic",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("beach with umbrella"),
        keywords: &["beach", "beach with umbrella", "umbrella"],
    }],
};
#[doc = "🏜\u{fe0f}"]
pub const DESERT: crate::Emoji = crate::Emoji {
    glyph: "🏜\u{fe0f}",
    codepoint: "1F3DC FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.7f32,
    name: "desert",
    group: "Travel & Places",
    subgroup: "place-geographic",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "🏜",
        codepoint: "1F3DC",
        status: crate::Status::Unqualified,
        introduction_version: 0.7f32,
        name: "desert",
        group: "Travel & Places",
        subgroup: "place-geographic",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("desert"),
        keywords: &["desert"],
    }],
};
#[doc = "🏝\u{fe0f}"]
pub const DESERT_ISLAND: crate::Emoji = crate::Emoji {
    glyph: "🏝\u{fe0f}",
    codepoint: "1F3DD FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.7f32,
    name: "desert island",
    group: "Travel & Places",
    subgroup: "place-geographic",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "🏝",
        codepoint: "1F3DD",
        status: crate::Status::Unqualified,
        introduction_version: 0.7f32,
        name: "desert island",
        group: "Travel & Places",
        subgroup: "place-geographic",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("desert island"),
        keywords: &["desert", "island"],
    }],
};
#[doc = "🏞\u{fe0f}"]
pub const NATIONAL_PARK: crate::Emoji = crate::Emoji {
    glyph: "🏞\u{fe0f}",
    codepoint: "1F3DE FE0F",
    status: crate::Status::FullyQualified,
    introduction_version: 0.7f32,
    name: "national park",
    group: "Travel & Places",
    subgroup: "place-geographic",
    is_variant: false,
    variants: &[crate::Emoji {
        glyph: "🏞",
        codepoint: "1F3DE",
        status: crate::Status::Unqualified,
        introduction_version: 0.7f32,
        name: "national park",
        group: "Travel & Places",
        subgroup: "place-geographic",
        is_variant: true,
        variants: &[],
        annotations: &[],
    }],
    annotations: &[crate::Annotation {
        lang: "en",
        tts: Some("national park"),
        keywords: &["national park", "park"],
    }],
};
